// Field icon bindings from Steam dedicated app 343050, scripts/map/customize.lua.
// Verified 2026-09-07; source SHA-256 864ecdb6427e9bd712b253682fbd514bb4faa86bf587c54666fd0fa58e3d7444.
// item.atlas or item.group.atlas selects the field icon; options_remap describes option values.

#[derive(Clone, Copy)]
pub(super) struct Icon {
    pub atlas: &'static str,
    pub element: &'static str,
}

pub(super) fn icon(native_key: &str) -> Option<Icon> {
    [
        ("worldgen_customization", WORLDGEN),
        ("worldsettings_customization", WORLDSETTINGS),
    ]
    .into_iter()
    .find_map(|(atlas, entries)| {
        entries
            .iter()
            .find(|(key, _)| *key == native_key)
            .map(|(_, element)| Icon { atlas, element })
    })
}

const WORLDGEN: &[(&str, &str)] = &[
    ("angrybees", "wasphive.tex"),
    ("balatro", "balatro_machine.tex"),
    ("banana", "banana.tex"),
    ("bats", "batcave.tex"),
    ("beefalo", "beefalo.tex"),
    ("bees", "beehive.tex"),
    ("berrybush", "berrybush.tex"),
    ("boons", "skeletons.tex"),
    ("branching", "world_branching.tex"),
    ("bunnymen", "bunnyhutch.tex"),
    ("buzzard", "buzzard.tex"),
    ("cactus", "cactus.tex"),
    ("carrot", "carrot.tex"),
    ("catcoon", "catcoonden.tex"),
    ("cave_ponds", "ponds.tex"),
    ("cave_spiders", "cave_spiderden.tex"),
    ("cavelight", "cavelight.tex"),
    ("chess", "chess_monsters.tex"),
    ("fern", "fern.tex"),
    ("fissure", "fissure.tex"),
    ("flint", "flint.tex"),
    ("flower_cave", "flower_cave.tex"),
    ("flowers", "flowers.tex"),
    ("grass", "grass.tex"),
    ("houndmound", "houndmound.tex"),
    ("junkyard", "junkyard.tex"),
    ("lichen", "lichen.tex"),
    ("lightninggoat", "lightning_goat.tex"),
    ("loop", "world_loop.tex"),
    ("marshbush", "marsh_bush.tex"),
    ("merm", "mermhut.tex"),
    ("meteorspawner", "burntground.tex"),
    ("moles", "molehill.tex"),
    ("monkey", "monkeybarrel.tex"),
    ("moon_berrybush", "moon_berrybush.tex"),
    ("moon_bullkelp", "moon_bullkelp.tex"),
    ("moon_carrot", "moon_carrot.tex"),
    ("moon_fissure", "moon_fissure.tex"),
    ("moon_fruitdragon", "moon_fruitdragon.tex"),
    ("moon_hotspring", "moon_hotspring.tex"),
    ("moon_rock", "moon_rock.tex"),
    ("moon_sapling", "moon_sapling.tex"),
    ("moon_spiders", "moon_spiders.tex"),
    ("moon_starfish", "moon_starfish.tex"),
    ("moon_tree", "moon_tree.tex"),
    ("mushroom", "mushrooms.tex"),
    ("mushtree", "mushtree.tex"),
    ("ocean_bullkelp", "ocean_bullkelp.tex"),
    ("ocean_otterdens", "ocean_otterdens.tex"),
    ("ocean_seastack", "ocean_seastack.tex"),
    ("ocean_shoal", "ocean_shoal.tex"),
    ("ocean_waterplant", "ocean_waterplant.tex"),
    ("ocean_wobsterden", "ocean_wobsterden.tex"),
    ("palmconetree", "palmconetree.tex"),
    ("pigs", "pighouse.tex"),
    ("ponds", "ponds.tex"),
    ("prefabswaps_start", "starting_variety.tex"),
    ("rabbits", "rabbithole.tex"),
    ("reeds", "reeds.tex"),
    ("roads", "roads.tex"),
    ("rock", "rock.tex"),
    ("rock_ice", "iceboulder.tex"),
    ("rocky", "rocky.tex"),
    ("sapling", "sapling.tex"),
    ("season_start", "season_start.tex"),
    ("slurper", "slurper.tex"),
    ("slurtles", "slurtleden.tex"),
    ("spiders", "spiderden.tex"),
    ("stageplays", "stageplays.tex"),
    ("start_location", "world_start.tex"),
    ("tallbirds", "tallbirdnest.tex"),
    ("task_set", "world_map.tex"),
    ("tentacles", "tentacles.tex"),
    ("terrariumchest", "terrarium.tex"),
    ("touchstone", "touchstone.tex"),
    ("tree_rock", "tree_rock.tex"),
    ("trees", "trees.tex"),
    ("tumbleweed", "tumbleweeds.tex"),
    ("walrus", "mactuskcamp.tex"),
    ("world_size", "world_size.tex"),
    ("wormlights", "wormlights.tex"),
    ("worms", "worms.tex"),
];

const WORLDSETTINGS: &[(&str, &str)] = &[
    ("acidrain_enabled", "acid_rain.tex"),
    ("alternatehunt", "alternatehunt.tex"),
    ("antliontribute", "antlion_tribute.tex"),
    ("atriumgate", "atriumgate.tex"),
    ("autumn", "autumn.tex"),
    ("bananabush_portalrate", "bananabush.tex"),
    ("basicresource_regrowth", "basicresource_regrowth.tex"),
    ("bats_setting", "bats.tex"),
    ("bearger", "bearger.tex"),
    ("beefaloheat", "beefaloheat.tex"),
    ("beequeen", "beequeen.tex"),
    ("bees_setting", "bees.tex"),
    ("birds", "birds.tex"),
    ("brightmarecreatures", "brightmarecreatures.tex"),
    ("bunnymen_setting", "bunnymen.tex"),
    ("butterfly", "butterfly.tex"),
    ("cactus_regrowth", "cactus.tex"),
    ("carrots_regrowth", "carrots.tex"),
    ("catcoons", "catcoons.tex"),
    ("chest_mimics", "chest_mimics.tex"),
    ("cookiecutters", "cookiecutters.tex"),
    ("crabking", "crabking.tex"),
    ("crow_carnival", "crowcarnival.tex"),
    ("darkness", "darkness.tex"),
    ("day", "day.tex"),
    ("daywalker", "daywalker.tex"),
    ("daywalker2", "daywalker2.tex"),
    ("deciduousmonster", "deciduouspoison.tex"),
    ("deciduoustree_regrowth", "deciduoustree.tex"),
    ("deerclops", "deerclops.tex"),
    ("dragonfly", "dragonfly.tex"),
    ("dropeverythingondespawn", "dropeverythingondespawn.tex"),
    ("dustmoths", "dustmoths.tex"),
    ("earthquakes", "earthquakes.tex"),
    ("evergreen_regrowth", "evergreen.tex"),
    ("extrastartingitems", "extrastartingitems.tex"),
    ("eyeofterror", "eyeofterror.tex"),
    ("fishschools", "fishschool.tex"),
    ("flower_cave_regrowth", "flower_cave.tex"),
    ("flowers_regrowth", "flowers.tex"),
    ("frograin", "frog_rain.tex"),
    ("frogs", "frogs.tex"),
    ("fruitfly", "fruitfly.tex"),
    ("ghostenabled", "ghostenabled.tex"),
    ("ghostsanitydrain", "ghostsanitydrain.tex"),
    ("gnarwail", "gnarwail.tex"),
    ("goosemoose", "goosemoose.tex"),
    ("grassgekkos", "grassgekkos.tex"),
    ("hallowed_nights", "hallowednights.tex"),
    ("healthpenalty", "healthpenalty.tex"),
    ("hound_mounds", "hounds.tex"),
    ("hounds", "houndattacks.tex"),
    ("hunger", "hunger.tex"),
    ("hunt", "tracks.tex"),
    ("itemmimics", "itemmimics.tex"),
    ("klaus", "klaus.tex"),
    ("krampus", "krampus.tex"),
    ("lessdamagetaken", "lessdamagetaken.tex"),
    ("liefs", "liefs.tex"),
    ("lightcrab_portalrate", "lightcrab.tex"),
    ("lightflier_flower_regrowth", "lightflier_flower.tex"),
    ("lightfliers", "lightfliers.tex"),
    ("lightning", "lightning.tex"),
    ("lunarhail_frequency", "lunar_hail.tex"),
    ("lureplants", "lureplants.tex"),
    ("malbatross", "malbatross.tex"),
    ("merms", "merms.tex"),
    ("meteorshowers", "meteor.tex"),
    ("molebats", "molebats.tex"),
    ("moles_setting", "moles.tex"),
    ("monkey_setting", "monkeys.tex"),
    ("monkeytail_portalrate", "monkeytail.tex"),
    ("moon_spider", "moon_spider.tex"),
    ("moon_tree_regrowth", "moon_tree.tex"),
    ("mosquitos", "mosquitos.tex"),
    ("mushgnome", "mushgnome.tex"),
    ("mushtree_moon_regrowth", "mushtree_moon.tex"),
    ("mushtree_regrowth", "mushtree.tex"),
    ("mutated_bearger", "mutated_bearger.tex"),
    ("mutated_bird_gestalt", "mutated_bird_gestalt.tex"),
    ("mutated_birds", "mutated_birds.tex"),
    ("mutated_buzzard_gestalt", "mutated_buzzard_gestalt.tex"),
    ("mutated_deerclops", "mutated_deerclops.tex"),
    ("mutated_hounds", "mutated_hounds.tex"),
    ("mutated_merm", "mutated_merm.tex"),
    ("mutated_spiderqueen", "mutated_spiderqueen.tex"),
    ("mutated_warg", "mutated_warg.tex"),
    ("nightmarecreatures", "nightmarecreatures.tex"),
    ("otters_setting", "otter.tex"),
    ("palmcone_seed_portalrate", "palmcone_seed.tex"),
    ("palmconetree_regrowth", "palmconetree.tex"),
    ("penguins", "pengull.tex"),
    ("penguins_moon", "moon_pengull.tex"),
    ("perd", "perd.tex"),
    ("petrification", "petrified_tree.tex"),
    ("pigs_setting", "pigs.tex"),
    ("pirateraids", "pirateattacks.tex"),
    ("portal_spawnrate", "monkeyportal.tex"),
    ("portalresurection", "portalresurection.tex"),
    ("powder_monkey_portalrate", "powder_monkey.tex"),
    ("rabbits_setting", "rabbits.tex"),
    ("reeds_regrowth", "reeds.tex"),
    ("regrowth", "regrowth.tex"),
    ("resettime", "resettime.tex"),
    ("rifts_enabled", "lunarrift_portal.tex"),
    ("rifts_enabled_cave", "shadowrift_portal.tex"),
    ("rifts_frequency", "lunarrift_portal.tex"),
    ("rifts_frequency_cave", "shadowrift_portal.tex"),
    ("rocky_setting", "rock_lobsters.tex"),
    ("saltstack_regrowth", "saltstack.tex"),
    ("seasonalstartingitems", "seasonalstartingitems.tex"),
    ("shadowcreatures", "shadowcreatures.tex"),
    ("sharkboi", "sharkboi.tex"),
    ("sharks", "sharks.tex"),
    ("slurtles_setting", "slurtles.tex"),
    ("snurtles", "snurtles.tex"),
    ("spawnmode", "spawnmode.tex"),
    ("spawnprotection", "spawnprotection.tex"),
    ("specialevent", "events.tex"),
    ("spider_dropper", "spider_dropper.tex"),
    ("spider_hider", "spider_hider.tex"),
    ("spider_spitter", "spider_spitter.tex"),
    ("spider_warriors", "spider_warriors.tex"),
    ("spiderqueen", "spiderqueen.tex"),
    ("spiders_setting", "spiders.tex"),
    ("spring", "spring.tex"),
    ("squid", "squid.tex"),
    ("summer", "summer.tex"),
    ("summerhounds", "summerhounds.tex"),
    ("temperaturedamage", "temperaturedamage.tex"),
    ("toadstool", "toadstool.tex"),
    ("tree_rock_regrowth", "tree_rock.tex"),
    ("twiggytrees_regrowth", "twiggytrees.tex"),
    ("walrus_setting", "mactusk.tex"),
    ("wanderingtrader_enabled", "wanderingtrader.tex"),
    ("wasps", "wasps.tex"),
    ("weather", "rain.tex"),
    ("wildfires", "smoke.tex"),
    ("winter", "winter.tex"),
    ("winterhounds", "winterhounds.tex"),
    ("winters_feast", "wintersfeast.tex"),
    ("wobsters", "wobsters.tex"),
    ("wormattacks", "wormattacks.tex"),
    ("wormattacks_boss", "wormattacks_boss.tex"),
    ("year_of_the_beefalo", "yotb_beefaloshrine.tex"),
    ("year_of_the_bunnyman", "yotr_rabbitshrine.tex"),
    ("year_of_the_carrat", "yotc_carratshrine.tex"),
    ("year_of_the_catcoon", "yot_catcoonshrine.tex"),
    ("year_of_the_dragonfly", "yotd_dragonshrine.tex"),
    ("year_of_the_gobbler", "perdshrine.tex"),
    ("year_of_the_knight", "yoth_knightshrine.tex"),
    ("year_of_the_pig", "pigshrine.tex"),
    ("year_of_the_snake", "yots_wormshrine.tex"),
    ("year_of_the_varg", "wargshrine.tex"),
];
