pub(super) type DstOverrideEntry = (&'static str, &'static str, &'static str);

// Klei customize.lua GetMasterOptions(), copied to secondary worlds by
// servercreationscreen.lua. master_controlled and master_sync are different sets.
pub(super) const DST_CAVES_INHERITED_OVERRIDE_KEYS: &[&str] = &[
    "basicresource_regrowth",
    "extrastartingitems",
    "seasonalstartingitems",
    "spawnprotection",
    "dropeverythingondespawn",
    "healthpenalty",
    "lessdamagetaken",
    "temperaturedamage",
    "hunger",
    "darkness",
    "shadowcreatures",
    "brightmarecreatures",
    "crow_carnival",
    "hallowed_nights",
    "winters_feast",
    "year_of_the_gobbler",
    "year_of_the_varg",
    "year_of_the_pig",
    "year_of_the_carrat",
    "year_of_the_beefalo",
    "year_of_the_catcoon",
    "year_of_the_bunnyman",
    "year_of_the_dragonfly",
    "year_of_the_snake",
    "year_of_the_knight",
    "specialevent",
    "day",
    "spawnmode",
    "ghostenabled",
    "portalresurection",
    "ghostsanitydrain",
    "resettime",
    "beefaloheat",
    "krampus",
];

pub(super) fn dst_caves_inherited_override_entries()
-> impl Iterator<Item = &'static DstOverrideEntry> {
    DST_SHARED_OVERRIDE_ENTRIES
        .iter()
        .chain(DST_MASTER_OVERRIDE_ENTRIES)
        .filter(|(_, native, _)| DST_CAVES_INHERITED_OVERRIDE_KEYS.contains(native))
}

pub(super) const DST_SHARED_OVERRIDE_ENTRIES: &[DstOverrideEntry] = &[
    ("world_specialevent", "specialevent", "default"),
    ("world_autumn", "autumn", "default"),
    ("world_winter", "winter", "default"),
    ("world_spring", "spring", "default"),
    ("world_summer", "summer", "default"),
    ("world_extrastartingitems", "extrastartingitems", "default"),
    (
        "world_seasonalstartingitems",
        "seasonalstartingitems",
        "default",
    ),
    ("world_spawnprotection", "spawnprotection", "default"),
    (
        "world_dropeverythingondespawn",
        "dropeverythingondespawn",
        "default",
    ),
    ("world_darkness", "darkness", "default"),
    ("world_temperaturedamage", "temperaturedamage", "default"),
    ("world_hunger", "hunger", "default"),
    ("world_healthpenalty", "healthpenalty", "always"),
    ("world_shadowcreatures", "shadowcreatures", "default"),
    (
        "world_brightmarecreatures",
        "brightmarecreatures",
        "default",
    ),
    ("world_crow_carnival", "crow_carnival", "default"),
    ("world_hallowed_nights", "hallowed_nights", "default"),
    ("world_winters_feast", "winters_feast", "default"),
    (
        "world_year_of_the_beefalo",
        "year_of_the_beefalo",
        "default",
    ),
    (
        "world_year_of_the_bunnyman",
        "year_of_the_bunnyman",
        "default",
    ),
    ("world_year_of_the_carrat", "year_of_the_carrat", "default"),
    (
        "world_year_of_the_catcoon",
        "year_of_the_catcoon",
        "default",
    ),
    (
        "world_year_of_the_dragonfly",
        "year_of_the_dragonfly",
        "default",
    ),
    (
        "world_year_of_the_gobbler",
        "year_of_the_gobbler",
        "default",
    ),
    ("world_year_of_the_knight", "year_of_the_knight", "default"),
    ("world_year_of_the_pig", "year_of_the_pig", "default"),
    ("world_year_of_the_snake", "year_of_the_snake", "default"),
    ("world_year_of_the_varg", "year_of_the_varg", "default"),
    ("world_ghostenabled", "ghostenabled", "always"),
    ("world_ghostsanitydrain", "ghostsanitydrain", "always"),
    ("world_portalresurection", "portalresurection", "none"),
    ("world_resettime", "resettime", "default"),
    ("world_spawnmode", "spawnmode", "fixed"),
    (
        "world_basicresource_regrowth",
        "basicresource_regrowth",
        "none",
    ),
    ("world_lessdamagetaken", "lessdamagetaken", "none"),
];

pub(super) const DST_MASTER_OVERRIDE_ENTRIES: &[DstOverrideEntry] = &[
    ("master_world_size", "world_size", "default"),
    ("master_season_start", "season_start", "default"),
    ("master_task_set", "task_set", "default"),
    ("master_start_location", "start_location", "default"),
    ("master_day", "day", "default"),
    ("master_beefaloheat", "beefaloheat", "default"),
    ("master_branching", "branching", "default"),
    ("master_loop", "loop", "default"),
    ("master_touchstone", "touchstone", "default"),
    ("master_roads", "roads", "default"),
    ("master_boons", "boons", "default"),
    ("master_prefabswaps_start", "prefabswaps_start", "default"),
    ("master_petrification", "petrification", "default"),
    ("master_meteorshowers", "meteorshowers", "default"),
    ("master_regrowth", "regrowth", "default"),
    (
        "master_deciduoustree_regrowth",
        "deciduoustree_regrowth",
        "default",
    ),
    ("master_carrots_regrowth", "carrots_regrowth", "default"),
    ("master_evergreen_regrowth", "evergreen_regrowth", "default"),
    ("master_flowers_regrowth", "flowers_regrowth", "default"),
    ("master_moon_tree_regrowth", "moon_tree_regrowth", "default"),
    ("master_saltstack_regrowth", "saltstack_regrowth", "default"),
    (
        "master_twiggytrees_regrowth",
        "twiggytrees_regrowth",
        "default",
    ),
    ("master_weather", "weather", "default"),
    ("master_frogs", "frogs", "default"),
    ("master_hounds", "hounds", "default"),
    ("master_lightning", "lightning", "default"),
    ("master_wildfires", "wildfires", "default"),
    ("master_berrybush", "berrybush", "default"),
    ("master_carrot", "carrot", "default"),
    ("master_flint", "flint", "default"),
    ("master_grass", "grass", "default"),
    ("master_marshbush", "marshbush", "default"),
    ("master_reeds", "reeds", "default"),
    ("master_rock", "rock", "default"),
    ("master_sapling", "sapling", "default"),
    ("master_trees", "trees", "default"),
    ("master_mushroom", "mushroom", "default"),
    ("master_flowers", "flowers", "default"),
    ("master_ponds", "ponds", "default"),
    ("master_tumbleweed", "tumbleweed", "default"),
    ("master_moon_fissure", "moon_fissure", "default"),
    ("master_moon_starfish", "moon_starfish", "default"),
    ("master_moon_bullkelp", "moon_bullkelp", "default"),
    ("master_ocean_bullkelp", "ocean_bullkelp", "default"),
    ("master_cactus", "cactus", "default"),
    ("master_moon_hotspring", "moon_hotspring", "default"),
    ("master_moon_rock", "moon_rock", "default"),
    ("master_moon_sapling", "moon_sapling", "default"),
    ("master_moon_tree", "moon_tree", "default"),
    ("master_meteorspawner", "meteorspawner", "default"),
    ("master_rock_ice", "rock_ice", "default"),
    ("master_ocean_seastack", "ocean_seastack", "ocean_default"),
    ("master_moon_berrybush", "moon_berrybush", "default"),
    ("master_bees", "bees", "default"),
    ("master_beefalo", "beefalo", "default"),
    ("master_butterfly", "butterfly", "default"),
    ("master_buzzard", "buzzard", "default"),
    ("master_catcoon", "catcoon", "default"),
    ("master_moles", "moles", "default"),
    ("master_pigs", "pigs", "default"),
    ("master_rabbits", "rabbits", "default"),
    ("master_lightninggoat", "lightninggoat", "default"),
    ("master_spiders", "spiders", "default"),
    ("master_tallbirds", "tallbirds", "default"),
    ("master_tentacles", "tentacles", "default"),
    ("master_moon_carrot", "moon_carrot", "default"),
    ("master_moon_fruitdragon", "moon_fruitdragon", "default"),
    ("master_ocean_shoal", "ocean_shoal", "default"),
    ("master_ocean_wobsterden", "ocean_wobsterden", "default"),
    (
        "master_ocean_waterplant",
        "ocean_waterplant",
        "ocean_default",
    ),
    ("master_moon_spiders", "moon_spiders", "default"),
    ("master_penguins", "penguins", "default"),
    ("master_perd", "perd", "default"),
    ("master_bees_setting", "bees_setting", "default"),
    ("master_birds", "birds", "default"),
    ("master_bunnymen_setting", "bunnymen_setting", "default"),
    ("master_catcoons", "catcoons", "default"),
    ("master_gnarwail", "gnarwail", "default"),
    ("master_grassgekkos", "grassgekkos", "default"),
    ("master_moles_setting", "moles_setting", "default"),
    ("master_fishschools", "fishschools", "default"),
    ("master_wobsters", "wobsters", "default"),
    ("master_bats_setting", "bats_setting", "default"),
    ("master_cookiecutters", "cookiecutters", "default"),
    ("master_mutated_hounds", "mutated_hounds", "default"),
    ("master_wasps", "wasps", "default"),
    ("master_merms", "merms", "default"),
    ("master_penguins_moon", "penguins_moon", "default"),
    ("master_mosquitos", "mosquitos", "default"),
    ("master_sharks", "sharks", "default"),
    ("master_moon_spider", "moon_spider", "default"),
    ("master_squid", "squid", "default"),
    ("master_spider_warriors", "spider_warriors", "default"),
    ("master_angrybees", "angrybees", "default"),
    ("master_chess", "chess", "default"),
    ("master_antliontribute", "antliontribute", "default"),
    ("master_krampus", "krampus", "default"),
    ("master_walrus", "walrus", "default"),
    ("master_merm", "merm", "default"),
    ("master_houndmound", "houndmound", "default"),
    ("master_lureplants", "lureplants", "default"),
    ("master_bearger", "bearger", "default"),
    ("master_beequeen", "beequeen", "default"),
    ("master_crabking", "crabking", "default"),
    ("master_deerclops", "deerclops", "default"),
    ("master_dragonfly", "dragonfly", "default"),
    ("master_fruitfly", "fruitfly", "default"),
    ("master_klaus", "klaus", "default"),
    ("master_malbatross", "malbatross", "default"),
    ("master_deciduousmonster", "deciduousmonster", "default"),
    ("master_goosemoose", "goosemoose", "default"),
    ("master_spiderqueen", "spiderqueen", "default"),
    ("master_liefs", "liefs", "default"),
    ("master_ocean_otterdens", "ocean_otterdens", "default"),
    ("master_balatro", "balatro", "default"),
    ("master_junkyard", "junkyard", "default"),
    ("master_stageplays", "stageplays", "default"),
    ("master_terrariumchest", "terrariumchest", "default"),
    ("master_palmconetree", "palmconetree", "default"),
    ("master_otters_setting", "otters_setting", "default"),
    ("master_pigs_setting", "pigs_setting", "default"),
    ("master_rabbits_setting", "rabbits_setting", "default"),
    ("master_daywalker2", "daywalker2", "default"),
    ("master_eyeofterror", "eyeofterror", "default"),
    ("master_sharkboi", "sharkboi", "default"),
    ("master_mutated_bearger", "mutated_bearger", "default"),
    (
        "master_mutated_bird_gestalt",
        "mutated_bird_gestalt",
        "default",
    ),
    ("master_mutated_birds", "mutated_birds", "default"),
    (
        "master_mutated_buzzard_gestalt",
        "mutated_buzzard_gestalt",
        "default",
    ),
    ("master_mutated_deerclops", "mutated_deerclops", "default"),
    ("master_mutated_merm", "mutated_merm", "default"),
    (
        "master_mutated_spiderqueen",
        "mutated_spiderqueen",
        "default",
    ),
    ("master_mutated_warg", "mutated_warg", "default"),
    ("master_alternatehunt", "alternatehunt", "default"),
    ("master_frograin", "frograin", "default"),
    ("master_hunt", "hunt", "default"),
    (
        "master_lunarhail_frequency",
        "lunarhail_frequency",
        "default",
    ),
    ("master_rifts_enabled", "rifts_enabled", "default"),
    ("master_rifts_frequency", "rifts_frequency", "default"),
    ("master_summerhounds", "summerhounds", "default"),
    (
        "master_wanderingtrader_enabled",
        "wanderingtrader_enabled",
        "always",
    ),
    ("master_winterhounds", "winterhounds", "default"),
    ("master_hound_mounds", "hound_mounds", "default"),
    ("master_pirateraids", "pirateraids", "default"),
    ("master_spiders_setting", "spiders_setting", "default"),
    ("master_walrus_setting", "walrus_setting", "default"),
    ("master_portal_spawnrate", "portal_spawnrate", "default"),
    (
        "master_bananabush_portalrate",
        "bananabush_portalrate",
        "default",
    ),
    (
        "master_lightcrab_portalrate",
        "lightcrab_portalrate",
        "default",
    ),
    (
        "master_monkeytail_portalrate",
        "monkeytail_portalrate",
        "default",
    ),
    (
        "master_palmcone_seed_portalrate",
        "palmcone_seed_portalrate",
        "default",
    ),
    (
        "master_powder_monkey_portalrate",
        "powder_monkey_portalrate",
        "default",
    ),
    ("master_cactus_regrowth", "cactus_regrowth", "default"),
    (
        "master_palmconetree_regrowth",
        "palmconetree_regrowth",
        "default",
    ),
    ("master_reeds_regrowth", "reeds_regrowth", "default"),
];

pub(super) const DST_CAVES_OVERRIDE_ENTRIES: &[DstOverrideEntry] = &[
    ("caves_world_size", "world_size", "default"),
    ("caves_branching", "branching", "default"),
    ("caves_loop", "loop", "default"),
    ("caves_atriumgate", "atriumgate", "default"),
    ("caves_wormattacks", "wormattacks", "default"),
    ("caves_earthquakes", "earthquakes", "default"),
    ("caves_weather", "weather", "default"),
    ("caves_regrowth", "regrowth", "default"),
    (
        "caves_flower_cave_regrowth",
        "flower_cave_regrowth",
        "default",
    ),
    (
        "caves_lightflier_flower_regrowth",
        "lightflier_flower_regrowth",
        "default",
    ),
    (
        "caves_mushtree_moon_regrowth",
        "mushtree_moon_regrowth",
        "default",
    ),
    ("caves_mushtree_regrowth", "mushtree_regrowth", "default"),
    ("caves_banana", "banana", "default"),
    ("caves_cave_ponds", "cave_ponds", "default"),
    ("caves_fern", "fern", "default"),
    ("caves_flint", "flint", "default"),
    ("caves_grass", "grass", "default"),
    ("caves_lichen", "lichen", "default"),
    ("caves_marshbush", "marshbush", "default"),
    ("caves_mushroom", "mushroom", "default"),
    ("caves_wormlights", "wormlights", "default"),
    ("caves_flower_cave", "flower_cave", "default"),
    ("caves_mushtree", "mushtree", "default"),
    ("caves_rock", "rock", "default"),
    ("caves_reeds", "reeds", "default"),
    ("caves_sapling", "sapling", "default"),
    ("caves_trees", "trees", "default"),
    ("caves_bunnymen", "bunnymen", "default"),
    ("caves_rocky", "rocky", "default"),
    ("caves_slurper", "slurper", "default"),
    ("caves_slurtles", "slurtles", "default"),
    ("caves_snurtles", "snurtles", "default"),
    ("caves_monkey", "monkey", "default"),
    ("caves_bats", "bats", "default"),
    ("caves_worms", "worms", "default"),
    ("caves_spiders", "spiders", "default"),
    ("caves_cave_spiders", "cave_spiders", "default"),
    ("caves_tentacles", "tentacles", "default"),
    ("caves_chess", "chess", "default"),
    ("caves_lightfliers", "lightfliers", "default"),
    ("caves_bunnymen_setting", "bunnymen_setting", "default"),
    ("caves_dustmoths", "dustmoths", "default"),
    ("caves_grassgekkos", "grassgekkos", "default"),
    ("caves_moles_setting", "moles_setting", "default"),
    ("caves_mushgnome", "mushgnome", "default"),
    ("caves_pigs_setting", "pigs_setting", "default"),
    ("caves_rocky_setting", "rocky_setting", "default"),
    ("caves_slurtles_setting", "slurtles_setting", "default"),
    ("caves_monkey_setting", "monkey_setting", "default"),
    ("caves_bats_setting", "bats_setting", "default"),
    ("caves_spider_hider", "spider_hider", "default"),
    ("caves_merms", "merms", "default"),
    ("caves_spider_warriors", "spider_warriors", "default"),
    ("caves_spiders_setting", "spiders_setting", "default"),
    ("caves_molebats", "molebats", "default"),
    ("caves_nightmarecreatures", "nightmarecreatures", "default"),
    ("caves_spider_dropper", "spider_dropper", "default"),
    ("caves_spider_spitter", "spider_spitter", "default"),
    ("caves_fruitfly", "fruitfly", "default"),
    ("caves_spiderqueen", "spiderqueen", "default"),
    ("caves_toadstool", "toadstool", "default"),
    ("caves_liefs", "liefs", "default"),
    ("caves_fissure", "fissure", "default"),
    ("caves_boons", "boons", "default"),
    ("caves_cavelight", "cavelight", "default"),
    ("caves_prefabswaps_start", "prefabswaps_start", "default"),
    ("caves_start_location", "start_location", "caves"),
    ("caves_task_set", "task_set", "cave_default"),
    ("caves_touchstone", "touchstone", "default"),
    ("caves_berrybush", "berrybush", "default"),
    ("caves_tree_rock", "tree_rock", "default"),
    ("caves_daywalker", "daywalker", "default"),
    ("caves_moon_spider", "moon_spider", "default"),
    ("caves_mutated_birds", "mutated_birds", "default"),
    ("caves_mutated_merm", "mutated_merm", "default"),
    (
        "caves_mutated_spiderqueen",
        "mutated_spiderqueen",
        "default",
    ),
    ("caves_acidrain_enabled", "acidrain_enabled", "always"),
    ("caves_rifts_enabled", "rifts_enabled_cave", "default"),
    ("caves_rifts_frequency", "rifts_frequency_cave", "default"),
    ("caves_wormattacks_boss", "wormattacks_boss", "default"),
    ("caves_chest_mimics", "chest_mimics", "default"),
    ("caves_itemmimics", "itemmimics", "default"),
    ("caves_evergreen_regrowth", "evergreen_regrowth", "default"),
    ("caves_reeds_regrowth", "reeds_regrowth", "default"),
    ("caves_tree_rock_regrowth", "tree_rock_regrowth", "default"),
    (
        "caves_twiggytrees_regrowth",
        "twiggytrees_regrowth",
        "default",
    ),
];

pub(super) fn dst_shard_override_entries(shard: &str) -> &'static [DstOverrideEntry] {
    if shard == "master" {
        DST_MASTER_OVERRIDE_ENTRIES
    } else {
        DST_CAVES_OVERRIDE_ENTRIES
    }
}
