use super::*;

#[rustfmt::skip]
pub(crate) const ARK_ASA_GUS_SERVER_SETTINGS: &[ArkIniSetting] = &[
    ("ActiveMapMod", "active_map_mod", false, false, false),
    ("AdminLogging", "admin_logging", false, false, false),
    ("AllowAnyoneBabyImprintCuddle", "allow_anyone_baby_imprint_cuddle", false, false, false),
    ("AllowCaveBuildingPvE", "allow_cave_building_pve", false, false, false),
    ("AllowCaveBuildingPvP", "allow_cave_building_pv_p", false, false, false),
    ("AllowCryoFridgeOnSaddle", "allow_cryo_fridge_on_saddle", false, false, false),
    ("AllowFlyerCarryPvE", "allow_flyer_carry_pve", false, false, false),
    ("AllowHideDamageSourceFromLogs", "allow_hide_damage_source_from_logs", false, false, false),
    ("AllowHitMarkers", "allow_hit_markers", false, false, false),
    ("AllowMultipleAttachedC4", "allow_multiple_attached_c4", false, false, false),
    ("AllowRaidDinoFeeding", "allow_raid_dino_feeding", false, false, false),
    ("AllowThirdPersonPlayer", "allow_third_person_player", false, false, false),
    ("AlwaysAllowStructurePickup", "always_allow_structure_pickup", false, false, false),
    ("ArmadoggoDeathCooldown", "armadoggo_death_cooldown", false, false, false),
    ("AutoSavePeriodMinutes", "auto_save_period_minutes", false, false, false),
    ("BanListURL", "ban_list_url", false, false, true),
    ("ClampItemSpoilingTimes", "clamp_item_spoiling_times", false, false, false),
    ("ClampResourceHarvestDamage", "clamp_resource_harvest_damage", false, false, false),
    ("CosmeticWhitelistOverride", "cosmetic_whitelist_override", false, false, false),
    ("CosmoWeaponAmmoReloadAmount", "cosmo_weapon_ammo_reload_amount", false, false, false),
    ("CustomLiveTuningUrl", "custom_live_tuning_url", false, false, true),
    ("DayCycleSpeedScale", "day_cycle_speed_scale", false, false, false),
    ("DayTimeSpeedScale", "day_time_speed_scale", false, false, false),
    ("DestroyTamesOverTheSoftTameLimit", "destroy_tames_over_soft_tame_limit", false, false, false),
    ("DifficultyOffset", "difficulty_offset", false, false, false),
    ("DinoCharacterFoodDrainMultiplier", "dino_character_food_drain_multiplier", false, false, false),
    ("DinoCharacterHealthRecoveryMultiplier", "dino_character_health_recovery_multiplier", false, false, false),
    ("DinoCharacterStaminaDrainMultiplier", "dino_character_stamina_drain_multiplier", false, false, false),
    ("DinoDamageMultiplier", "dino_damage_multiplier", false, false, false),
    ("DinoResistanceMultiplier", "dino_resistance_multiplier", false, false, false),
    ("DisableBurrowDecayTimers", "disable_burrow_decay_timers", false, false, false),
    ("DisableCryopodEnemyCheck", "disable_cryopod_enemy_check", false, false, false),
    ("DisableCryopodFridgeRequirement", "disable_cryopod_fridge_requirement", false, false, false),
    ("DisableDinoDecayPvE", "disable_dino_decay_pve", false, false, false),
    ("DisableImprintDinoBuff", "disable_imprint_dino_buff", false, false, false),
    ("DisablePvEGamma", "disable_pve_gamma", false, false, false),
    ("DisableStructureDecayPvE", "disable_structure_decay_pve", false, false, false),
    ("DisableWeatherFog", "disable_weather_fog", false, false, false),
    ("DontAlwaysNotifyPlayerJoined", "dont_always_notify_player_joined", false, false, false),
    ("EnableExtraStructurePreventionVolumes", "enable_extra_structure_prevention_volumes", false, false, false),
    ("EnablePvPGamma", "enable_pvp_gamma", false, false, false),
    ("ForceAllStructureLocking", "force_all_structure_locking", false, false, false),
    ("ForceGachaUnhappyInCaves", "force_gacha_unhappy_in_caves", false, false, false),
    ("globalVoiceChat", "global_voice_chat", false, false, false),
    ("HarvestAmountMultiplier", "harvest_amount_multiplier", false, false, false),
    ("HarvestHealthMultiplier", "harvest_health_multiplier", false, false, false),
    ("IgnoreLimitMaxStructuresInRangeTypeFlag", "ignore_limit_max_structures_in_range_type_flag", false, false, false),
    ("IgnorePVPMountedWeaponryRestrictions", "ignore_pvpmounted_weaponry_restrictions", false, false, false),
    ("ImplantSuicideCD", "implant_suicide_cd", false, false, false),
    ("ItemStackSizeMultiplier", "item_stack_size_multiplier", false, false, false),
    ("KickIdlePlayersPeriod", "kick_idle_players_period", false, false, false),
    ("MaxCosmoWeaponAmmo", "max_cosmo_weapon_ammo", false, false, false),
    ("MaxPersonalTamedDinos", "max_personal_tamed_dinos", false, false, false),
    ("MaxTamedDinos", "max_tamed_dinos", false, false, false),
    ("MaxTamedDinos_SoftTameLimit", "max_tamed_dinos_soft_tame_limit", false, false, false),
    ("MaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration", "max_tamed_dinos_soft_tame_limit_countdown_for_deletion_duration", false, false, false),
    ("MaxTrainCars", "max_train_cars", false, false, false),
    ("MaxTributeDinos", "max_tribute_dinos", false, false, false),
    ("MaxTributeItems", "max_tribute_items", false, false, false),
    ("NightTimeSpeedScale", "night_time_speed_scale", false, false, false),
    ("NonPermanentDiseases", "non_permanent_diseases", false, false, false),
    ("OverrideOfficialDifficulty", "override_official_difficulty", false, false, false),
    ("OverrideStructurePlatformPrevention", "override_structure_platform_prevention", false, false, false),
    ("OxygenSwimSpeedStatMultiplier", "oxygen_swim_speed_stat_multiplier", false, false, false),
    ("PerPlatformMaxStructuresMultiplier", "per_platform_max_structures_multiplier", false, false, false),
    ("PlatformSaddleBuildAreaBoundsMultiplier", "platform_saddle_build_area_bounds_multiplier", false, false, false),
    ("PlayerCharacterFoodDrainMultiplier", "player_character_food_drain_multiplier", false, false, false),
    ("PlayerCharacterHealthRecoveryMultiplier", "player_character_health_recovery_multiplier", false, false, false),
    ("PlayerCharacterStaminaDrainMultiplier", "player_character_stamina_drain_multiplier", false, false, false),
    ("PlayerCharacterWaterDrainMultiplier", "player_character_water_drain_multiplier", false, false, false),
    ("PlayerDamageMultiplier", "player_damage_multiplier", false, false, false),
    ("PlayerResistanceMultiplier", "player_resistance_multiplier", false, false, false),
    ("PreventDiseases", "prevent_diseases", false, false, false),
    ("PreventMateBoost", "prevent_mate_boost", false, false, false),
    ("PreventOfflinePvP", "prevent_offline_pvp", false, false, false),
    ("PreventOfflinePvPInterval", "prevent_offline_pvp_interval", false, false, false),
    ("PreventSpawnAnimations", "prevent_spawn_animations", false, false, false),
    ("PreventTribeAlliances", "prevent_tribe_alliances", false, false, false),
    ("ProximityChat", "proximity_chat", false, false, false),
    ("PvEAllowStructuresAtSupplyDrops", "pve_allow_structures_at_supply_drops", false, false, false),
    ("PvEDinoDecayPeriodMultiplier", "pve_dino_decay_period_multiplier", false, false, false),
    ("PvPDinoDecay", "pv_pdino_decay", false, false, false),
    ("RaidDinoCharacterFoodDrainMultiplier", "raid_dino_character_food_drain_multiplier", false, false, false),
    ("RandomSupplyCratePoints", "random_supply_crate_points", false, false, false),
    ("RCONServerGameLogBuffer", "rconserver_game_log_buffer", false, false, false),
    ("ResourcesRespawnPeriodMultiplier", "resources_respawn_period_multiplier", false, false, false),
    ("ServerAdminPassword", "admin_password", false, false, false),
    ("ServerCrosshair", "server_crosshair", false, false, false),
    ("ServerForceNoHUD", "server_force_no_hud", false, false, false),
    ("ServerHardcore", "server_hardcore", false, false, false),
    ("ServerPassword", "server_password", false, false, false),
    ("serverPVE", "server_pve", false, false, false),
    ("ShowFloatingDamageText", "show_floating_damage_text", false, false, false),
    ("ShowMapPlayerLocation", "show_map_player_location", false, false, false),
    ("StructurePickupHoldDuration", "structure_pickup_hold_duration", false, false, false),
    ("StructurePickupTimeAfterPlacement", "structure_pickup_time_after_placement", false, false, false),
    ("StructurePreventResourceRadiusMultiplier", "structure_prevent_resource_radius_multiplier", false, false, false),
    ("StructureResistanceMultiplier", "structure_resistance_multiplier", false, false, false),
    ("TamingSpeedMultiplier", "taming_speed_multiplier", false, false, false),
    ("TheMaxStructuresInRange", "the_max_structures_in_range", false, false, false),
    ("TribeNameChangeCooldown", "tribe_name_change_cooldown", false, false, false),
    ("XPMultiplier", "xp_multiplier", false, false, false),
    ("YoungIceFoxDeathCooldown", "young_ice_fox_death_cooldown", false, false, false),
    ("CrossARKAllowForeignDinoDownloads", "cross_arkallow_foreign_dino_downloads", false, false, false),
    ("noTributeDownloads", "no_tribute_downloads", false, false, false),
    ("PreventDownloadDinos", "prevent_download_dinos", false, false, false),
    ("PreventDownloadItems", "prevent_download_items", false, false, false),
    ("PreventDownloadSurvivors", "prevent_download_survivors", false, false, false),
    ("PreventUploadDinos", "prevent_upload_dinos", false, false, false),
    ("PreventUploadItems", "prevent_upload_items", false, false, false),
    ("PreventUploadSurvivors", "prevent_upload_survivors", false, false, false),
    ("BadWordListURL", "bad_word_list_url", false, false, false),
    ("BadWordWhiteListURL", "bad_word_whitelist_url", false, false, false),
    ("LimitBunkersPerTribe", "limit_bunkers_per_tribe", false, false, false),
    ("LimitBunkersPerTribeNum", "limit_bunkers_per_tribe_num", false, false, false),
    ("AllowBunkersInPreventionZones", "allow_bunkers_in_prevention_zones", false, false, false),
    ("AllowRidingDinosInsideBunkers", "allow_riding_dinos_inside_bunkers", false, false, false),
    ("AllowBunkerModulesAboveGround", "allow_bunker_modules_above_ground", false, false, false),
    ("AllowDinoAIInsideBunkers", "allow_dino_aiinside_bunkers", false, false, false),
    ("AllowBunkerModulesInPreventionZones", "allow_bunker_modules_in_prevention_zones", false, false, false),
    ("MinDistanceBetweenBunkers", "min_distance_between_bunkers", false, false, false),
    ("EnemyAccessBunkerHPThreshold", "enemy_access_bunker_hpthreshold", false, false, false),
    ("BunkerUnderHPThresholdDmgMultiplier", "bunker_under_hpthreshold_dmg_multiplier", false, false, false),
    ("CryoHospitalHoursToRegenHP", "cryo_hospital_hours_to_regen_hp", false, false, false),
    ("CryoHospitalHoursToRegenFood", "cryo_hospital_hours_to_regen_food", false, false, false),
    ("CryoHospitalHoursToDrainTorpor", "cryo_hospital_hours_to_drain_torpor", false, false, false),
    ("CryoHospitalMatingCooldownReduction", "cryo_hospital_mating_cooldown_reduction", false, false, false),
    ("BloodforgeReinforceExtraDurability", "bloodforge_reinforce_extra_durability", false, false, false),
    ("BloodforgeReinforceResourceCostMultiplier", "bloodforge_reinforce_resource_cost_multiplier", false, false, false),
    ("BloodforgeReinforceSpeedMultiplier", "bloodforge_reinforce_speed_multiplier", false, false, false),
    ("MaxActiveOutposts", "max_active_outposts", false, false, false),
    ("MaxActiveResourceCaches", "max_active_resource_caches", false, false, false),
    ("MaxActiveCityOutposts", "max_active_city_outposts", false, false, false),
    ("OutpostSigilRewardMultiplier", "outpost_sigil_reward_multiplier", false, false, false),
    ("AdminListURL", "admin_list_url", false, false, false),
    ("AutoRestartIntervalSeconds", "auto_restart_interval_seconds", false, false, false),
    ("UpdateAllowedCheatersInterval", "update_allowed_cheaters_interval", false, false, false),
    ("UseCharacterTracker", "use_character_tracker", false, false, false),
];

#[rustfmt::skip]
pub(crate) const ARK_ASA_GUS_SESSION_SETTINGS: &[ArkIniSetting] = &[
    ("SessionName", "server_name", false, false, false),
];

#[rustfmt::skip]
pub(crate) const ARK_ASA_GUS_MOTD: &[ArkIniSetting] = &[
    ("Duration", "duration", false, false, false),
    ("Message", "message", false, false, false),
];

#[rustfmt::skip]
pub(crate) const ARK_ASA_GAME_INI: &[ArkIniSetting] = &[
    ("BabyCuddleGracePeriodMultiplier", "baby_cuddle_grace_period_multiplier", false, false, false),
    ("BabyCuddleIntervalMultiplier", "baby_cuddle_interval_multiplier", false, false, false),
    ("BabyCuddleLoseImprintQualitySpeedMultiplier", "baby_cuddle_lose_imprint_quality_speed_multiplier", false, false, false),
    ("BabyFoodConsumptionSpeedMultiplier", "baby_food_consumption_speed_multiplier", false, false, false),
    ("BabyImprintAmountMultiplier", "baby_imprint_amount_multiplier", false, false, false),
    ("BabyImprintingStatScaleMultiplier", "baby_imprinting_stat_scale_multiplier", false, false, false),
    ("BabyMatureSpeedMultiplier", "baby_mature_speed_multiplier", false, false, false),
    ("bAllowFlyerSpeedLeveling", "b_allow_flyer_speed_leveling", false, false, false),
    ("bAllowSpeedLeveling", "b_allow_speed_leveling", false, false, false),
    ("bAllowUnlimitedRespecs", "b_allow_unlimited_respecs", false, false, false),
    ("bDisableFriendlyFire", "b_disable_friendly_fire", false, false, false),
    ("bDisablePhotoMode", "b_disable_photo_mode", false, false, false),
    ("bDisableStructurePlacementCollision", "disable_structure_placement_collision", false, false, false),
    ("bDisableWirelessCrafting", "b_disable_wireless_crafting", false, false, false),
    ("bDisableWirelessCraftingForDinos", "b_disable_wireless_crafting_for_dinos", false, false, false),
    ("bDisableWirelessCraftingForPlayers", "b_disable_wireless_crafting_for_players", false, false, false),
    ("bDisableWirelessCraftingForStructures", "b_disable_wireless_crafting_for_structures", false, false, false),
    ("bIgnoreStructuresPreventionVolumes", "b_ignore_structures_prevention_volumes", false, false, false),
    ("bPvEDisableFriendlyFire", "b_pv_edisable_friendly_fire", false, false, false),
    ("bShowCreativeMode", "show_creative_mode", false, false, false),
    ("bUseDinoLevelUpAnimations", "use_dino_level_up_animations", false, false, false),
    ("bUseSingleplayerSettings", "use_singleplayer_settings", false, false, false),
    ("CheatTeleportLocations", "cheat_teleport_locations", true, false, false),
    ("ConfigAddNPCSpawnEntriesContainer", "config_add_npc_spawn_entries_container", true, false, false),
    ("CraftingSkillBonusMultiplier", "crafting_skill_bonus_multiplier", false, false, false),
    ("CraftXPMultiplier", "craft_xpmultiplier", false, false, false),
    ("CropDecaySpeedMultiplier", "crop_decay_speed_multiplier", false, false, false),
    ("CropGrowthSpeedMultiplier", "crop_growth_speed_multiplier", false, false, false),
    ("CustomRecipeEffectivenessMultiplier", "custom_recipe_effectiveness_multiplier", false, false, false),
    ("CustomRecipeSkillMultiplier", "custom_recipe_skill_multiplier", false, false, false),
    ("DestroyTamesOverLevelClamp", "destroy_tames_over_level_clamp", false, false, false),
    ("EggHatchSpeedMultiplier", "egg_hatch_speed_multiplier", false, false, false),
    ("ExcludeItemIndices", "exclude_item_indices", true, false, false),
    ("LimitGeneratorsNum", "limit_generators_num", false, false, false),
    ("LimitGeneratorsRange", "limit_generators_range", false, false, false),
    ("GenericXPMultiplier", "generic_xpmultiplier", false, false, false),
    ("GlobalItemDecompositionTimeMultiplier", "global_item_decomposition_time_multiplier", false, false, false),
    ("GlobalSpoilingTimeMultiplier", "global_spoiling_time_multiplier", false, false, false),
    ("HairGrowthSpeedMultiplier", "hair_growth_speed_multiplier", false, false, false),
    ("HarvestResourceItemAmountClassMultipliers", "harvest_resource_item_amount_class_multipliers", true, false, false),
    ("HarvestXPMultiplier", "harvest_xpmultiplier", false, false, false),
    ("KillXPMultiplier", "kill_xpmultiplier", false, false, false),
    ("LayEggIntervalMultiplier", "lay_egg_interval_multiplier", false, false, false),
    ("LevelExperienceRampOverrides", "level_experience_ramp_overrides", true, false, false),
    ("MatingIntervalMultiplier", "mating_interval_multiplier", false, false, false),
    ("MatingSpeedMultiplier", "mating_speed_multiplier", false, false, false),
    ("MaxFallSpeedMultiplier", "max_fall_speed_multiplier", false, false, false),
    ("OverrideNamedEngramEntries", "override_named_engram_entries", true, false, false),
    ("PerLevelStatsMultiplier_Player", "per_level_stats_multiplier_player_integer", true, true, false),
    ("PhotoModeRangeLimit", "photo_mode_range_limit", false, false, false),
    ("PoopIntervalMultiplier", "poop_interval_multiplier", false, false, false),
    ("PreventBreedingForClassNames", "prevent_breeding_for_class_names", true, false, false),
    ("ResourceNoReplenishRadiusPlayers", "resource_no_replenish_radius_players", false, false, false),
    ("ResourceNoReplenishRadiusStructures", "resource_no_replenish_radius_structures", false, false, false),
    ("SpecialXPMultiplier", "special_xpmultiplier", false, false, false),
    ("TribeTowerBonusMultiplier", "tribe_tower_bonus_multiplier", false, false, false),
    ("WildDinoCharacterFoodDrainMultiplier", "wild_dino_character_food_drain_multiplier", false, false, false),
    ("WirelessCraftingRangeOverride", "wireless_crafting_range_override", false, false, false),
    ("ValgueroMemorialEntries", "valguero_memorial_entries", false, false, false),
    ("BaseHexagonRewardMultiplier", "base_hexagon_reward_multiplier", false, false, false),
    ("HexagonCostMultiplier", "hexagon_cost_multiplier", false, false, false),
];

#[rustfmt::skip]
pub(crate) const ARK_ASA_PATCH_GUS_SERVER_SETTINGS: &[ArkIniSetting] = &[
    ("AnchoredVesselCheckRadius", "anchored_vessel_check_radius", false, false, false),
    ("MaxAnchoredVesselsInRange", "max_anchored_vessels_in_range", false, false, false),
    ("NeedsPowerToActivateAquaticCompartments", "needs_power_to_activate_aquatic_compartments", false, false, false),
    ("PreventTemplateOnSaddle", "prevent_template_on_saddle", false, false, false),
    ("UseAstraeosTraversalBuff", "use_astraeos_traversal_buff", false, false, false),
];

#[rustfmt::skip]
pub(crate) const ARK_ASA_ADVANCED_GAME_INI: &[ArkIniSetting] = &[
    ("SupplyCrateLootQualityMultiplier", "supply_crate_loot_quality_multiplier", false, false, false),
    ("OverrideMaxExperiencePointsPlayer", "override_max_experience_points_player", false, false, false),
    ("OverrideMaxExperiencePointsDino", "override_max_experience_points_dino", false, false, false),
    ("bAutoUnlockAllEngrams", "auto_unlock_all_engrams", false, false, false),
    ("ConfigOverrideSupplyCrateItems", "config_override_supply_crate_items", true, false, false),
    ("ConfigOverrideItemCraftingCosts", "config_override_item_crafting_costs", true, false, false),
    ("ConfigOverrideItemMaxQuantity", "config_override_item_max_quantity", true, false, false),
    ("ConfigOverrideNPCSpawnEntriesContainer", "config_override_npc_spawn_entries_container", true, false, false),
    ("ConfigSubtractNPCSpawnEntriesContainer", "config_subtract_npc_spawn_entries_container", true, false, false),
    ("DinoSpawnWeightMultipliers", "dino_spawn_weight_multipliers", true, false, false),
    ("NPCReplacements", "npc_replacements", true, false, false),
    ("OverridePlayerLevelEngramPoints", "override_player_level_engram_points", true, false, false),
    ("EngramEntryAutoUnlocks", "engram_entry_auto_unlocks", true, false, false),
    ("PerLevelStatsMultiplier_DinoTamed", "per_level_stats_multiplier_dino_tamed_type_integer", true, true, false),
    ("PerLevelStatsMultiplier_DinoWild", "per_level_stats_multiplier_dino_wild_integer", true, true, false),
];
