use super::super::*;

pub(super) fn ark_ascended_test_descriptor(root: &Path) -> ModuleDescriptor {
    ModuleDescriptor {
        root: root.join("modules").join("arksurvivalascended"),
        manifest_toml: String::from(
            "id = \"arksurvivalascended\"\nname = \"ARK: Survival Ascended\"\nversion = \"0.1.0\"\nsupported_platforms = [\"windows\"]\n\n[storage]\nsaves_path_template = \"{{paths.install_root}}/ShooterGame/Saved/{{instance.id}}\"\n",
        ),
        schema_json: Some(
            r#"{
                    "type": "object",
                    "properties": {
                        "server_name": { "type": "string", "default": "ASA Server", "x-lsgm-default-source": "instance_name" },
                        "map_name": { "type": "string", "default": "TheIsland_WP" },
                        "max_players": { "type": "integer", "default": 30 },
                        "admin_password": { "type": "string", "default": "asa-admin" },
                        "server_password": { "type": "string", "default": "" },
                        "rcon_enabled": { "type": "boolean", "default": true },
                        "battleye_enabled": { "type": "boolean", "default": true },
                        "auto_save_period_minutes": { "type": "number", "default": 20.0 },
                        "ban_list_url": { "type": "string", "default": "https://example.com/asa-banlist.txt" },
                        "show_floating_damage_text": { "type": "boolean", "default": true },
                        "server_hardcore": { "type": "boolean", "default": true },
                        "server_force_no_hud": { "type": "boolean", "default": false },
                        "spectator_password": { "type": "string", "default": "fixture-observer-mode" },
                        "kick_idle_players_period": { "type": "number", "default": 2700.0 },
                        "enable_idle_player_kick": { "type": "boolean", "default": true },
                        "structure_pickup_time_after_placement": { "type": "number", "default": 45.0 },
                        "structure_pickup_hold_duration": { "type": "number", "default": 0.75 },
                        "the_max_structures_in_range": { "type": "integer", "default": 9500 },
                        "enable_auto_destroy_structures": { "type": "boolean", "default": true },
                        "auto_destroy_old_structures_multiplier": { "type": "number", "default": 0.5 },
                        "only_auto_destroy_core_structures": { "type": "boolean", "default": true },
                        "limit_turrets_in_range": { "type": "boolean", "default": true },
                        "hard_limit_turrets_in_range": { "type": "boolean", "default": true },
                        "limit_turrets_num": { "type": "integer", "default": 80 },
                        "limit_turrets_range": { "type": "number", "default": 9000.0 },
                        "destroy_tames_over_soft_tame_limit": { "type": "boolean", "default": true },
                        "max_tamed_dinos_soft_tame_limit": { "type": "integer", "default": 4500 },
                        "max_tamed_dinos_soft_tame_limit_countdown_for_deletion_duration": { "type": "integer", "default": 259200 },
                        "no_transfer_from_filtering": { "type": "boolean", "default": true },
                        "cluster_id": { "type": "string", "default": "alpha-cluster" },
                        "no_tribute_downloads": { "type": "boolean", "default": true },
                        "prevent_download_survivors": { "type": "boolean", "default": true },
                        "prevent_download_items": { "type": "boolean", "default": false },
                        "prevent_download_dinos": { "type": "boolean", "default": true },
                        "prevent_upload_survivors": { "type": "boolean", "default": false },
                        "prevent_upload_items": { "type": "boolean", "default": true },
                        "prevent_upload_dinos": { "type": "boolean", "default": true },
                        "minimum_dino_reupload_interval": { "type": "number", "default": 900.0 },
                        "max_tribute_characters": { "type": "integer", "default": 15 },
                        "max_tribute_dinos": { "type": "integer", "default": 40 },
                        "max_tribute_items": { "type": "integer", "default": 100 },
                        "tribute_character_expiration_seconds": { "type": "integer", "default": 172800 },
                        "tribute_dino_expiration_seconds": { "type": "integer", "default": 259200 },
                        "tribute_item_expiration_seconds": { "type": "integer", "default": 432000 },
                        "prevent_transfer_for_class_names": { "type": "string", "default": "PrimalItem_WeaponTekSword_C\nPrimalDinoCharacter_BP_Rex_C" },
                        "mod_ids_csv": { "type": "string", "default": "900001,900002" },
                        "server_game_log": { "type": "boolean", "default": true },
                        "server_game_log_include_tribe_logs": { "type": "boolean", "default": true },
                        "tribe_log_destroyed_enemy_structures": { "type": "boolean", "default": true },
                        "allow_hide_damage_source_from_logs": { "type": "boolean", "default": false },
                        "notify_admin_commands_in_chat": { "type": "boolean", "default": true },
                        "exclusive_join_enabled": { "type": "boolean", "default": true },
                        "exclusive_join_list": { "type": "string", "default": "1111\n2222" },
                        "priority_join_list": { "type": "string", "default": "3333" },
                        "admin_account_ids": { "type": "string", "default": "9999" },
                        "filter_chat": { "type": "boolean", "default": true },
                        "filter_character_names": { "type": "boolean", "default": true },
                        "filter_tribe_names": { "type": "boolean", "default": true },
                        "bad_word_list_url": { "type": "string", "default": "http://arkdedicated.com/badwords.txt" },
                        "bad_word_whitelist_url": { "type": "string", "default": "" },
                        "active_event": { "type": "string", "default": "Birthday" },
                        "allow_flying_stamina_recovery": { "type": "boolean", "default": true },
                        "allow_multiple_attached_c4": { "type": "boolean", "default": true },
                        "allow_raid_dino_feeding": { "type": "boolean", "default": true },
                        "allow_hit_markers": { "type": "boolean", "default": true },
                        "disable_weather_fog": { "type": "boolean", "default": true },
                        "enable_pvp_gamma": { "type": "boolean", "default": true },
                        "disable_pve_gamma": { "type": "boolean", "default": false },
                        "allow_cave_building_pve": { "type": "boolean", "default": true },
                        "disable_structure_decay_pve": { "type": "boolean", "default": true },
                        "prevent_offline_pvp": { "type": "boolean", "default": true },
                        "prevent_offline_pvp_interval": { "type": "number", "default": 900.0 },
                        "override_structure_platform_prevention": { "type": "boolean", "default": true },
                        "enable_extra_structure_prevention_volumes": { "type": "boolean", "default": true },
                        "pve_allow_structures_at_supply_drops": { "type": "boolean", "default": false },
                        "allow_crate_spawns_on_top_of_structures": { "type": "boolean", "default": true },
                        "force_all_structure_locking": { "type": "boolean", "default": true },
                        "disable_dino_decay_pve": { "type": "boolean", "default": true },
                        "auto_destroy_decayed_dinos": { "type": "boolean", "default": true },
                        "pve_structure_decay_period_multiplier": { "type": "number", "default": 1.5 },
                        "pve_dino_decay_period_multiplier": { "type": "number", "default": 2.0 },
                        "allow_integrated_splus_structures": { "type": "boolean", "default": true },
                        "disable_structure_placement_collision": { "type": "boolean", "default": true },
                        "resource_no_replenish_radius_players": { "type": "number", "default": 0.5 },
                        "resource_no_replenish_radius_structures": { "type": "number", "default": 0.5 },
                        "crop_growth_speed_multiplier": { "type": "number", "default": 2.0 },
                        "crop_decay_speed_multiplier": { "type": "number", "default": 0.5 },
                        "poop_interval_multiplier": { "type": "number", "default": 0.75 },
                        "player_character_health_recovery_multiplier": { "type": "number", "default": 1.4 },
                        "player_character_stamina_drain_multiplier": { "type": "number", "default": 0.85 },
                        "resources_respawn_period_multiplier": { "type": "number", "default": 1.25 },
                        "item_stack_size_multiplier": { "type": "number", "default": 3.0 },
                        "dino_count_multiplier": { "type": "number", "default": 1.35 },
                        "server_auto_force_respawn_wild_dinos_interval": { "type": "number", "default": 604800.0 },
                        "prevent_diseases": { "type": "boolean", "default": true },
                        "force_can_ride_fliers": { "type": "boolean", "default": true },
                        "allow_flyer_speed_leveling": { "type": "boolean", "default": true },
                        "use_singleplayer_settings": { "type": "boolean", "default": true },
                        "show_creative_mode": { "type": "boolean", "default": true },
                        "use_dino_level_up_animations": { "type": "boolean", "default": false },
                        "prevent_mate_boost": { "type": "boolean", "default": true },
                        "player_damage_multiplier": { "type": "number", "default": 1.2 },
                        "player_resistance_multiplier": { "type": "number", "default": 0.85 },
                        "dino_damage_multiplier": { "type": "number", "default": 1.15 },
                        "dino_resistance_multiplier": { "type": "number", "default": 0.9 },
                        "tamed_dino_damage_multiplier": { "type": "number", "default": 1.3 },
                        "tamed_dino_resistance_multiplier": { "type": "number", "default": 0.8 },
                        "structure_damage_multiplier": { "type": "number", "default": 1.1 },
                        "structure_resistance_multiplier": { "type": "number", "default": 0.75 },
                        "dino_class_damage_multipliers": { "type": "string", "default": "(ClassName=\"MegaRex_Character_BP_C\",Multiplier=0.7)\nDinoClassDamageMultipliers=(ClassName=\"AlphaRaptor_Character_BP_C\",Multiplier=1.4)" },
                        "dino_class_resistance_multipliers": { "type": "string", "default": "(ClassName=\"Giga_Character_BP_C\",Multiplier=1.25)" },
                        "tamed_dino_class_damage_multipliers": { "type": "string", "default": "(ClassName=\"Rex_Character_BP_C\",Multiplier=1.6)" },
                        "tamed_dino_class_resistance_multipliers": { "type": "string", "default": "(ClassName=\"Stego_Character_BP_C\",Multiplier=0.85)" },
                        "use_dynamic_config": { "type": "boolean", "default": true },
                        "custom_dynamic_config_url": { "type": "string", "default": "http://cdn.example.com/asa-dynamic.ini" },
                        "custom_live_tuning_url": { "type": "string", "default": "https://cdn2.arkdedicated.com/asa/livetuningoverloads.json" },
                        "enable_cryopod_nerf": { "type": "boolean", "default": true },
                        "cryopod_nerf_duration": { "type": "number", "default": 600.0 },
                        "cryopod_nerf_damage_mult": { "type": "number", "default": 0.01 },
                        "cryopod_nerf_incoming_damage_mult_percent": { "type": "number", "default": 25.0 },
                        "enable_cryo_sickness_pve": { "type": "boolean", "default": true },
                        "disable_cryopod_enemy_check": { "type": "boolean", "default": true },
                        "disable_cryopod_fridge_requirement": { "type": "boolean", "default": false },
                        "allow_cryo_fridge_on_saddle": { "type": "boolean", "default": true },
                        "max_platform_saddle_structure_limit": { "type": "integer", "default": 100 },
                        "only_decay_unsnapped_core_structures": { "type": "boolean", "default": true },
                        "fast_decay_unsnapped_core_structures": { "type": "boolean", "default": true },
                        "player_level_health_multiplier": { "type": "number", "default": 1.5 },
                        "player_level_stamina_multiplier": { "type": "number", "default": 1.25 },
                        "player_level_oxygen_multiplier": { "type": "number", "default": 1.0 },
                        "player_level_food_multiplier": { "type": "number", "default": 1.0 },
                        "player_level_water_multiplier": { "type": "number", "default": 1.0 },
                        "player_level_weight_multiplier": { "type": "number", "default": 2.0 },
                        "player_level_melee_multiplier": { "type": "number", "default": 1.4 },
                        "player_level_speed_multiplier": { "type": "number", "default": 1.0 },
                        "player_level_fortitude_multiplier": { "type": "number", "default": 1.0 },
                        "player_level_crafting_multiplier": { "type": "number", "default": 1.25 },
                        "dino_wild_level_health_multiplier": { "type": "number", "default": 1.1 },
                        "dino_wild_level_stamina_multiplier": { "type": "number", "default": 1.0 },
                        "dino_wild_level_damage_multiplier": { "type": "number", "default": 1.2 },
                        "dino_tamed_level_health_multiplier": { "type": "number", "default": 1.35 },
                        "dino_tamed_level_stamina_multiplier": { "type": "number", "default": 1.1 },
                        "dino_tamed_level_food_multiplier": { "type": "number", "default": 1.0 },
                        "dino_tamed_level_weight_multiplier": { "type": "number", "default": 1.8 },
                        "dino_tamed_level_damage_multiplier": { "type": "number", "default": 1.4 },
                        "dino_tamed_level_speed_multiplier": { "type": "number", "default": 1.0 },
                        "mating_interval_multiplier": { "type": "number", "default": 0.5 },
                        "egg_hatch_speed_multiplier": { "type": "number", "default": 4.0 },
                        "baby_mature_speed_multiplier": { "type": "number", "default": 3.0 },
                        "baby_cuddle_interval_multiplier": { "type": "number", "default": 0.25 },
                        "lay_egg_interval_multiplier": { "type": "number", "default": 0.8 },
                        "mating_speed_multiplier": { "type": "number", "default": 1.5 },
                        "baby_food_consumption_speed_multiplier": { "type": "number", "default": 0.8 },
                        "baby_cuddle_grace_period_multiplier": { "type": "number", "default": 1.5 },
                        "baby_cuddle_lose_imprint_quality_speed_multiplier": { "type": "number", "default": 0.5 },
                        "baby_imprinting_stat_scale_multiplier": { "type": "number", "default": 1.2 },
                        "baby_imprint_amount_multiplier": { "type": "number", "default": 1.5 },
                        "allow_anyone_baby_imprint_cuddle": { "type": "boolean", "default": true },
                        "disable_imprint_dino_buff": { "type": "boolean", "default": false },
                        "auto_unlock_all_engrams": { "type": "boolean", "default": true },
                        "engram_entry_auto_unlocks": { "type": "string", "default": "(EngramClassName=\"EngramEntry_WoodWall_C\",LevelToAutoUnlock=10)\nEngramEntryAutoUnlocks=(EngramClassName=\"EngramEntry_StoneWall_C\",LevelToAutoUnlock=20)" },
                        "override_named_engram_entries": { "type": "string", "default": "(EngramClassName=\"EngramEntry_TekClaws_C\",EngramHidden=false,EngramPointsCost=0,EngramLevelRequirement=100,RemoveEngramPreReq=true)" },
                        "level_experience_ramp_overrides": { "type": "string", "default": "(ExperiencePointsForLevel[0]=5,ExperiencePointsForLevel[1]=15,ExperiencePointsForLevel[2]=30)" },
                        "override_player_level_engram_points": { "type": "string", "default": "8\nOverridePlayerLevelEngramPoints=12\n16" },
                        "npc_replacements": { "type": "string", "default": "(FromClassName=\"MegaRaptor_Character_BP_C\",ToClassName=\"Raptor_Character_BP_C\")" },
                        "dino_spawn_weight_multipliers": { "type": "string", "default": "(DinoNameTag=\"Raptor\",SpawnWeightMultiplier=1.5,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=0.25)" },
                        "config_add_npc_spawn_entries_container": { "type": "string", "default": "(NPCSpawnEntriesContainerClassString=\"DinoSpawnEntriesBeach_C\",NPCSpawnEntries=((AnEntryName=\"LanGameRaptor\",EntryWeight=0.2,NPCsToSpawnStrings=(\"Raptor_Character_BP_C\"))),NPCSpawnLimits=((NPCClassString=\"Raptor_Character_BP_C\",MaxPercentageOfDesiredNumToAllow=0.2)))" },
                        "config_subtract_npc_spawn_entries_container": { "type": "string", "default": "(NPCSpawnEntriesContainerClassString=\"DinoSpawnEntriesBeach_C\",NPCSpawnEntries=((AnEntryName=\"Dodo\",NPCsToSpawnStrings=(\"Dodo_Character_BP_C\"))))" },
                        "config_override_npc_spawn_entries_container": { "type": "string", "default": "(NPCSpawnEntriesContainerClassString=\"DinoSpawnEntriesBeach_C\",NPCSpawnEntries=((AnEntryName=\"LanGameCarno\",EntryWeight=0.1,NPCsToSpawnStrings=(\"Carno_Character_BP_C\"))),NPCSpawnLimits=((NPCClassString=\"Carno_Character_BP_C\",MaxPercentageOfDesiredNumToAllow=0.05)))" },
                        "disable_loot_crates": { "type": "boolean", "default": false },
                        "random_supply_crate_points": { "type": "boolean", "default": true },
                        "supply_crate_loot_quality_multiplier": { "type": "number", "default": 2.5 },
                        "fishing_loot_quality_multiplier": { "type": "number", "default": 1.75 },
                        "config_override_supply_crate_items": { "type": "string", "default": "(SupplyCrateClassString=\"SupplyCrate_Level15_C\",MinItemSets=1,MaxItemSets=1,NumItemSetsPower=1.0,bSetsRandomWithoutReplacement=true,ItemSets=((SetName=\"LanGameBlueDrop\",MinNumItems=1,MaxNumItems=1,NumItemsPower=1.0,SetWeight=1.0,bItemsRandomWithoutReplacement=true,ItemEntries=((EntryWeight=1.0,ItemClassStrings=(\"PrimalItemResource_MetalIngot_C\"),ItemsWeights=(1.0),MinQuantity=100.0,MaxQuantity=150.0,MinQuality=1.0,MaxQuality=1.0,bForceBlueprint=false,ChanceToBeBlueprintOverride=0.0)))))" },
                        "allow_custom_recipes": { "type": "boolean", "default": true },
                        "custom_recipe_effectiveness_multiplier": { "type": "number", "default": 1.8 },
                        "custom_recipe_skill_multiplier": { "type": "number", "default": 0.65 },
                        "config_override_item_crafting_costs": { "type": "string", "default": "(ItemClassString=\"PrimalItem_WeaponStoneHatchet_C\",BaseCraftingResourceRequirements=((ResourceItemTypeString=\"PrimalItemResource_Thatch_C\",BaseResourceRequirement=10.0,bCraftingRequireExactResourceType=false),(ResourceItemTypeString=\"PrimalItemResource_Wood_C\",BaseResourceRequirement=1.0,bCraftingRequireExactResourceType=false)))" },
                        "config_override_item_max_quantity": { "type": "string", "default": "(ItemClassString=\"PrimalItemResource_MetalIngot_C\",Quantity=(MaxItemQuantity=500,bIgnoreMultiplier=true))" }
                    }
                }"#
            .to_string(),
        ),
        default_ports: vec![
            PortBinding {
                name: String::from("game"),
                protocol: String::from("udp"),
                port: 7777,
            },
            PortBinding {
                name: String::from("peer"),
                protocol: String::from("udp"),
                port: 7778,
            },
            PortBinding {
                name: String::from("query"),
                protocol: String::from("udp"),
                port: 27015,
            },
            PortBinding {
                name: String::from("rcon"),
                protocol: String::from("tcp"),
                port: 27020,
            },
        ],
        install: Some(app_core::InstallSpec {
            shared_game_dir: String::from("arksurvivalascended"),
            download_url_windows: None,
            download_integrity_windows: None,
            source: None,
            verification_path: None,
            minecraft: None,
        }),
        process: Some(app_core::ProcessSpec {
            environment_template: Default::default(),
            executable: String::from("ShooterGame/Binaries/Win64/ArkAscendedServer.exe"),
            args_template: vec![
                String::from("{{arksa.server_url}}"),
                String::from("-port={{ports.game.port}}"),
                String::from("-WinLiveMaxPlayers={{settings.max_players}}"),
                String::from("-NullRHI"),
                String::from("-Unattended"),
                String::from("-NoSplash"),
                String::from("-abslog={{paths.logs_dir}}/ark-ascended-server.log"),
                String::from("{{arksa.multihome_flag}}"),
                String::from("{{arksa.cluster_dir_override_flag}}"),
                String::from("{{arksa.mod_ids_flag}}"),
                String::from("{{arksa.official_launch_flags}}"),
                String::from("{{arksa.custom_launch_flags}}"),
            ],
            working_directory_template: Some(String::from(
                "{{paths.install_root}}/ShooterGame/Binaries/Win64",
            )),
            window_policy: app_core::ProcessWindowPolicy::Background,
            host_surface: app_core::ProcessHostSurface::ManagedTerminal,
            host_notes: None,
        }),
        workshop: None,
        runtime: app_core::ModuleRuntimeSpec::default(),
        storage: app_modules::ModuleStorageSpec {
            saves_path_template: Some(String::from(
                "{{paths.install_root}}/ShooterGame/Saved/{{instance.id}}",
            )),
            ..Default::default()
        },
        summary: ModuleSummary {
            id: String::from("arksurvivalascended"),
            name: String::from("ARK: Survival Ascended Dedicated Server"),
            version: String::from("0.1.0"),
            description: Some(String::from("Test module")),
            steam_app_id: Some(2430930),
            install_state: InstallState::NotInstalled,
            instance_program_count: 0,
            archived_program_count: 0,
            supported_platforms: vec![String::from("windows")],
        },
    }
}

pub(super) fn prepare_ark_ascended_environment(root: &Path, descriptor: &ModuleDescriptor) {
    let paths = test_paths(root);
    prepare_shared_install(&paths, descriptor);
    fs::create_dir_all(paths.database_path.parent().unwrap()).unwrap();
    fs::create_dir_all(&paths.logs_root).unwrap();
    fs::create_dir_all(&paths.steamcmd_root).unwrap();
    fs::create_dir_all(&paths.games_root).unwrap();
    fs::create_dir_all(&paths.instances_root).unwrap();
    write_module_descriptor_files(descriptor);
    let templates_root = descriptor.root.join("templates");
    fs::create_dir_all(&templates_root).unwrap();
    fs::write(
        templates_root.join("GameUserSettings.ini.hbs"),
        "[ServerSettings]\nServerAdminPassword={{admin_password}}\nServerPassword={{server_password}}\nRCONEnabled={{rcon_enabled}}\nTribeLogDestroyedEnemyStructures={{tribe_log_destroyed_enemy_structures}}\nAllowHideDamageSourceFromLogs={{allow_hide_damage_source_from_logs}}\nRCONPort={{ports.rcon.port}}\nAutoSavePeriodMinutes={{auto_save_period_minutes}}\nBanListURL=\"{{ban_list_url}}\"\nCustomDynamicConfigUrl=\"{{custom_dynamic_config_url}}\"\nCustomLiveTuningUrl=\"{{custom_live_tuning_url}}\"\nShowFloatingDamageText={{show_floating_damage_text}}\nServerHardcore={{server_hardcore}}\nServerForceNoHUD={{server_force_no_hud}}\n{{#if spectator_password}}SpectatorPassword={{spectator_password}}\n{{/if}}KickIdlePlayersPeriod={{kick_idle_players_period}}\nTheMaxStructuresInRange={{the_max_structures_in_range}}\nMaxPlatformSaddleStructureLimit={{max_platform_saddle_structure_limit}}\nAutoDestroyOldStructuresMultiplier={{auto_destroy_old_structures_multiplier}}\nOnlyAutoDestroyCoreStructures={{only_auto_destroy_core_structures}}\nOnlyDecayUnsnappedCoreStructures={{only_decay_unsnapped_core_structures}}\nFastDecayUnsnappedCoreStructures={{fast_decay_unsnapped_core_structures}}\nDestroyTamesOverTheSoftTameLimit={{destroy_tames_over_soft_tame_limit}}\nMaxTamedDinos_SoftTameLimit={{max_tamed_dinos_soft_tame_limit}}\nMaxTamedDinos_SoftTameLimit_CountdownForDeletionDuration={{max_tamed_dinos_soft_tame_limit_countdown_for_deletion_duration}}\nNoTributeDownloads={{no_tribute_downloads}}\nPreventDownloadSurvivors={{prevent_download_survivors}}\nPreventDownloadItems={{prevent_download_items}}\nPreventDownloadDinos={{prevent_download_dinos}}\nPreventUploadSurvivors={{prevent_upload_survivors}}\nPreventUploadItems={{prevent_upload_items}}\nPreventUploadDinos={{prevent_upload_dinos}}\nMinimumDinoReuploadInterval={{minimum_dino_reupload_interval}}\nMaxTributeCharacters={{max_tribute_characters}}\nMaxTributeDinos={{max_tribute_dinos}}\nMaxTributeItems={{max_tribute_items}}\nTributeCharacterExpirationSeconds={{tribute_character_expiration_seconds}}\nTributeDinoExpirationSeconds={{tribute_dino_expiration_seconds}}\nTributeItemExpirationSeconds={{tribute_item_expiration_seconds}}\nbFilterChat={{filter_chat}}\nbFilterCharacterNames={{filter_character_names}}\nbFilterTribeNames={{filter_tribe_names}}\nBadWordListURL={{bad_word_list_url}}\nBadWordWhiteListURL={{bad_word_whitelist_url}}\nServerPVE=true\nUseExclusiveList={{exclusive_join_enabled}}\nAllowThirdPersonPlayer={{allow_third_person_player}}\nServerCrosshair={{server_crosshair}}\nShowMapPlayerLocation={{show_map_player_location}}\nDisableFriendlyFire={{disable_friendly_fire}}\nAllowFlyerCarryPvE={{allow_flyer_carry_pve}}\nAllowFlyingStaminaRecovery={{allow_flying_stamina_recovery}}\nAllowMultipleAttachedC4={{allow_multiple_attached_c4}}\nAllowRaidDinoFeeding={{allow_raid_dino_feeding}}\nGlobalVoiceChat={{global_voice_chat}}\nProximityChat={{proximity_chat}}\nAlwaysNotifyPlayerJoined={{always_notify_player_joined}}\nAlwaysNotifyPlayerLeft={{always_notify_player_left}}\nAllowHitMarkers={{allow_hit_markers}}\nDisableWeatherFog={{disable_weather_fog}}\nEnablePvPGamma={{enable_pvp_gamma}}\nDisablePvEGamma={{disable_pve_gamma}}\nPreventSpawnAnimations={{prevent_spawn_animations}}\nAllowCaveBuildingPvE={{allow_cave_building_pve}}\nDisableStructureDecayPvE={{disable_structure_decay_pve}}\nPreventOfflinePvP={{prevent_offline_pvp}}\nPreventOfflinePvPInterval={{prevent_offline_pvp_interval}}\nOverrideStructurePlatformPrevention={{override_structure_platform_prevention}}\nEnableExtraStructurePreventionVolumes={{enable_extra_structure_prevention_volumes}}\nPvEAllowStructuresAtSupplyDrops={{pve_allow_structures_at_supply_drops}}\nAllowCrateSpawnsOnTopOfStructures={{allow_crate_spawns_on_top_of_structures}}\nForceAllStructureLocking={{force_all_structure_locking}}\nDisableDinoDecayPvE={{disable_dino_decay_pve}}\nAutoDestroyDecayedDinos={{auto_destroy_decayed_dinos}}\nPvEStructureDecayPeriodMultiplier={{pve_structure_decay_period_multiplier}}\nPvEDinoDecayPeriodMultiplier={{pve_dino_decay_period_multiplier}}\nAllowIntegratedSPlusStructures={{allow_integrated_splus_structures}}\nXPMultiplier={{xp_multiplier}}\nTamingSpeedMultiplier={{taming_speed_multiplier}}\nHarvestAmountMultiplier={{harvest_amount_multiplier}}\nPlayerCharacterWaterDrainMultiplier={{player_character_water_drain_multiplier}}\nPlayerCharacterFoodDrainMultiplier={{player_character_food_drain_multiplier}}\nDinoCharacterFoodDrainMultiplier={{dino_character_food_drain_multiplier}}\nResourcesRespawnPeriodMultiplier={{resources_respawn_period_multiplier}}\nItemStackSizeMultiplier={{item_stack_size_multiplier}}\nDinoCountMultiplier={{dino_count_multiplier}}\nServerAutoForceRespawnWildDinosInterval={{server_auto_force_respawn_wild_dinos_interval}}\nPreventDiseases={{prevent_diseases}}\nbForceCanRideFliers={{force_can_ride_fliers}}\nPlayerDamageMultiplier={{player_damage_multiplier}}\nPlayerResistanceMultiplier={{player_resistance_multiplier}}\nDinoDamageMultiplier={{dino_damage_multiplier}}\nDinoResistanceMultiplier={{dino_resistance_multiplier}}\nTamedDinoDamageMultiplier={{tamed_dino_damage_multiplier}}\nTamedDinoResistanceMultiplier={{tamed_dino_resistance_multiplier}}\nStructureDamageMultiplier={{structure_damage_multiplier}}\nStructureResistanceMultiplier={{structure_resistance_multiplier}}\nEnableCryopodNerf={{enable_cryopod_nerf}}\nCryopodNerfDuration={{cryopod_nerf_duration}}\nCryopodNerfDamageMult={{cryopod_nerf_damage_mult}}\nCryopodNerfIncomingDamageMultPercent={{cryopod_nerf_incoming_damage_mult_percent}}\nEnableCryoSicknessPVE={{enable_cryo_sickness_pve}}\nDisableCryopodEnemyCheck={{disable_cryopod_enemy_check}}\nDisableCryopodFridgeRequirement={{disable_cryopod_fridge_requirement}}\nAllowCryoFridgeOnSaddle={{allow_cryo_fridge_on_saddle}}\nMatingIntervalMultiplier={{mating_interval_multiplier}}\nEggHatchSpeedMultiplier={{egg_hatch_speed_multiplier}}\nBabyMatureSpeedMultiplier={{baby_mature_speed_multiplier}}\nBabyCuddleIntervalMultiplier={{baby_cuddle_interval_multiplier}}\n\n[SessionSettings]\nPort={{ports.game.port}}\nQueryPort={{ports.query.port}}\nSessionName={{server_name}}\nMaxPlayers={{max_players}}\n\n[/Script/Engine.GameSession]\nStructurePickupTimeAfterPlacement={{structure_pickup_time_after_placement}}\nStructurePickupHoldDuration={{structure_pickup_hold_duration}}\n",
    )
    .unwrap();
    fs::write(
        templates_root.join("Game.ini.hbs"),
        "; Managed by LanGame Server Manager.\n\n[/script/shootergame.shootergamemode]\nResourceNoReplenishRadiusPlayers={{resource_no_replenish_radius_players}}\nResourceNoReplenishRadiusStructures={{resource_no_replenish_radius_structures}}\nCropGrowthSpeedMultiplier={{crop_growth_speed_multiplier}}\nCropDecaySpeedMultiplier={{crop_decay_speed_multiplier}}\nPoopIntervalMultiplier={{poop_interval_multiplier}}\nPerLevelStatsMultiplier_Player[0]={{player_level_health_multiplier}}\nPerLevelStatsMultiplier_Player[1]={{player_level_stamina_multiplier}}\nPerLevelStatsMultiplier_Player[3]={{player_level_oxygen_multiplier}}\nPerLevelStatsMultiplier_Player[4]={{player_level_food_multiplier}}\nPerLevelStatsMultiplier_Player[5]={{player_level_water_multiplier}}\nPerLevelStatsMultiplier_Player[7]={{player_level_weight_multiplier}}\nPerLevelStatsMultiplier_Player[8]={{player_level_melee_multiplier}}\nPerLevelStatsMultiplier_Player[9]={{player_level_speed_multiplier}}\nPerLevelStatsMultiplier_Player[10]={{player_level_fortitude_multiplier}}\nPerLevelStatsMultiplier_Player[11]={{player_level_crafting_multiplier}}\nPerLevelStatsMultiplier_DinoWild[0]={{dino_wild_level_health_multiplier}}\nPerLevelStatsMultiplier_DinoWild[1]={{dino_wild_level_stamina_multiplier}}\nPerLevelStatsMultiplier_DinoWild[8]={{dino_wild_level_damage_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[0]={{dino_tamed_level_health_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[1]={{dino_tamed_level_stamina_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[4]={{dino_tamed_level_food_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[7]={{dino_tamed_level_weight_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[8]={{dino_tamed_level_damage_multiplier}}\nPerLevelStatsMultiplier_DinoTamed[9]={{dino_tamed_level_speed_multiplier}}\n{{ark.level_experience_ramp_overrides_lines}}{{ark.override_player_level_engram_points_lines}}\nSupplyCrateLootQualityMultiplier={{supply_crate_loot_quality_multiplier}}\nFishingLootQualityMultiplier={{fishing_loot_quality_multiplier}}\nbDisableLootCrates={{disable_loot_crates}}\nRandomSupplyCratePoints={{random_supply_crate_points}}\nbAllowCustomRecipes={{allow_custom_recipes}}\nCustomRecipeEffectivenessMultiplier={{custom_recipe_effectiveness_multiplier}}\nCustomRecipeSkillMultiplier={{custom_recipe_skill_multiplier}}\nPlayerCharacterHealthRecoveryMultiplier={{player_character_health_recovery_multiplier}}\nPlayerCharacterStaminaDrainMultiplier={{player_character_stamina_drain_multiplier}}\nbLimitTurretsInRange={{limit_turrets_in_range}}\nbHardLimitTurretsInRange={{hard_limit_turrets_in_range}}\nLimitTurretsNum={{limit_turrets_num}}\nLimitTurretsRange={{limit_turrets_range}}\nbDisableStructurePlacementCollision={{disable_structure_placement_collision}}\n{{ark.config_override_item_crafting_costs_lines}}{{ark.config_override_item_max_quantity_lines}}{{ark.dino_class_damage_multipliers_lines}}{{ark.dino_class_resistance_multipliers_lines}}{{ark.tamed_dino_class_damage_multipliers_lines}}{{ark.tamed_dino_class_resistance_multipliers_lines}}\nPreventMateBoost={{prevent_mate_boost}}\nbUseSingleplayerSettings={{use_singleplayer_settings}}\nbShowCreativeMode={{show_creative_mode}}\nbUseDinoLevelUpAnimations={{use_dino_level_up_animations}}\nMatingIntervalMultiplier={{mating_interval_multiplier}}\nLayEggIntervalMultiplier={{lay_egg_interval_multiplier}}\nMatingSpeedMultiplier={{mating_speed_multiplier}}\nEggHatchSpeedMultiplier={{egg_hatch_speed_multiplier}}\nBabyMatureSpeedMultiplier={{baby_mature_speed_multiplier}}\nBabyFoodConsumptionSpeedMultiplier={{baby_food_consumption_speed_multiplier}}\nBabyCuddleIntervalMultiplier={{baby_cuddle_interval_multiplier}}\nBabyCuddleGracePeriodMultiplier={{baby_cuddle_grace_period_multiplier}}\nBabyCuddleLoseImprintQualitySpeedMultiplier={{baby_cuddle_lose_imprint_quality_speed_multiplier}}\nBabyImprintingStatScaleMultiplier={{baby_imprinting_stat_scale_multiplier}}\nBabyImprintAmountMultiplier={{baby_imprint_amount_multiplier}}\nAllowAnyoneBabyImprintCuddle={{allow_anyone_baby_imprint_cuddle}}\nDisableImprintDinoBuff={{disable_imprint_dino_buff}}\nbAutoUnlockAllEngrams={{auto_unlock_all_engrams}}\n{{ark.engram_entry_auto_unlock_lines}}{{ark.override_named_engram_entries_lines}}{{ark.npc_replacements_lines}}{{ark.dino_spawn_weight_multipliers_lines}}{{ark.config_add_npc_spawn_entries_container_lines}}{{ark.config_subtract_npc_spawn_entries_container_lines}}{{ark.config_override_npc_spawn_entries_container_lines}}{{ark.config_override_supply_crate_items_lines}}{{ark.prevent_transfer_for_class_names_lines}}\n",
    )
    .unwrap();
    fs::write(
        templates_root.join("AllowedCheaterAccountIDs.txt.hbs"),
        "{{admin_account_ids}}\n",
    )
    .unwrap();
    fs::write(
        templates_root.join("PlayersExclusiveJoinList.txt.hbs"),
        "{{exclusive_join_list}}\n",
    )
    .unwrap();
    fs::write(
        templates_root.join("PlayersJoinNoCheckList.txt.hbs"),
        "{{priority_join_list}}\n",
    )
    .unwrap();
}
