use super::*;

#[rustfmt::skip]
pub(crate) const ARK_ASA_ADDITIONAL_LAUNCH_SETTINGS: &[ArkLaunchSetting] = &[
    ("-ActiveEvent", "active_event", ArkLaunchSettingKind::Value),
    ("-AlwaysTickDedicatedSkeletalMeshes", "always_tick_dedicated_skeletal_meshes", ArkLaunchSettingKind::Flag),
    ("-AutoDestroyStructures", "enable_auto_destroy_structures", ArkLaunchSettingKind::Flag),
    ("-culture", "culture", ArkLaunchSettingKind::Value),
    ("-DoCustomCosmeticValidation", "do_custom_cosmetic_validation", ArkLaunchSettingKind::Flag),
    ("-DisableCustomCosmetics", "disable_custom_cosmetics", ArkLaunchSettingKind::Flag),
    ("-disabledinonetrangescaling", "disabledinonetrangescaling", ArkLaunchSettingKind::Flag),
    ("-EasterColors", "easter_colors", ArkLaunchSettingKind::Flag),
    ("-EnableIdlePlayerKick", "enable_idle_player_kick", ArkLaunchSettingKind::Flag),
    ("-exclusivejoin", "exclusive_join_enabled", ArkLaunchSettingKind::Flag),
    ("-ForceAllowCaveFlyers", "force_allow_cave_flyers", ArkLaunchSettingKind::Flag),
    ("-ForceRespawnDinos", "force_respawn_dinos", ArkLaunchSettingKind::Flag),
    ("-GBUsageToForceRestart", "gbusage_to_force_restart", ArkLaunchSettingKind::Value),
    ("-NoBattlEye", "battleye_enabled", ArkLaunchSettingKind::InvertedFlag),
    ("-NoDinos", "no_dinos", ArkLaunchSettingKind::Flag),
    ("-NoWildBabies", "no_wild_babies", ArkLaunchSettingKind::Flag),
    ("-passivemods", "passive_mod_ids_csv", ArkLaunchSettingKind::ModIds),
    ("-servergamelog", "server_game_log", ArkLaunchSettingKind::Flag),
    ("-servergamelogincludetribelogs", "server_game_log_include_tribe_logs", ArkLaunchSettingKind::Flag),
    ("-ServerRCONOutputTribeLogs", "server_game_log_include_tribe_logs", ArkLaunchSettingKind::Flag),
    ("-ServerUseEventColors", "server_use_event_colors", ArkLaunchSettingKind::Flag),
    ("-StasisKeepControllers", "stasis_keep_controllers", ArkLaunchSettingKind::Flag),
    ("-UseDynamicConfig", "use_dynamic_config", ArkLaunchSettingKind::Flag),
    ("-usestore", "usestore", ArkLaunchSettingKind::Flag),
    ("-clusterid", "cluster_id", ArkLaunchSettingKind::Value),
    ("-NoTransferFromFiltering", "no_transfer_from_filtering", ArkLaunchSettingKind::Flag),
    ("-CustomNotificationURL", "custom_notification_url", ArkLaunchSettingKind::Value),
    ("-disableCharacterTracker", "disable_character_tracker", ArkLaunchSettingKind::Flag),
    ("-EnableSteelShield", "enable_steel_shield", ArkLaunchSettingKind::Flag),
    ("-forceuseperfthreads", "forceuseperfthreads", ArkLaunchSettingKind::Flag),
    ("-NoAI", "no_ai", ArkLaunchSettingKind::Flag),
    ("-NoDinosExceptForcedSpawn", "no_dinos_except_forced_spawn", ArkLaunchSettingKind::Flag),
    ("-NoDinosExceptStreamingSpawn", "no_dinos_except_streaming_spawn", ArkLaunchSettingKind::Flag),
    ("-NoDinosExceptManualSpawn", "no_dinos_except_manual_spawn", ArkLaunchSettingKind::Flag),
    ("-NoDinosExceptWaterSpawn", "no_dinos_except_water_spawn", ArkLaunchSettingKind::Flag),
    ("-noperfthreads", "noperfthreads", ArkLaunchSettingKind::Flag),
    ("-nosound", "nosound", ArkLaunchSettingKind::Flag),
    ("-onethread", "onethread", ArkLaunchSettingKind::Flag),
    ("-ServerPlatform", "server_platform", ArkLaunchSettingKind::Value),
    ("-UnstasisDinoObstructionCheck", "unstasis_dino_obstruction_check", ArkLaunchSettingKind::Flag),
    ("-UseServerNetSpeedCheck", "use_server_net_speed_check", ArkLaunchSettingKind::Flag),
];
