use super::windrose_tests::{TestRoot, seed_server, seed_world, server_path};
use super::*;
use serde_json::json;

fn rendered_config(config_dir: &Path, invite_code: &str) {
    let document = json!({
        "Version": 1,
        "ServerDescription_Persistent": {
            "PersistentServerId": "TEMPLATE-MUST-NOT-REPLACE-NATIVE-ID",
            "WorldIslandId": "",
            "InviteCode": invite_code,
            "ServerName": "Isolated server",
            "IsPasswordProtected": true,
            "Password": "synthetic-fixture",
            "UseDirectConnection": true,
            "DirectConnectionServerPort": 28017,
            "P2pProxyAddress": "127.0.0.1",
            "DirectConnectionProxyAddress": "127.0.0.1"
        }
    });
    fs::write(
        config_dir.join(WINDROSE_SERVER_DESCRIPTION_FILE),
        serde_json::to_vec(&document).unwrap(),
    )
    .unwrap();
}

#[test]
fn fresh_windrose_config_omits_unassigned_identities_and_keeps_instance_transport() {
    let root = TestRoot::new("bootstrap-runtime");
    let config = TestRoot::new("bootstrap-config");
    rendered_config(config.path(), "");
    let settings = json!({ "world_island_id": "", "invite_code": "" });

    materialize_windrose_documents(
        root.path(),
        config.path(),
        settings.as_object().unwrap(),
        false,
    )
    .unwrap();

    let server: Value =
        serde_json::from_slice(&fs::read(server_path(root.path())).unwrap()).unwrap();
    let persistent = &server["ServerDescription_Persistent"];
    for key in ["PersistentServerId", "WorldIslandId", "InviteCode"] {
        assert!(
            persistent.get(key).is_none(),
            "{key} must be generated by the native server"
        );
    }
    assert_eq!(persistent["ServerName"], "Isolated server");
    assert_eq!(persistent["Password"], "synthetic-fixture");
    assert_eq!(persistent["IsPasswordProtected"], true);
    assert_eq!(persistent["UseDirectConnection"], true);
    assert_eq!(persistent["DirectConnectionServerPort"], 28017);
    assert_eq!(persistent["P2pProxyAddress"], "127.0.0.1");
    assert_eq!(persistent["DirectConnectionProxyAddress"], "127.0.0.1");
    assert!(!root.path().join("R5/Saved").exists());
    assert!(!pending_plan_path(config.path()).exists());
}

#[test]
fn unselected_windrose_world_preserves_native_identity_and_world_bytes_on_repeated_save() {
    let root = TestRoot::new("native-identity");
    let config = TestRoot::new("native-identity-config");
    let world_id = "E24A22C9C8D3448951AFD002162576D5";
    seed_server(root.path(), world_id);
    let native_path = server_path(root.path());
    let mut native: Value = serde_json::from_slice(&fs::read(&native_path).unwrap()).unwrap();
    native["ServerDescription_Persistent"]["InviteCode"] = json!("NativeInvite");
    fs::write(&native_path, serde_json::to_vec(&native).unwrap()).unwrap();
    let world = seed_world(root.path(), "0.10.0", world_id, world_id);
    let world_bytes = fs::read(&world).unwrap();
    rendered_config(config.path(), "");
    let settings = json!({ "world_island_id": "", "invite_code": "" });

    for _ in 0..2 {
        materialize_windrose_documents(
            root.path(),
            config.path(),
            settings.as_object().unwrap(),
            false,
        )
        .unwrap();
        let server: Value = serde_json::from_slice(&fs::read(&native_path).unwrap()).unwrap();
        let persistent = &server["ServerDescription_Persistent"];
        assert_eq!(persistent["PersistentServerId"], "SERVER-ID");
        assert_eq!(persistent["WorldIslandId"], world_id);
        assert_eq!(persistent["InviteCode"], "NativeInvite");
        assert_eq!(persistent["ServerName"], "Isolated server");
        assert_eq!(server["DeploymentId"], "build-owned");
        assert_eq!(persistent["UnknownPersistent"], "keep-me");
        assert_eq!(fs::read(&world).unwrap(), world_bytes);
        assert!(!pending_plan_path(config.path()).exists());
    }

    rendered_config(config.path(), "ExplicitInvite");
    let settings = json!({ "world_island_id": "", "invite_code": "ExplicitInvite" });
    materialize_windrose_documents(
        root.path(),
        config.path(),
        settings.as_object().unwrap(),
        false,
    )
    .unwrap();
    let server: Value = serde_json::from_slice(&fs::read(&native_path).unwrap()).unwrap();
    assert_eq!(
        server["ServerDescription_Persistent"]["InviteCode"],
        "ExplicitInvite"
    );
    assert_eq!(
        server["ServerDescription_Persistent"]["WorldIslandId"],
        world_id
    );
    assert_eq!(
        server["ServerDescription_Persistent"]["PersistentServerId"],
        "SERVER-ID"
    );
}
