use crate::{
    CpuCoreSnapshot, DiskVolumeSnapshot, MemoryModuleSnapshot, NetworkAdapterSnapshot,
    SystemTelemetry,
};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemSnapshot {
    pub telemetry: SystemTelemetry,
    pub disk_volumes: Vec<DiskVolumeSnapshot>,
    pub memory_commit_used_bytes: Option<u64>,
    pub memory_commit_limit_bytes: Option<u64>,
    pub cpu_percent: f32,
    pub cpu_name: String,
    pub cpu_frequency_mhz: u32,
    pub cpu_max_frequency_mhz: u32,
    pub cpu_physical_cores: u32,
    pub cpu_logical_cores: u32,
    pub cpu_single_core_peak_percent: f32,
    pub cpu_performance_percent: f32,
    pub cpu_cores: Vec<CpuCoreSnapshot>,
    pub memory_percent: f32,
    pub memory_total_bytes: u64,
    pub memory_available_bytes: u64,
    pub memory_modules: Vec<MemoryModuleSnapshot>,
    pub disk_used_percent: f32,
    pub disk_used_bytes: u64,
    pub disk_total_bytes: u64,
    pub disk_label: String,
    pub disk_volume_id: String,
    pub disk_model: String,
    pub disk_volume_name: String,
    pub disk_file_system: String,
    pub disk_read_bps: u64,
    pub disk_write_bps: u64,
    pub disk_read_latency_ms: f32,
    pub disk_write_latency_ms: f32,
    pub disk_queue_length: f32,
    pub network_receive_bps: u64,
    pub network_transmit_bps: u64,
    pub network_adapters: Vec<NetworkAdapterSnapshot>,
    pub instance_process_memory_bytes: u64,
    pub instance_process_memory_percent: f32,
    pub instance_process_count: usize,
    pub instance_process_threads: usize,
    pub instance_process_handles: usize,
    pub running_instances: usize,
    pub total_online_players: usize,
    pub total_player_capacity: usize,
    pub player_count_queried_instances: usize,
    pub player_count_queryable_instances: usize,
}

impl Default for SystemSnapshot {
    fn default() -> Self {
        Self {
            telemetry: SystemTelemetry::default(),
            disk_volumes: Vec::new(),
            memory_commit_used_bytes: None,
            memory_commit_limit_bytes: None,
            cpu_percent: 0.0,
            cpu_name: String::new(),
            cpu_frequency_mhz: 0,
            cpu_max_frequency_mhz: 0,
            cpu_physical_cores: 0,
            cpu_logical_cores: 0,
            cpu_single_core_peak_percent: 0.0,
            cpu_performance_percent: 0.0,
            cpu_cores: Vec::new(),
            memory_percent: 0.0,
            memory_total_bytes: 0,
            memory_available_bytes: 0,
            memory_modules: Vec::new(),
            disk_used_percent: 0.0,
            disk_used_bytes: 0,
            disk_total_bytes: 0,
            disk_label: String::new(),
            disk_volume_id: String::new(),
            disk_model: String::new(),
            disk_volume_name: String::new(),
            disk_file_system: String::new(),
            disk_read_bps: 0,
            disk_write_bps: 0,
            disk_read_latency_ms: 0.0,
            disk_write_latency_ms: 0.0,
            disk_queue_length: 0.0,
            network_receive_bps: 0,
            network_transmit_bps: 0,
            network_adapters: Vec::new(),
            instance_process_memory_bytes: 0,
            instance_process_memory_percent: 0.0,
            instance_process_count: 0,
            instance_process_threads: 0,
            instance_process_handles: 0,
            running_instances: 0,
            total_online_players: 0,
            total_player_capacity: 0,
            player_count_queried_instances: 0,
            player_count_queryable_instances: 0,
        }
    }
}
