export interface ArkRuleField { nativeKey: string; section: string; sample: string }
export const ARK_RULE_FIELDS: Readonly<Record<string, ArkRuleField>> = {
  npc_replacements: { nativeKey: "NPCReplacements", section: "spawns", sample: '(FromClassName="Raptor_Character_BP_C",ToClassName="")' },
  dino_spawn_weight_multipliers: { nativeKey: "DinoSpawnWeightMultipliers", section: "spawns", sample: '(DinoNameTag="Raptor",SpawnWeightMultiplier=1,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.1)' },
  config_add_npc_spawn_entries_container: { nativeKey: "ConfigAddNPCSpawnEntriesContainer", section: "spawns", sample: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((AnEntryName="Custom",EntryWeight=0.1,NPCsToSpawnStrings=("Raptor_Character_BP_C"))),NPCSpawnLimits=((NPCClassString="Raptor_Character_BP_C",MaxPercentageOfDesiredNumToAllow=0.1)))' },
  config_subtract_npc_spawn_entries_container: { nativeKey: "ConfigSubtractNPCSpawnEntriesContainer", section: "spawns", sample: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((NPCsToSpawnStrings=("Raptor_Character_BP_C"))))' },
  config_override_npc_spawn_entries_container: { nativeKey: "ConfigOverrideNPCSpawnEntriesContainer", section: "spawns", sample: '(NPCSpawnEntriesContainerClassString="DinoSpawnEntriesBeach_C",NPCSpawnEntries=((AnEntryName="Custom",EntryWeight=0.1,NPCsToSpawnStrings=("Raptor_Character_BP_C"))),NPCSpawnLimits=((NPCClassString="Raptor_Character_BP_C",MaxPercentageOfDesiredNumToAllow=0.1)))' },
  engram_entry_auto_unlocks: { nativeKey: "EngramEntryAutoUnlocks", section: "engrams", sample: '(EngramClassName="EngramEntry_Campfire_C",LevelToAutoUnlock=2)' },
  override_named_engram_entries: { nativeKey: "OverrideNamedEngramEntries", section: "engrams", sample: '(EngramClassName="EngramEntry_Campfire_C",EngramHidden=False,EngramPointsCost=3,EngramLevelRequirement=2,RemoveEngramPreReq=False)' },
  override_engram_entries: { nativeKey: "OverrideEngramEntries", section: "engrams", sample: '(EngramIndex=0,EngramHidden=False,EngramPointsCost=3,EngramLevelRequirement=2,RemoveEngramPreReq=False)' },
  config_override_supply_crate_items: { nativeKey: "ConfigOverrideSupplyCrateItems", section: "loot", sample: '(SupplyCrateClassString="SupplyCrate_Level03_C",MinItemSets=1,MaxItemSets=1,NumItemSetsPower=1,bSetsRandomWithoutReplacement=True,ItemSets=((SetName="Custom",MinNumItems=1,MaxNumItems=1,NumItemsPower=1,SetWeight=1,bItemsRandomWithoutReplacement=True,ItemEntries=((EntryWeight=1,ItemClassStrings=("PrimalItemResource_Stone_C"),ItemsWeights=(1),MinQuantity=1,MaxQuantity=10,MinQuality=0,MaxQuality=0,bForceBlueprint=False,ChanceToBeBlueprintOverride=0)))))' },
  config_override_item_crafting_costs: { nativeKey: "ConfigOverrideItemCraftingCosts", section: "crafting", sample: '(ItemClassString="PrimalItem_WeaponStonePick_C",BaseCraftingResourceRequirements=((ResourceItemTypeString="PrimalItemResource_Stone_C",BaseResourceRequirement=1,bCraftingRequireExactResourceType=False)))' },
  config_override_item_max_quantity: { nativeKey: "ConfigOverrideItemMaxQuantity", section: "crafting", sample: '(ItemClassString="PrimalItemResource_Stone_C",Quantity=(MaxItemQuantity=1000,bIgnoreMultiplier=True))' }
};
