const EXACT_ZH_SCHEMA_TITLES: Record<string, string> = {
  "Server Name": "服务器名称",
  "Map Name": "地图名称",
  "Max Players": "最大玩家数",
  "Server Password": "服务器密码",
  "Network Compression Threshold": "网络压缩阈值",
  "Packet Rate Limit": "数据包速率上限",
  "Use Native Transport": "使用原生网络传输",
  "Accepts Transfers": "接受玩家跨服转移",
  "Join Password": "加入密码",
  "Admin Password": "管理员密码",
  "Enable RCON": "启用 RCON",
  "Enable BattlEye": "启用 BattlEye",
  "PVE Mode": "PvE 模式",
  "PVP Mode": "PvP 模式",
  "Mods": "Mod ID",
  "Allow Cave Building in PVE": "PvE 允许洞穴建造",
  "Disable Structure Decay in PVE": "PvE 禁用结构衰败",
  "Offline PVP Delay Seconds": "离线 PvP 保护延迟 (秒)",
  "Override Platform Build Prevention": "覆盖平台建造限制",
  "Enable Extra Structure Prevention Volumes": "启用额外结构限制体积",
  "PVE Allow Structures At Supply Drops": "PvE 允许在补给点建造结构",
  "Allow Crate Spawns On Top Of Structures": "允许补给箱在结构顶部生成",
  "Force All Structure Locking": "强制所有结构上锁",
  "Structure Pickup Time After Placement Seconds": "放置后可拾取时间 (秒)",
  "Structure Pickup Hold Duration Seconds": "结构拾取按住时长 (秒)",
  "Max Structures In Range": "范围内结构上限",
  "Only Decay Unsnapped Core Structures": "仅衰败未连接核心结构",
  "Fast Decay Unsnapped Core Structures": "快速衰败未连接核心结构",
  "Limit Turrets In Range": "限制范围内炮塔",
  "Hard Limit Turrets In Range": "硬限制范围内炮塔",
  "Limit Turrets Num": "炮塔数量上限",
  "Limit Turrets Range": "炮塔限制范围",
  "Destroy Tames Over Soft Tame Limit": "超过软驯养上限时摧毁驯服生物",
  "Soft Tame Deletion Countdown Seconds": "软驯养删除倒计时 (秒)",
  "Force Can Ride Fliers": "强制可骑乘飞行生物",
  "Allow Flyer Speed Leveling": "允许飞行生物升级速度",
  "Use Dino Level-Up Animations": "使用恐龙升级动画",
  "Allow Cryo Fridge On Saddle": "允许鞍上放置低温冰箱",
  "Lay Egg Interval Multiplier": "产蛋间隔倍率",
  "Baby Food Consumption Speed Multiplier": "幼崽食物消耗速度倍率",
  "Random Supply Crate Points": "随机补给箱点位"
};

const TITLE_WORD_ZH: Record<string, string> = {
  Account: "账号",
  Active: "活动",
  Add: "添加",
  Additional: "额外",
  Admin: "管理员",
  Allow: "允许",
  All: "全部",
  Always: "始终",
  Amount: "数量",
  Animations: "动画",
  Any: "任意",
  Anyone: "任何人",
  Area: "区域",
  At: "在",
  Attached: "附着",
  Auto: "自动",
  Baby: "幼崽",
  Bad: "敏感",
  Ban: "封禁",
  BattlEye: "BattlEye",
  Block: "阻止",
  Bounds: "边界",
  Broadcast: "广播",
  Buff: "增益",
  Build: "建造",
  Building: "建造",
  Cap: "上限",
  Carry: "抓取",
  Cave: "洞穴",
  Character: "角色",
  Characters: "角色",
  Chat: "聊天",
  Check: "检查",
  Class: "类",
  Classes: "类",
  Cluster: "集群",
  Collision: "碰撞",
  Commands: "命令",
  Config: "配置",
  Consumption: "消耗",
  Container: "容器",
  Core: "核心",
  Cost: "成本",
  Costs: "成本",
  Count: "数量",
  Crate: "箱",
  Crates: "箱",
  Crafting: "制作",
  Creative: "创造",
  Crosshair: "准星",
  Cryo: "低温",
  Cryopod: "低温舱",
  Cuddle: "互动",
  Custom: "自定义",
  Cycle: "循环",
  Damage: "伤害",
  Day: "白天",
  Decay: "衰败",
  Decayed: "衰败",
  Delay: "延迟",
  Deletion: "删除",
  Dino: "恐龙",
  Dinos: "恐龙",
  Disable: "禁用",
  Disease: "疾病",
  Diseases: "疾病",
  Download: "下载",
  Downloads: "下载",
  Drain: "消耗",
  Duration: "持续时间",
  Dynamic: "动态",
  Effectiveness: "效果",
  Egg: "蛋",
  Enable: "启用",
  Enemy: "敌人",
  Engram: "印痕技能",
  Engrams: "印痕技能",
  Entries: "条目",
  Entry: "条目",
  Event: "事件",
  Exclusive: "专属",
  Experience: "经验",
  Expiration: "过期",
  Extra: "额外",
  Fast: "快速",
  Filter: "过滤",
  Fire: "伤害",
  Fishing: "钓鱼",
  Flags: "参数",
  Flyer: "飞行生物",
  Flying: "飞行",
  Fog: "雾",
  Food: "食物",
  Force: "强制",
  For: "用于",
  Fridge: "冰箱",
  Friendly: "友方",
  From: "来自",
  Gamma: "Gamma",
  Game: "游戏",
  Global: "全局",
  Grace: "宽限",
  Growth: "生长",
  Hard: "硬",
  Hardcore: "硬核",
  Harvest: "采集",
  Health: "生命",
  Hide: "隐藏",
  Hit: "命中",
  Hold: "按住",
  HUD: "HUD",
  ID: "ID",
  IDs: "ID",
  Idle: "闲置",
  Imprint: "留痕",
  Imprinting: "留痕",
  Include: "包含",
  Incoming: "承受",
  In: "中",
  in: "中",
  Integrated: "集成",
  Interval: "间隔",
  Item: "物品",
  Items: "物品",
  Joined: "加入",
  Kick: "踢出",
  Lay: "产",
  Left: "离开",
  Level: "等级",
  Limit: "上限",
  Limits: "上限",
  List: "名单",
  Live: "实时",
  Locking: "上锁",
  Log: "日志",
  Logs: "日志",
  Loot: "战利品",
  Map: "地图",
  Markers: "标记",
  Mate: "配偶",
  Mating: "交配",
  Mature: "成长",
  Max: "最大",
  Melee: "近战",
  Minimum: "最小",
  Minutes: "分钟",
  Mode: "模式",
  Multiplier: "倍率",
  Multipliers: "倍率",
  Name: "名称",
  Named: "命名",
  Nerf: "削弱",
  Night: "夜晚",
  Notify: "通知",
  NPC: "NPC",
  Number: "数量",
  Num: "数量",
  Offline: "离线",
  Official: "官方",
  Of: "的",
  of: "的",
  Old: "旧",
  Only: "仅",
  On: "在",
  Oxygen: "氧气",
  Over: "超过",
  Period: "周期",
  Percent: "百分比",
  Person: "人称",
  Placement: "放置",
  Platform: "平台",
  Player: "玩家",
  Players: "玩家",
  Points: "点数",
  Poop: "排泄",
  Prevent: "阻止",
  Prevention: "限制",
  Priority: "优先",
  Proximity: "近距离",
  PVE: "PvE",
  PvE: "PvE",
  PVP: "PvP",
  PvP: "PvP",
  Quality: "品质",
  Quantity: "数量",
  Radius: "半径",
  Raid: "突袭",
  Ramp: "曲线",
  Random: "随机",
  Range: "范围",
  RCON: "RCON",
  Recipe: "配方",
  Recipes: "配方",
  Recovery: "恢复",
  Replenish: "补充",
  Replacements: "替换",
  Requirement: "需求",
  Resistance: "抗性",
  Resource: "资源",
  Resources: "资源",
  Respawn: "刷新",
  Reupload: "重新上传",
  Ride: "骑乘",
  Saddle: "鞍",
  Save: "保存",
  Scale: "缩放",
  Seconds: "秒",
  Server: "服务器",
  Settings: "设置",
  Sickness: "疾病",
  Singleplayer: "单人",
  Size: "大小",
  Skill: "技能",
  Soft: "软",
  Source: "来源",
  Spawn: "生成",
  Spawns: "生成",
  Speed: "速度",
  Stamina: "体力",
  Stat: "属性",
  Structures: "结构",
  Structure: "结构",
  Subtract: "移除",
  Supply: "补给",
  Survivors: "幸存者",
  Tame: "驯养",
  Tamed: "驯服",
  Tames: "驯服生物",
  Taming: "驯养",
  Text: "文本",
  Third: "第三",
  Time: "时间",
  To: "到",
  Top: "顶部",
  Tuning: "调优",
  Turrets: "炮塔",
  Unlock: "解锁",
  Unlocks: "解锁",
  Unsnapped: "未连接",
  Up: "提升",
  Upload: "上传",
  Uploads: "上传",
  URL: "URL",
  Use: "使用",
  Voice: "语音",
  Volumes: "体积",
  Water: "水",
  Weather: "天气",
  Weight: "重量",
  Whitelist: "白名单",
  Wild: "野生",
  Word: "词",
  XP: "经验"
};

function tidyTranslatedTitle(value: string): string {
  return value
    .replace(/\s+/g, " ")
    .replace(/\s*\/\s*/g, " / ")
    .replace(/\s*\(\s*/g, " (")
    .replace(/\s*\)\s*/g, ") ")
    .replace(/\s+/g, " ")
    .replace(/([\u4e00-\u9fff])\s+(?=[\u4e00-\u9fff])/g, "$1")
    .trim();
}

export function localizeSchemaTitleFallback(title: string | undefined): string | undefined {
  if (!title) {
    return undefined;
  }

  const exact = EXACT_ZH_SCHEMA_TITLES[title] ?? Object.entries(EXACT_ZH_SCHEMA_TITLES)
    .find(([source]) => source.toLowerCase() === title.toLowerCase())?.[1];
  if (exact) {
    return exact;
  }

  let translatedAny = false;
  let missingWord = false;
  const parts = title.match(/[A-Za-z]+|\d+(?:\.\d+)?|[^A-Za-z\d]+/g) ?? [];
  const translated = parts
    .map((part) => {
      if (/^[A-Za-z]+$/.test(part)) {
        const mapped = TITLE_WORD_ZH[part];
        if (!mapped) {
          missingWord = true;
          return null;
        }
        translatedAny = true;
        return mapped;
      }
      return part;
    })
    .filter((part): part is string => part !== null)
    .join("");

  if (!translatedAny || missingWord) {
    return undefined;
  }

  return tidyTranslatedTitle(translated);
}
