"""Reviewed Barotrauma 1.13.4.0 setting semantics, independent of XML value spelling.

Types and closed enums follow official release ca7f5976fe16de7b153585ac4f6a12bdccbbbf8e.
New bounds follow native property setters, not the narrower ranges of UI sliders.
Content identifiers remain open strings because installed content packages can extend them.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class FieldMetadata:
    section: str
    value_type: str
    en_title: str
    zh_title: str
    en_description: str
    zh_description: str


FIELDS: dict[str, FieldMetadata] = {
    "server_name": FieldMetadata("room", "string", "Server name", "服务器名称", "Name shown in the server list and lobby.", "显示在服务器列表和大厅中的名称。"),
    "server_message": FieldMetadata("room", "string", "Server message", "服务器公告", "Message displayed to players in the lobby.", "向大厅中的玩家显示的服务器公告。"),
    "server_password": FieldMetadata("room", "string", "Join password", "加入密码", "Password required to join; leave empty to allow joining without a password.", "玩家加入时使用的密码；留空表示无需密码。"),
    "admin_entries": FieldMetadata("access", "string", "Administrator accounts", "管理员账号", "Managed in Player management and written to Data/clientpermissions.xml. Each line accepts a Steam2, Steam3 or SteamID64 account, optionally followed by a comma and display name; listed accounts receive full permissions.", "在玩家管理中维护，并写入 Data/clientpermissions.xml。每行填写 Steam2、Steam3 或 SteamID64，可在逗号后附加显示名称；列出的账号获得完整管理员权限。"),
    "max_players": FieldMetadata("room", "integer", "Player limit", "玩家人数上限", "Maximum simultaneous players, from 1 to 16.", "同时在线的玩家人数上限，范围为 1–16 人。"),
    "public_server": FieldMetadata("room", "boolean", "Public server listing", "公开服务器列表", "Advertise the server publicly. Private servers do not enable the Steam query endpoint.", "将服务器公布到公共列表。私有服务器不会启用 Steam 查询端口。"),
    "voice_chat_enabled": FieldMetadata("network", "boolean", "Voice chat", "语音聊天", "Allow players to use the game's voice chat.", "允许玩家使用游戏内语音聊天。"),
    "allow_file_transfers": FieldMetadata("network", "boolean", "Submarine file transfers", "潜艇文件传输", "Allow the server to send submarine files to connecting players.", "允许服务器向连接的玩家传输潜艇文件。"),
    "tick_rate": FieldMetadata("runtime", "integer", "Server tick rate (Hz)", "服务器更新频率（Hz）", "Server simulation updates per second, from 1 to 60.", "服务器每秒执行的模拟更新次数，范围为 1–60。"),
    "randomize_seed": FieldMetadata("round", "boolean", "Randomize level seed", "随机生成关卡种子", "Choose a new random level seed when starting a round.", "开始回合时使用新的随机关卡种子。"),
    "karma_enabled": FieldMetadata("gameplay", "boolean", "Karma system", "业力系统", "Track harmful player behavior and apply the selected karma rules.", "记录玩家的破坏行为，并应用所选业力规则。"),
    "use_respawn_shuttle": FieldMetadata("round", "boolean", "Respawn shuttle", "使用重生穿梭艇", "Respawn players in a shuttle; when disabled, respawn them aboard the main submarine.", "让玩家在重生穿梭艇内复活；关闭后在主潜艇内复活。"),
    "respawn_interval": FieldMetadata("round", "number", "Respawn countdown (seconds)", "重生倒计时（秒）", "Delay before respawning eligible players once the minimum respawn ratio is met.", "达到最低待重生玩家比例后，等待该时长再执行重生。"),
    "auto_restart": FieldMetadata("round", "boolean", "Automatically start next round", "自动开始下一回合", "Start a new round after the lobby countdown. This does not restart a crashed server process.", "大厅倒计时结束后开始新回合；此项不负责服务器进程崩溃后的重启。"),
    "auto_restart_interval": FieldMetadata("round", "number", "Next-round countdown (seconds)", "下一回合倒计时（秒）", "Lobby delay before automatically starting the next round.", "自动开始下一回合前，在大厅等待的时长。"),
    "start_when_clients_ready": FieldMetadata("round", "boolean", "Start when players are ready", "玩家就绪后开局", "Start the round when the configured proportion of players marks itself ready.", "达到指定比例的玩家确认就绪后开始回合。"),
    "allow_vote_kick": FieldMetadata("voting", "boolean", "Vote to kick players", "允许投票踢人", "Allow players to initiate votes to remove another player.", "允许玩家发起投票，将其他玩家移出服务器。"),
    "allow_end_voting": FieldMetadata("voting", "boolean", "Vote to end the round", "允许投票结束回合", "Allow players to vote to end the current round.", "允许玩家投票结束当前回合。"),
    "ban_after_wrong_password": FieldMetadata("access", "boolean", "Ban repeated password failures", "封禁反复输错密码的连接", "Automatically ban connections that exceed the allowed number of incorrect password attempts.", "连接连续输错加入密码并超过允许次数后，执行自动封禁。"),
    "max_password_retries_before_ban": FieldMetadata("access", "integer", "Incorrect password attempt limit", "错误密码尝试次数上限", "Number of incorrect join-password attempts allowed before automatic banning.", "自动封禁前允许输错加入密码的次数。"),
    "auto_ban_time": FieldMetadata("access", "number", "Automatic ban duration (seconds)", "自动封禁时长（秒）", "Duration of automatic bans for incorrect passwords and other server-enforced bans.", "输错密码等服务器自动封禁使用的持续时长。"),
    "mod_workshop_ids": FieldMetadata("runtime", "string", "Workshop content IDs", "创意工坊内容 ID", "Managed in Mods. List one Workshop item ID per line; installed packages are enabled for this instance.", "在模组选项卡管理。每行填写一个创意工坊物品 ID，安装的内容包会为当前实例启用。"),
    "extra_launch_args": FieldMetadata("runtime", "string", "Additional launch arguments", "额外启动参数", "Append one complete process argument per line to DedicatedServer startup.", "向 DedicatedServer 启动命令追加参数，每行一个完整的进程参数。"),
    "enable_upnp": FieldMetadata("network", "boolean", "UPnP port mapping", "UPnP 端口映射", "Ask a compatible router to create the server's port mappings automatically.", "请求支持 UPnP 的路由器自动创建服务器端口映射。"),
    "hidden_subs": FieldMetadata("round", "string", "Hidden submarines", "隐藏的潜艇", "Comma-separated submarine names to omit from the lobby selection list.", "从大厅选择列表中隐藏的潜艇名称，多个名称用英文逗号分隔。"),
    "allowed_random_mission_types": FieldMetadata("round", "string", "Random mission pool", "随机任务类型池", "Comma-separated mission type identifiers eligible for random selection; use installed content identifiers.", "允许随机抽取的任务类型标识，使用已安装内容中的标识，以英文逗号分隔。"),
    "allowed_client_name_chars": FieldMetadata("access", "string", "Allowed player-name characters", "玩家名称允许字符", "Comma-separated decimal Unicode code-point ranges, such as 65-90. Names containing other characters are rejected.", "允许用于玩家名称的 Unicode 十进制码位范围，例如 65-90；多项用英文逗号分隔，其他字符会被拒绝。"),
    "max_lag_compensation": FieldMetadata("network", "integer", "Weapon lag compensation (ms)", "武器延迟补偿（毫秒）", "Maximum time the server rewinds hit detection for delayed weapon input, from 0 to 500 milliseconds.", "服务器为延迟到达的开火输入回溯命中判定的最长时间，范围为 0–500 毫秒。"),
    "require_authentication": FieldMetadata("access", "boolean", "Require account authentication", "要求账号认证", "Verify joining clients through Steam or Epic ownership authentication; disabling this removes that account check.", "通过 Steam 或 Epic 所有权认证验证加入的客户端；关闭后不执行此账号检查。"),
    "max_transport_time": FieldMetadata("round", "number", "Respawn shuttle duration (seconds)", "重生艇运输时限（秒）", "Time available to reach the main submarine before the respawn shuttle leaves the level; 0 removes the time limit.", "重生穿梭艇离开关卡前，留给玩家前往主潜艇的时间；0 表示不限时。"),
    "min_respawn_ratio": FieldMetadata("round", "number", "Minimum respawn ratio", "最低待重生玩家比例", "Fraction of dead or spectating players required to dispatch a respawn; 0.2 means 20%.", "触发重生所需的死亡或观战玩家比例；0.2 表示 20%。"),
    "skill_loss_percentage_on_death": FieldMetadata("round", "number", "Skill loss on death (%)", "死亡技能损失（%）", "Percentage by which skills move toward the job's initial levels after death.", "死亡后，技能值向该职业初始技能水平回落的百分比。"),
    "skill_loss_percentage_on_immediate_respawn": FieldMetadata("round", "number", "Additional immediate-respawn skill loss (%)", "立即重生额外技能损失（%）", "Additional skill loss for choosing to respawn during the round, on top of the death penalty.", "选择在回合中立即重生时，在死亡惩罚基础上追加的技能损失百分比。"),
    "replace_cost_percentage": FieldMetadata("round", "number", "Replacement character cost (%)", "替代角色雇佣费用（%）", "Cost multiplier for replacing a permanently dead character; 100 is normal cost and 0 makes replacements free.", "替换永久死亡角色的雇佣费用百分比；100 为正常费用，0 为免费。"),
    "allow_bot_takeover_on_permadeath": FieldMetadata("round", "boolean", "Take over bots after permanent death", "永久死亡后接管机器人", "Allow a player whose character died permanently to control a crew bot.", "允许角色永久死亡的玩家接管船员机器人。"),
    "ironman_mode": FieldMetadata("round", "boolean", "Ironman campaign", "铁人战役", "With Permadeath respawning, a dead player can only spectate and cannot obtain a replacement character.", "仅在永久死亡重生模式下生效：角色死亡后只能观战，不能获得替代角色。"),
    "pvp_team_selection_mode": FieldMetadata("pvp", "string", "Team assignment", "队伍分配方式", "Use player team preferences for assignment, or let players explicitly choose their team.", "根据玩家的队伍偏好分配，或允许玩家明确选择队伍。"),
    "pvp_auto_balance_threshold": FieldMetadata("pvp", "integer", "Team size difference limit", "队伍人数差上限", "Maximum allowed difference between team sizes when players choose teams.", "玩家选择队伍时，两队允许的最大人数差。"),
    "start_when_clients_ready_ratio": FieldMetadata("round", "number", "Ready-player ratio", "开局就绪比例", "Fraction of players that must be ready to start automatically; 0.8 means 80%.", "自动开局所需的就绪玩家比例；0.8 表示 80%。"),
    "pvp_stun_resist": FieldMetadata("pvp", "number", "PvP stun resistance", "PvP 眩晕抗性", "Fraction of stun effects prevented for human characters in PvP; 0.5 means 50% resistance.", "PvP 中人类角色抵消眩晕效果的比例；0.5 表示 50% 抗性。"),
    "pvp_spawn_monsters": FieldMetadata("pvp", "boolean", "Spawn monsters in PvP", "PvP 生成怪物", "Include monsters in generated PvP levels.", "在生成的 PvP 关卡中加入怪物。"),
    "pvp_spawn_wrecks": FieldMetadata("pvp", "boolean", "Spawn wrecks in PvP", "PvP 生成沉船", "Include submarine wrecks in generated PvP levels.", "在生成的 PvP 关卡中加入潜艇残骸。"),
    "biome": FieldMetadata("round", "string", "Biome", "生态区域", "Biome identifier for level generation; Random lets the game choose.", "生成关卡使用的生态区域标识；Random 表示由游戏随机选择。"),
    "selected_outpost_name": FieldMetadata("round", "string", "Outpost", "前哨站", "Outpost selection identifier; Random lets the game choose.", "前哨站选择标识；Random 表示由游戏随机选择。"),
    "allow_spectating": FieldMetadata("gameplay", "boolean", "Allow spectating", "允许观战", "Allow connected players to watch without controlling a character.", "允许已连接玩家在不控制角色的情况下观看回合。"),
    "allow_afk": FieldMetadata("access", "boolean", "Allow away status", "允许离开状态", "Allow players to mark themselves away; away players are excluded from active participation and their inactivity timer pauses.", "允许玩家标记为离开状态；离开玩家不参与活动，并暂停其无操作踢出计时。"),
    "save_server_logs": FieldMetadata("runtime", "boolean", "Write server logs", "写入服务器日志", "Save the game's server activity log to disk.", "将游戏服务器活动日志写入磁盘。"),
    "allow_mod_downloads": FieldMetadata("network", "boolean", "Allow client Mod downloads", "允许客户端下载模组", "Allow joining clients to download the server's enabled content packages.", "允许加入的客户端下载服务器启用的内容包。"),
    "allow_remote_campaign_interactions": FieldMetadata("campaign", "boolean", "Remote campaign interactions", "远程战役交互", "Allow campaign interactions such as shops without moving the character to the relevant NPC.", "允许不将角色移动到对应 NPC 身边即可进行商店等战役交互。"),
    "play_style": FieldMetadata("room", "string", "Play style", "游玩风格", "Server-list category describing the intended play style; it does not select a game mode.", "服务器列表中展示的游玩风格分类，不用于选择游戏模式。"),
    "los_mode": FieldMetadata("gameplay", "string", "Line-of-sight visibility", "视线遮挡模式", "Choose unrestricted vision, dim static scenery through walls, or fully opaque obstruction.", "选择不限制视线、隔墙显示暗化的静态场景，或完全遮住被阻挡的区域。"),
    "show_enemy_health_bars": FieldMetadata("gameplay", "string", "Enemy health bars", "敌人生命条", "Show all enemy health bars, only boss health bars, or none.", "显示所有敌人生命条、仅首领生命条，或全部隐藏。"),
    "lines_per_log_file": FieldMetadata("runtime", "integer", "Lines per log file", "每个日志文件行数", "Maximum number of log lines before the game starts another log file.", "单个日志文件达到该行数后，游戏开始写入下一个日志文件。"),
    "respawn_mode": FieldMetadata("round", "string", "Respawn mode", "重生模式", "Choose no respawning, mid-round respawning, between-round respawning, or permanent character death.", "选择禁止重生、回合中重生、回合间重生，或角色永久死亡。"),
    "bot_count": FieldMetadata("bots", "integer", "Crew bot count", "船员机器人数量", "Number of bots to add in Normal mode, or the target crew size in Fill mode.", "普通模式中加入的机器人数量；补齐模式中要补齐到的船员人数。"),
    "max_bot_count": FieldMetadata("bots", "integer", "Crew bot limit", "船员机器人上限", "Maximum number of crew bots allowed by the server.", "服务器允许的船员机器人数量上限。"),
    "bot_spawn_mode": FieldMetadata("bots", "string", "Bot population mode", "机器人补员方式", "Normal adds the configured bot count; Fill uses bots to fill the crew target.", "普通模式加入指定数量的机器人；补齐模式用机器人补足目标船员人数。"),
    "disable_bot_conversations": FieldMetadata("bots", "boolean", "Disable bot conversations", "禁用机器人闲聊", "Suppress ambient conversations between crew bots.", "关闭船员机器人之间的环境闲聊。"),
    "selected_level_difficulty": FieldMetadata("round", "number", "Level difficulty", "关卡难度", "Difficulty used for a selected non-campaign level, from 0 to 100.", "所选非战役关卡使用的难度，范围为 0–100。"),
    "allow_disguises": FieldMetadata("gameplay", "boolean", "Allow disguises", "允许伪装身份", "Allow characters to conceal or impersonate their identity using disguise items.", "允许角色使用伪装物品隐藏或冒用身份。"),
    "allow_rewiring": FieldMetadata("gameplay", "boolean", "Allow rewiring", "允许重新接线", "Allow players to change device wiring during play.", "允许玩家在游戏中修改设备接线。"),
    "allow_immediate_item_delivery": FieldMetadata("campaign", "boolean", "Immediate item delivery", "允许立即交付物品", "Allow purchased campaign items to be delivered immediately.", "允许战役中购买的物品立即交付。"),
    "lock_all_default_wires": FieldMetadata("gameplay", "boolean", "Lock original wiring", "锁定原有接线", "Prevent players from removing the submarine's original wires.", "阻止玩家拆除潜艇原本已有的接线。"),
    "allow_linking_wifi_to_chat": FieldMetadata("gameplay", "boolean", "Link Wi-Fi components to chat", "允许无线组件连接聊天", "Allow Wi-Fi components to exchange signals with the chat system.", "允许无线组件与聊天系统交换信号。"),
    "allow_friendly_fire": FieldMetadata("pvp", "boolean", "Friendly fire", "友军伤害", "Allow damage between characters on the same team.", "允许同队角色之间造成伤害。"),
    "allow_drag_and_drop_give": FieldMetadata("gameplay", "boolean", "Give items by drag and drop", "拖放物品赠送", "Allow giving another character an item by dragging it onto them.", "允许将物品拖到另一角色身上来赠送物品。"),
    "destructible_outposts": FieldMetadata("gameplay", "boolean", "Destructible outposts", "前哨站可破坏", "Allow damage to outpost structures.", "允许破坏前哨站结构。"),
    "killable_npcs": FieldMetadata("bots", "boolean", "Killable NPCs", "NPC 可被杀死", "Allow non-player characters to be killed.", "允许杀死非玩家角色。"),
    "enable_dos_protection": FieldMetadata("network", "boolean", "Network abuse protection", "网络滥用防护", "Enable the game's protection against excessive network traffic.", "启用游戏对异常大量网络流量的防护。"),
    "max_packet_amount": FieldMetadata("network", "integer", "Client message limit (per minute)", "客户端消息上限（每分钟）", "Kick clients exceeding this message rate. A value at or below 1200 disables the limit; values below 3500 can disconnect normal clients.", "客户端每分钟发送消息超过此值会被踢出。1200 或更低表示不限速；低于 3500 可能影响正常客户端。"),
    "selected_submarine": FieldMetadata("round", "string", "Selected submarine", "选定潜艇", "Name of an installed submarine to select in the lobby.", "大厅中选定的已安装潜艇名称。"),
    "selected_shuttle": FieldMetadata("round", "string", "Selected respawn shuttle", "选定重生穿梭艇", "Name of an installed shuttle to use for respawning.", "用于重生的已安装穿梭艇名称。"),
    "traitor_probability": FieldMetadata("pvp", "number", "Traitor event probability", "叛徒事件概率", "Probability of traitor events, from 0 to 1; 0 disables them and 1 means 100%.", "叛徒事件发生概率，范围为 0–1；0 为关闭，1 为 100%。"),
    "traitor_danger_level": FieldMetadata("pvp", "integer", "Traitor danger level", "叛徒危险等级", "Highest traitor-event danger level, from 1 to 3.", "允许的叛徒事件最高危险等级，范围为 1–3。"),
    "traitors_min_player_count": FieldMetadata("pvp", "integer", "Minimum players for traitors", "叛徒事件最低玩家数", "Minimum connected players required before traitor events can occur.", "允许出现叛徒事件所需的最低在线玩家人数。"),
    "min_percentage_of_players_for_traitor_accusation": FieldMetadata("pvp", "number", "Traitor accusation threshold (%)", "叛徒指控比例（%）", "Percentage of players required to support a traitor accusation.", "叛徒指控成立所需的玩家支持百分比。"),
    "language": FieldMetadata("room", "string", "Server language", "服务器语言", "Language advertised for this server, using a game language identifier such as English.", "服务器对外展示的语言，使用游戏语言标识，例如 English。"),
    "sub_selection_mode": FieldMetadata("round", "string", "Submarine selection", "潜艇选择方式", "Let an administrator select the submarine, choose randomly, or use a player vote.", "由管理员手动选择、随机选择，或由玩家投票选择潜艇。"),
    "mode_selection_mode": FieldMetadata("round", "string", "Game mode selection", "游戏模式选择方式", "Let an administrator select the mode, choose randomly, or use a player vote.", "由管理员手动选择、随机选择，或由玩家投票选择游戏模式。"),
    "end_vote_required_ratio": FieldMetadata("voting", "number", "End-round vote ratio", "结束回合所需票数比例", "Fraction of players needed to pass an end-round vote; 0.6 means 60%.", "通过结束回合投票所需的玩家比例；0.6 表示 60%。"),
    "vote_required_ratio": FieldMetadata("voting", "number", "General vote ratio", "普通投票所需比例", "Required vote fraction for supported lobby and campaign voting; 0.6 means 60%.", "大厅和战役中适用投票所需的支持比例；0.6 表示 60%。"),
    "vote_timeout": FieldMetadata("voting", "number", "Vote timeout (seconds)", "投票超时（秒）", "Time allowed to complete a timed vote.", "限时投票允许持续的时间。"),
    "kick_vote_required_ratio": FieldMetadata("voting", "number", "Kick vote ratio", "踢人投票所需比例", "Fraction of eligible players required to pass a kick vote; 0.6 means 60%.", "通过踢人投票所需的有效玩家支持比例；0.6 表示 60%。"),
    "disallow_kick_vote_time": FieldMetadata("voting", "number", "New-player voting delay (seconds)", "新加入玩家投票等待时间（秒）", "Time after joining before a player is counted among eligible kick voters.", "玩家加入后，经过该时长才计入有资格参与踢人投票的玩家人数。"),
    "kill_disconnected_time": FieldMetadata("round", "number", "Disconnected character death delay (seconds)", "断线角色死亡延迟（秒）", "Time a disconnected character remains before being removed through brain death in ordinary respawn modes.", "普通重生模式下，断线角色保留多久后因脑死亡而被移除。"),
    "despawn_disconnected_permadeath_time": FieldMetadata("round", "number", "Permadeath disconnect removal delay (seconds)", "永久死亡模式断线移除延迟（秒）", "Time a disconnected character remains vulnerable before removal in Permadeath mode.", "永久死亡模式下，断线角色在仍可受伤的状态中保留多久后被移除。"),
    "kick_afk_time": FieldMetadata("access", "number", "Inactivity kick delay (seconds)", "无操作踢出延迟（秒）", "Time without player input before kicking. Allowed away status pauses this timer; administrator exemptions follow the game.", "玩家持续无操作多久后被踢出。允许的离开状态会暂停计时；管理员豁免规则由游戏处理。"),
    "minimum_mid_round_sync_timeout": FieldMetadata("network", "number", "Mid-round sync grace period (seconds)", "回合中同步宽限期（秒）", "Minimum time given to a client joining an ongoing round to synchronize its state.", "给予中途加入回合的客户端完成状态同步的最短时间。"),
    "round_start_sync_duration": FieldMetadata("network", "number", "Round-start sync timeout (seconds)", "开局同步超时（秒）", "Time allowed for clients to synchronize after the round starts before disconnecting them.", "回合开始后允许客户端完成同步的时间，超时后断开连接。"),
    "event_removal_time": FieldMetadata("network", "number", "Delivered event retention (seconds)", "已送达事件保留时间（秒）", "Retain events for this duration after all currently synchronized clients have received them.", "所有当前已同步客户端收到事件后，服务器继续保留该事件的时长。"),
    "old_received_event_kick_time": FieldMetadata("network", "number", "Partially delivered event timeout (seconds)", "部分送达事件超时（秒）", "Disconnect a client that still lacks an event after it has already been delivered to another client for this duration.", "事件已送达其他客户端后，某客户端仍未收到该事件超过此时长则断开连接。"),
    "old_event_kick_time": FieldMetadata("network", "number", "Undelivered event timeout (seconds)", "未送达事件超时（秒）", "Disconnect a client that has not received an event within this duration.", "客户端在该时长内仍未收到事件时断开连接。"),
    "timeout_threshold_not_in_game": FieldMetadata("network", "number", "Lobby connection timeout (seconds)", "大厅连接超时（秒）", "Disconnect after this period without messages while in the lobby or loading screen.", "大厅或加载界面中，连接持续收不到消息超过此时长则断开。"),
    "timeout_threshold_in_game": FieldMetadata("network", "number", "In-round connection timeout (seconds)", "回合内连接超时（秒）", "Disconnect after this period without messages during an active round.", "正在进行的回合中，连接持续收不到消息超过此时长则断开。"),
    "karma_preset": FieldMetadata("gameplay", "string", "Karma preset", "业力预设", "Name of a karma rule preset available in the server's karma configuration.", "服务器业力配置中可用的规则预设名称。"),
    "game_mode_identifier": FieldMetadata("round", "string", "Game mode", "游戏模式", "Installed game-mode identifier, for example sandbox, mission, pvp or multiplayercampaign.", "已安装的游戏模式标识，例如 sandbox、mission、pvp 或 multiplayercampaign。"),
    "mission_types": FieldMetadata("round", "string", "Selected mission types", "选定任务类型", "Comma-separated mission type identifiers selected for the round.", "为回合选定的任务类型标识，多个标识用英文逗号分隔。"),
    "max_auto_ban_time": FieldMetadata("access", "number", "Automatic ban duration limit (seconds)", "自动封禁时长上限（秒）", "Upper duration offered by the game's automatic-ban settings control.", "游戏自动封禁设置控件允许选择的最长封禁时间。"),
    "looted_money_destination": FieldMetadata("campaign", "string", "Looted money destination", "拾取金钱去向", "Send looted money to the shared bank or the looting character's wallet.", "将拾取的金钱存入公共银行，或归入拾取角色的钱包。"),
    "maximum_money_transfer_request": FieldMetadata("campaign", "integer", "Money transfer request limit", "转账申请金额上限", "Largest amount a player can request in one campaign money transfer.", "玩家单次战役转账申请允许请求的最高金额。"),
    "new_campaign_default_salary": FieldMetadata("campaign", "number", "New-campaign salary share (%)", "新战役默认薪资比例（%）", "Default percentage share used for crew salaries when creating a campaign.", "创建新战役时，分配给船员薪资的默认百分比。"),
    "track_opponent_in_pvp": FieldMetadata("pvp", "boolean", "Show opposing submarine on sonar", "声呐显示敌方潜艇", "Show the opposing team's submarine on sonar in PvP.", "在 PvP 声呐上显示敌方队伍的潜艇。"),
    "disembark_point_allowance": FieldMetadata("gameplay", "integer", "Starting perk points", "开局增益点数", "Points available for selecting starting perks in PvP, mission and sandbox modes.", "PvP、任务和沙盒模式中，用于选择开局增益的点数。"),
    "selected_coalition_perks": FieldMetadata("gameplay", "string", "Coalition starting perks", "联盟开局增益", "Semicolon-separated identifiers of selected Coalition perks, within the perk point allowance.", "联盟已选开局增益标识，用英文分号分隔，总消耗应在增益点数额度内。"),
    "win_score_pvp": FieldMetadata("pvp", "integer", "PvP winning score", "PvP 获胜分数", "Score needed to win PvP missions that use a scoring system.", "采用计分机制的 PvP 任务中，获胜所需的分数。"),
    "selected_separatists_perks": FieldMetadata("gameplay", "string", "Separatist starting perks", "分离主义者开局增益", "Semicolon-separated identifiers of selected Separatist perks, within the perk point allowance.", "分离主义者已选开局增益标识，用英文分号分隔，总消耗应在增益点数额度内。"),
    "disabled_monsters": FieldMetadata("gameplay", "string", "Disabled monster species", "禁用的怪物种类", "Comma-separated creature identifiers excluded from monster spawning.", "禁止生成的生物标识，多个标识用英文逗号分隔。"),
    "campaign_preset_name": FieldMetadata("campaign", "string", "Campaign preset name", "战役预设名称", "Name recorded for the campaign settings preset; individual values below remain explicit settings.", "记录的战役设置预设名称；下方各项仍使用各自明确填写的数值。"),
    "campaign_tutorial_enabled": FieldMetadata("campaign", "boolean", "Campaign tutorial", "战役教程", "Enable tutorial guidance when starting the campaign.", "开始战役时启用教程引导。"),
    "campaign_radiation_enabled": FieldMetadata("campaign", "boolean", "Jovian radiation", "木卫辐射", "Enable the radiation front that advances across the campaign map.", "启用在战役地图中逐步推进的辐射区域。"),
    "campaign_max_mission_count": FieldMetadata("campaign", "integer", "Missions per departure", "每次出航任务上限", "Base number of missions selectable for one departure, from 1 to 10; talents may add more.", "每次出航可选任务的基础上限，范围为 1–10；角色天赋可能额外增加。"),
    "campaign_world_hostility": FieldMetadata("campaign", "string", "World hostility", "世界危险程度", "Campaign difficulty tier affecting level difficulty and event pressure.", "影响关卡难度和事件压力的战役危险程度档位。"),
    "campaign_start_item_set": FieldMetadata("campaign", "string", "Starting supply set", "开局补给套组", "Identifier of an installed starting-item set, such as normal.", "已安装的开局物品套组标识，例如 normal。"),
    "campaign_starting_balance_amount": FieldMetadata("campaign", "string", "Starting funds", "初始资金档位", "Select the initial campaign bank-balance tier defined by the campaign presets.", "选择战役预设中定义的初始银行资金档位。"),
    "campaign_crew_vitality_multiplier": FieldMetadata("campaign", "number", "Crew vitality multiplier", "船员生命值倍率", "Multiply the vitality of crew characters; 1 keeps the normal value.", "船员角色生命值倍率；1 为正常数值。"),
    "campaign_non_crew_vitality_multiplier": FieldMetadata("campaign", "number", "Non-crew vitality multiplier", "非船员生命值倍率", "Multiply the vitality of characters outside the crew; 1 keeps the normal value.", "非船员角色生命值倍率；1 为正常数值。"),
    "campaign_oxygen_multiplier": FieldMetadata("campaign", "number", "Oxygen tank capacity multiplier", "氧气瓶容量倍率", "Multiply the capacity of oxygen-source tanks, rather than oxygen consumption.", "调整作为氧气来源的气瓶容量，不是氧气消耗速度。"),
    "campaign_fuel_multiplier": FieldMetadata("campaign", "number", "Reactor fuel duration multiplier", "反应堆燃料持续时间倍率", "Multiply how long reactor fuel lasts; higher values extend fuel duration.", "调整反应堆燃料可持续使用的时间；数值越大，燃料越耐用。"),
    "campaign_mission_reward_multiplier": FieldMetadata("campaign", "number", "Mission money reward multiplier", "任务金钱奖励倍率", "Multiply money earned from completing campaign missions.", "调整完成战役任务获得的金钱奖励。"),
    "campaign_experience_reward_multiplier": FieldMetadata("campaign", "number", "Experience reward multiplier", "经验奖励倍率", "Multiply experience rewards earned by campaign characters.", "调整战役角色获得的经验奖励。"),
    "campaign_shop_price_multiplier": FieldMetadata("campaign", "number", "Shop price multiplier", "商店价格倍率", "Multiply campaign shop prices.", "调整战役商店商品价格。"),
    "campaign_shipyard_price_multiplier": FieldMetadata("campaign", "number", "Shipyard price multiplier", "船坞价格倍率", "Multiply campaign shipyard prices.", "调整战役船坞的价格。"),
    "campaign_repair_fail_multiplier": FieldMetadata("campaign", "number", "Failed-repair damage multiplier", "维修失败伤害倍率", "Multiply damage suffered when a repair attempt fails.", "调整维修失败时受到的伤害。"),
    "campaign_show_husk_warning": FieldMetadata("campaign", "boolean", "Early husk infection warning", "提前提示画皮感染", "Warn about a husk infection before it becomes visible in the health interface.", "画皮感染在健康界面中显现之前，提前发出感染提示。"),
    "campaign_patdown_probability": FieldMetadata("campaign", "string", "Security search frequency", "安保搜身频率", "Select how frequently outpost security performs searches, or disable them.", "选择前哨站安保人员搜身检查的频率，或关闭检查。"),
}


ENUMS: dict[str, tuple[tuple[str, str, str], ...]] = {
    "play_style": (("Serious", "Serious", "严肃"), ("Casual", "Casual", "休闲"), ("Roleplay", "Roleplay", "角色扮演"), ("Rampage", "Rampage", "混战"), ("SomethingDifferent", "Other", "其他")),
    "respawn_mode": (("None", "No respawning", "禁止重生"), ("MidRound", "During rounds", "回合中重生"), ("BetweenRounds", "Between rounds", "回合间重生"), ("Permadeath", "Permanent death", "永久死亡")),
    "pvp_team_selection_mode": (("PlayerPreference", "Player preference", "按玩家偏好分配"), ("PlayerChoice", "Player choice", "玩家自行选队")),
    "bot_spawn_mode": (("Normal", "Fixed bot count", "固定机器人数量"), ("Fill", "Fill crew slots", "补齐船员人数")),
    "los_mode": (("None", "Unrestricted", "无遮挡"), ("Transparent", "Dim scenery through walls", "隔墙显示暗化场景"), ("Opaque", "Opaque walls", "完全遮挡")),
    "show_enemy_health_bars": (("ShowAll", "All enemies", "所有敌人"), ("BossHealthBarsOnly", "Bosses only", "仅首领"), ("HideAll", "Hidden", "全部隐藏")),
    "sub_selection_mode": (("Manual", "Administrator selection", "管理员手动选择"), ("Random", "Random", "随机选择"), ("Vote", "Player vote", "玩家投票")),
    "mode_selection_mode": (("Manual", "Administrator selection", "管理员手动选择"), ("Random", "Random", "随机选择"), ("Vote", "Player vote", "玩家投票")),
    "looted_money_destination": (("Bank", "Shared bank", "公共银行"), ("Wallet", "Character wallet", "角色钱包")),
    "campaign_world_hostility": (("Low", "Low", "较低"), ("Medium", "Medium", "中等"), ("High", "High", "较高"), ("Hellish", "Hellish", "地狱难度")),
    "campaign_starting_balance_amount": (("Low", "Low", "较少"), ("Medium", "Medium", "中等"), ("High", "High", "较多")),
    "campaign_patdown_probability": (("Off", "Disabled", "关闭"), ("Low", "Low", "较低"), ("Medium", "Medium", "中等"), ("High", "High", "较高")),
}

BOUNDS: dict[str, tuple[float, float | None]] = {
    "max_players": (1, 16), "tick_rate": (1, 60), "max_lag_compensation": (0, 500),
    "selected_level_difficulty": (0, 100), "traitor_probability": (0, 1),
    "traitor_danger_level": (1, 3), "traitors_min_player_count": (1, 16),
    "campaign_max_mission_count": (1, 10),
    # Preserve the module's existing minimums for these established settings.
    "respawn_interval": (1, None), "auto_restart_interval": (1, None),
    "max_password_retries_before_ban": (1, None), "auto_ban_time": (0, None),
}
