#!/usr/bin/env node
// Build NSIS branding from the existing path-based LGSM logo; no fonts or npm dependencies.
// Usage: node scripts/generate_desktop_installer_branding.cjs --work-dir <external-directory> [--check] [--browser <exe>]
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const { spawn, execFileSync } = require("node:child_process");
const { createHash, randomUUID } = require("node:crypto");
const { pathToFileURL } = require("node:url");

const root = path.resolve(__dirname, "..");
const brandingRoot = path.join(root, "apps/desktop/src-tauri/installer/branding");
const sourceRoot = path.join(root, "apps/desktop/src/assets");

function parseArguments() {
  const args = process.argv.slice(2);
  const result = { check: false };
  while (args.length) {
    const arg = args.shift();
    if (arg === "--check") result.check = true;
    else if (arg === "--work-dir" || arg === "--browser") {
      const value = args.shift();
      assert.ok(value && !value.startsWith("--"), `${arg} needs a value`);
      result[arg === "--work-dir" ? "workDir" : "browser"] = path.resolve(value);
    } else throw new Error(`Unknown argument: ${arg}`);
  }
  assert.ok(result.workDir, "An external --work-dir is required for the renderer profile and previews");
  const relative = path.relative(root, result.workDir);
  assert.ok(relative.startsWith(".." + path.sep) || path.isAbsolute(relative), "--work-dir must be outside the repository");
  return result;
}

async function browserExecutable(explicit) {
  const candidates = explicit ? [explicit] : [
    process.env.LANGAME_RELIABILITY_BROWSER,
    process.env.ProgramFiles && path.join(process.env.ProgramFiles, "Google/Chrome/Application/chrome.exe"),
    process.env["ProgramFiles(x86)"] && path.join(process.env["ProgramFiles(x86)"], "Microsoft/Edge/Application/msedge.exe"),
    process.env.LOCALAPPDATA && path.join(process.env.LOCALAPPDATA, "Google/Chrome/Application/chrome.exe"),
  ];
  for (const candidate of candidates.filter(Boolean)) {
    try { if ((await fs.stat(candidate)).isFile()) return candidate; }
    catch (error) { if (error.code !== "ENOENT") throw error; }
  }
  throw new Error("An installed Chrome/Edge is required; pass --browser or LANGAME_RELIABILITY_BROWSER");
}

function logo(source, { prefix, x, y, width, height, iconOnly = false }) {
  assert.match(source, /viewBox="139 210\.91 1768 266\.17"/);
  assert.doesNotMatch(source, /<(?:text|image|script)\b/i, "Logo must remain self-contained vector paths");
  let body = source.slice(source.indexOf(">") + 1, source.lastIndexOf("</svg>"))
    .replace(/\s*<(title|desc)\b[^>]*>[\s\S]*?<\/\1>/g, "")
    .replace(/id="([^"]+)"/g, `id="${prefix}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#${prefix}-$1)`)
    .replaceAll("#06182D", "#181818").replaceAll("#F5F7FA", "#F5F5F5");
  return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="${iconOnly ? "139 210.91 575 266.17" : "139 210.91 1768 266.17"}" overflow="hidden">${body}</svg>`;
}

async function makeSources() {
  const light = (await fs.readFile(path.join(sourceRoot, "langame-logo.svg"), "utf8")).replaceAll("\r\n", "\n");
  const dark = (await fs.readFile(path.join(sourceRoot, "langame-logo-dark.svg"), "utf8")).replaceAll("\r\n", "\n");
  const wrap = (name, width, height, sourceName, source, body) => ({
    name, width, height,
    svg: `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" color-interpolation="sRGB">\n`
      + `<title>LanGame Server Manager installer ${name}</title>\n`
      + `<!-- Generated by scripts/generate_desktop_installer_branding.cjs. Geometry: apps/desktop/src/assets/${sourceName}; normalized SHA-256: ${createHash("sha256").update(source).digest("hex")}. Only monochrome palette and layout are adapted. -->\n`
      + body + "\n</svg>\n",
  });
  return [
    wrap("header", 150, 57, "langame-logo.svg", light,
      '<rect width="150" height="57" fill="#FFFFFF"/>\n'
      + logo(light, { prefix: "header", x: 6, y: 18, width: 138, height: 21 })),
    wrap("sidebar", 164, 314, "langame-logo-dark.svg", dark,
      '<rect width="164" height="314" fill="#181818"/>\n'
      + logo(dark, { prefix: "symbol", x: 24, y: 68, width: 116, height: 54, iconOnly: true })
      + '\n<path d="M18 242H146" stroke="#3A3A3A" stroke-width="1"/>\n'
      + logo(dark, { prefix: "signature", x: 15, y: 266, width: 134, height: 21 })),
  ];
}

function renderDocument(sources) {
  return `<!doctype html><meta charset="utf-8"><title>LGSM installer branding</title>`
    + sources.map((source) => `<img id="${source.name}" width="${source.width}" height="${source.height}" src="data:image/svg+xml;base64,${Buffer.from(source.svg).toString("base64")}">`).join("")
    + `<pre id="result"></pre><script>addEventListener("load", () => {
      try {
        const images = ${JSON.stringify(sources.map(({ name, width, height }) => ({ name, width, height })))};
        const canvases = images.map(item => {
          const image = document.getElementById(item.name);
          if (!image.complete || image.naturalWidth !== item.width || image.naturalHeight !== item.height) throw new Error("SVG did not render at its native size");
          const canvas = document.createElement("canvas"); canvas.width = item.width; canvas.height = item.height;
          const context = canvas.getContext("2d", {colorSpace:"srgb"}); context.drawImage(image,0,0);
          const bytes = context.getImageData(0,0,item.width,item.height).data;
          let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte);
          return {...item, canvas, rgba: btoa(binary)};
        });
        const preview = document.createElement("canvas"); preview.width=1002; preview.height=990;
        const context = preview.getContext("2d"); context.fillStyle="#DCDCDC"; context.fillRect(0,0,1002,990);
        context.imageSmoothingEnabled=false;
        context.drawImage(canvases[1].canvas,18,24,492,942);
        context.drawImage(canvases[0].canvas,534,24,450,171);
        document.getElementById("result").textContent = JSON.stringify({
          renderer:navigator.userAgent, images:canvases.map(({canvas,...item})=>item), preview:preview.toDataURL("image/png").split(",")[1]
        });
      } catch (error) { document.getElementById("result").textContent=JSON.stringify({error:String(error)}); }
    });</script>`;
}

async function runBrowser(executable, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(executable, args, { windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "", stderr = "", failure;
    function stop(error) {
      failure = error;
      if (child.pid && child.exitCode === null && child.signalCode === null) {
        try {
          if (process.platform === "win32") execFileSync("taskkill.exe", ["/PID", String(child.pid), "/T", "/F"], {windowsHide:true, timeout:5000, stdio:"ignore"});
          else child.kill("SIGKILL");
        } catch (cleanupError) { failure = new AggregateError([error, cleanupError], "Renderer and owned-process cleanup failed"); }
      }
    }
    const timer = setTimeout(() => stop(new Error("Branding renderer exceeded 30 seconds")), 30000);
    child.stdout.setEncoding("utf8"); child.stderr.setEncoding("utf8");
    child.stdout.on("data", chunk => { stdout += chunk; if (stdout.length > 2 * 1024 * 1024) stop(new Error("Renderer output limit exceeded")); });
    child.stderr.on("data", chunk => { stderr = (stderr + chunk).slice(-64 * 1024); });
    child.once("error", error => { clearTimeout(timer); reject(error); });
    child.once("close", code => {
      clearTimeout(timer);
      if (failure || code !== 0) reject(failure || new Error(`Renderer exited ${code}: ${stderr}`));
      else resolve(stdout);
    });
  });
}

function encodeBitmap(width, height, pixels) {
  assert.equal(pixels.length, width * height * 4);
  const rowSize = Math.ceil(width * 3 / 4) * 4;
  const bitmap = Buffer.alloc(54 + rowSize * height);
  bitmap.write("BM"); bitmap.writeUInt32LE(bitmap.length, 2); bitmap.writeUInt32LE(54, 10);
  bitmap.writeUInt32LE(40, 14); bitmap.writeInt32LE(width, 18); bitmap.writeInt32LE(height, 22);
  bitmap.writeUInt16LE(1, 26); bitmap.writeUInt16LE(24, 28); bitmap.writeUInt32LE(rowSize * height, 34);
  bitmap.writeInt32LE(3780, 38); bitmap.writeInt32LE(3780, 42);
  for (let y=0; y<height; y++) for (let x=0; x<width; x++) {
    const from=(y*width+x)*4, to=54+(height-y-1)*rowSize+x*3;
    assert.equal(pixels[from+3], 255, "NSIS artwork must have an opaque background");
    bitmap[to]=pixels[from+2]; bitmap[to+1]=pixels[from+1]; bitmap[to+2]=pixels[from];
  }
  return bitmap;
}

async function main() {
  const options = parseArguments();
  await fs.mkdir(options.workDir, {recursive:true});
  const scratch = path.join(options.workDir, `installer-branding-render-${randomUUID()}`);
  await fs.mkdir(scratch);
  try {
    const sources = await makeSources();
    const document = path.join(scratch, "render.html");
    await fs.writeFile(document, renderDocument(sources));
    const stdout = await runBrowser(await browserExecutable(options.browser), [
      "--headless=new", "--disable-gpu", "--disable-background-networking", "--disable-component-update",
      "--no-first-run", "--no-default-browser-check", "--force-color-profile=srgb", "--dump-dom",
      `--user-data-dir=${path.join(scratch,"profile")}`, pathToFileURL(document).href,
    ]);
    const match = stdout.match(/<pre id="result">([^<]+)<\/pre>/);
    assert.ok(match, "Browser did not return a rendered branding result");
    const result = JSON.parse(match[1].replaceAll("&quot;", '"').replaceAll("&amp;", "&"));
    assert.equal(result.error, undefined);
    assert.equal(result.images.length, sources.length);
    if (!options.check) await fs.mkdir(brandingRoot, {recursive:true});
    for (const source of sources) {
      const rendered = result.images.find(image => image.name===source.name);
      assert.equal(rendered.width, source.width); assert.equal(rendered.height, source.height);
      const bitmap = encodeBitmap(source.width, source.height, Buffer.from(rendered.rgba,"base64"));
      for (const [extension, bytes] of [["svg",Buffer.from(source.svg)], ["bmp",bitmap]]) {
        const destination=path.join(brandingRoot,`${source.name}.${extension}`);
        if (options.check) assert.ok((await fs.readFile(destination)).equals(bytes), `${source.name}.${extension} is stale; regenerate with the same Chromium renderer`);
        else await fs.writeFile(destination,bytes);
      }
    }
    await fs.writeFile(path.join(options.workDir,"installer-branding-preview.png"),Buffer.from(result.preview,"base64"));
    await fs.writeFile(path.join(options.workDir,"installer-branding-renderer.json"),JSON.stringify({renderer:result.renderer,dimensions:sources.map(({name,width,height})=>({name,width,height}))},null,2)+"\n");
    console.log(`${options.check ? "Verified" : "Generated"} NSIS header 150x57 and sidebar 164x314 (opaque 24-bit BMP).`);
  } finally {
    assert.equal(path.dirname(scratch),options.workDir);
    assert.ok(path.basename(scratch).startsWith("installer-branding-render-"));
    assert.equal((await fs.lstat(scratch)).isSymbolicLink(),false);
    await fs.rm(scratch,{recursive:true,force:false,maxRetries:5,retryDelay:100});
  }
}

main().catch(error => { console.error(error); process.exitCode=1; });
