export const CONAN_EXACT_SECTION_KEYS: Record<string, readonly string[]> = {
  "access": [
    "enable_ban_check",
    "validate_player_stats",
    "region_allow_africa",
    "region_allow_asia",
    "region_allow_central_europe",
    "region_allow_eastern_europe",
    "region_allow_western_europe",
    "region_allow_north_america",
    "region_allow_oceania",
    "region_allow_south_america",
    "kick_afk_percentage",
    "kick_afk_time",
  ],
  "world": [
    "clan_max_size",
    "max_nudity",
    "enable_clan_markers",
    "npc_respawn_multiplier",
    "player_movement_speed_scale",
    "player_sprint_speed_scale",
    "dogs_of_the_desert_spawn_with_dogs",
    "cross_desert_once",
    "creative_mode_server",
    "max_death_map_markers",
    "event_system_enabled",
    "healthbar_visibility_distance",
  ],
  "rates": [
    "disabled_knowledge_ids",
    "avatar_dome_duration_multiplier",
    "npc_max_spawn_cap_multiplier",
  ],
  "combat": [
    "shield_durability_multiplier",
    "npc_health_multiplier",
    "max_aggro_range",
    "avatar_dome_damage_multiplier",
    "combat_mode_modifier",
    "enable_target_lock",
    "allowed_time_undermesh",
  ],
  "network": [
    "max_allowed_ping",
    "disconnection_grace_time",
  ],
  "pvp_schedule": [
    "building_pvp_allowed_structure_ids",
    "pvp_mount_endurance_damage_multiplier",
    "pvp_build_from_storage_radius",
    "pvp_time_monday_start",
    "pvp_time_tuesday_start",
    "pvp_time_wednesday_start",
    "pvp_time_thursday_start",
    "pvp_time_friday_start",
    "pvp_time_saturday_start",
    "pvp_time_sunday_start",
    "pvp_time_monday_end",
    "pvp_time_tuesday_end",
    "pvp_time_wednesday_end",
    "pvp_time_thursday_end",
    "pvp_time_friday_end",
    "pvp_time_saturday_end",
    "pvp_time_sunday_end",
    "pvp_enabled_monday",
    "pvp_enabled_tuesday",
    "pvp_enabled_wednesday",
    "pvp_enabled_thursday",
    "pvp_enabled_friday",
    "pvp_enabled_saturday",
    "pvp_enabled_sunday",
    "pvp_building_damage_time_monday_start",
    "pvp_building_damage_time_tuesday_start",
    "pvp_building_damage_time_wednesday_start",
    "pvp_building_damage_time_thursday_start",
    "pvp_building_damage_time_friday_start",
    "pvp_building_damage_time_saturday_start",
    "pvp_building_damage_time_sunday_start",
    "pvp_building_damage_time_monday_end",
    "pvp_building_damage_time_tuesday_end",
    "pvp_building_damage_time_wednesday_end",
    "pvp_building_damage_time_thursday_end",
    "pvp_building_damage_time_friday_end",
    "pvp_building_damage_time_saturday_end",
    "pvp_building_damage_time_sunday_end",
    "pvp_building_damage_enabled_monday",
    "pvp_building_damage_enabled_tuesday",
    "pvp_building_damage_enabled_wednesday",
    "pvp_building_damage_enabled_thursday",
    "pvp_building_damage_enabled_friday",
    "pvp_building_damage_enabled_saturday",
    "pvp_building_damage_enabled_sunday",
    "disable_building_during_time_restricted_pvp",
    "restrict_avatar_summoning_time",
    "avatar_summoning_time_weekday_start",
    "avatar_summoning_time_weekday_end",
    "avatar_summoning_time_weekend_start",
    "avatar_summoning_time_weekend_end",
    "avatar_summon_time",
  ],
  "followers": [
    "minion_damage_multiplier",
    "minion_damage_taken_multiplier",
    "thrall_exclusion_radius",
    "thrall_scouting_time_minutes",
    "thrall_min_distance_away_from_home",
    "thrall_teleporting_cooldown",
    "enable_follower_dbno",
    "enable_follower_rescue_on_land_claim_only",
    "enable_follower_rescue_in_build_exclusion_zone",
    "follower_rescue_cooldown",
    "damage_cooldown_before_rescue",
    "thrall_corruption_removal_multiplier",
    "animal_pen_crafting_time_multiplier",
    "feed_box_range_multiplier",
    "path_following_sends_angular_velocity",
    "unconscious_time_seconds",
    "conciousness_damage_multiplier",
    "thrall_damage_to_npcs_multiplier",
    "thrall_decay_time",
    "disable_thrall_decay",
  ],
  "building": [
    "enable_building_destruction_capsules",
    "structure_damage_multiplier",
    "camps_ignore_landclaim",
    "land_claim_radius_multiplier",
    "disable_landclaim_notifications",
    "building_preload_radius",
    "dynamic_building_damage",
    "dynamic_building_damage_period",
    "disable_building_abandonment",
    "max_building_decay_time",
    "override_decay_max_building_pieces",
    "override_decay_time",
    "max_decay_time_to_auto_demolish",
    "building_decay_time_per_score",
    "decay_cleanup_time_multiplier",
    "decay_bonus_time_rate",
    "decay_show_building_score",
    "building_pickup_enabled",
    "poi_protection_enabled",
    "stability_loss_multiplier",
    "building_validation_enabled",
    "allow_building_anywhere",
  ],
  "survival": [
    "player_water_multiplier",
    "player_offline_thirst_multiplier",
    "player_offline_hunger_multiplier",
    "offline_players_unconscious_bodies_hours",
    "player_encumbrance_multiplier",
    "player_encumbrance_penalty_multiplier",
    "player_stamina_cost_sprint_multiplier",
    "action_stamina_cost_multiplier",
    "player_health_regen_speed_scale",
    "drop_equipment_on_death",
    "corpses_per_player",
    "player_corpse_life_time",
    "npc_corpse_life_time",
    "item_repair_minimum_durability",
    "item_repair_durability_loss_by_repairkit_tier",
    "item_repair_durability_loss_penalty_chance",
    "item_convertion_multiplier",
    "stamina_regeneration_time",
    "stamina_exhaustion_time",
    "stamina_static_regen_rate_multiplier",
    "stamina_moving_regen_rate_multiplier",
    "player_stamina_regen_speed_scale",
    "stamina_on_consume_regen_pause",
    "stamina_on_exhaustion_regen_pause",
    "player_corruption_gain_multiplier",
    "player_corruption_gain_from_sorcery_multiplier",
  ],
  "transfer": [
    "server_transfer_enabled",
    "server_transfer_allowed_servers",
    "server_merge_outgoing_time",
    "server_merge_destination",
  ],
  "advanced": [
    "local_nav_mesh_visualization_frequency",
    "local_land_claim_visualization_frequency",
    "local_land_claim_visualization_radius",
    "local_land_claim_visualization_channel",
    "use_local_quadratic_angular_velocity_prediction",
    "lqavp_use_time",
    "lqavp_fade_time",
    "lqavp_method",
    "network_simulated_smooth_rotation_time_with_lqavp",
    "cap_character_layout_scalar_params",
  ],
};

export const CONAN_DOCUMENTED_GROUPS = [
  {
    "id": "maelstrom",
    "section": "world",
    "title": "Maelstrom Weather",
    "keys": [
      "storm_enabled",
      "storm_time_weekday_start",
      "storm_time_weekday_end",
      "storm_time_weekend_start",
      "storm_time_weekend_end",
      "storm_cooldown",
      "storm_accumulation_time",
      "storm_duration",
      "storm_dissipation_time",
      "storm_minimum_online_players",
      "storm_map_blocker",
      "storm_endurance_drain_multiplier"
    ]
  },
  {
    "id": "elder_things",
    "section": "world",
    "title": "Maelstrom Creatures",
    "keys": [
      "elder_things_enabled",
      "elder_things_idle_lifespan",
      "elder_thing_spawn_rate",
      "max_ambush_elder_things",
      "siege_elder_things_enabled",
      "max_siege_elder_things",
      "siege_elder_thing_respawn_rate",
      "siege_elder_thing_map_markers"
    ]
  },
  {
    "id": "siptah_events",
    "section": "world",
    "title": "Siptah Events & Vaults",
    "keys": [
      "surge_despawn_timer",
      "surge_sacrifice_requirement_multiplier",
      "altar_module_active_time_multiplier",
      "vault_refresh_time",
      "vault_refresh_deviation"
    ]
  },
  {
    "id": "storm_building",
    "section": "building",
    "title": "Maelstrom & Siege Damage",
    "keys": [
      "storm_building_allowed",
      "storm_building_damage_enabled",
      "storm_building_damage_multiplier",
      "storm_building_damage_rate_multiplier",
      "minimum_storm_damage_building_pieces",
      "minimum_building_size_to_be_sieged",
      "elder_thing_siege_building_size_multiplier",
      "elder_thing_siege_damage_multiplier"
    ]
  },
  {
    "id": "player_needs",
    "section": "survival",
    "title": "Hunger, Thirst & Offline Bodies",
    "keys": [
      "player_active_hunger_multiplier",
      "player_active_thirst_multiplier",
      "player_idle_hunger_multiplier",
      "player_idle_thirst_multiplier",
      "logout_characters_remain_in_the_world"
    ]
  },
  {
    "id": "persistence",
    "section": "advanced",
    "title": "World Loading",
    "keys": [
      "is_load_errors_fatal"
    ]
  }
] as const;
