import { arkCatalogSearchAliases } from "./gm-catalog-i18n";

export interface ArkGmCreatureOption {
  value: string;
  label: string;
  name: string;
  category: string;
}

type ArkGmCreatureTuple = readonly [name: string, classId: string];

const ARK_GM_CREATURE_TUPLES: ArkGmCreatureTuple[] = [
  ["Aberrant Achatina", "Achatina_Character_BP_Aberrant_C"],
  ["Aberrant Anglerfish", "Angler_Character_BP_Aberrant_C"],
  ["Aberrant Ankylosaurus", "Ankylo_Character_BP_Aberrant_C"],
  ["Aberrant Araneo", "SpiderS_Character_BP_Aberrant_C"],
  ["Aberrant Arthropluera", "Arthro_Character_BP_Aberrant_C"],
  ["Aberrant Baryonyx", "Baryonyx_Character_BP_Aberrant_C"],
  ["Aberrant Beelzebufo", "Toad_Character_BP_Aberrant_C"],
  ["Aberrant Carbonemys", "Turtle_Character_BP_Aberrant_C"],
  ["Aberrant Carnotaurus", "Carno_Character_BP_Aberrant_C"],
  ["Aberrant Cnidaria", "Cnidaria_Character_BP_Aberrant_C"],
  ["Aberrant Coelacanth", "Coel_Character_BP_Aberrant_C"],
  ["Aberrant Dimetrodon", "Dimetro_Character_BP_Aberrant_C"],
  ["Aberrant Dimorphodon", "Dimorph_Character_BP_Aberrant_C"],
  ["Aberrant Diplocaulus", "Diplocaulus_Character_BP_Aberrant_C"],
  ["Aberrant Diplodocus", "Diplodocus_Character_BP_Aberrant_C"],
  ["Aberrant Direbear", "Direbear_Character_BP_Aberrant_C"],
  ["Aberrant Dodo", "Dodo_Character_BP_Aberrant_C"],
  ["Aberrant Doedicurus", "Doed_Character_BP_Aberrant_C"],
  ["Aberrant Dung Beetle", "DungBeetle_Character_BP_Aberrant_C"],
  ["Aberrant Electrophorus", "Eel_Character_BP_Aberrant_C"],
  ["Aberrant Equus", "Equus_Character_BP_Aberrant_C"],
  ["Aberrant Fasolasuchus", "Fasola_Character_BP_Aberrant_C"],
  ["Aberrant Gigantopithecus", "Bigfoot_Character_BP_Aberrant_C"],
  ["Aberrant Gigantoraptor", "Gigantoraptor_Character_BP_Aberrant_C"],
  ["Aberrant Iguanodon", "Iguanodon_Character_BP_Aberrant_C"],
  ["Aberrant Lystrosaurus", "Lystro_Character_BP_Aberrant_C"],
  ["Aberrant Manta", "Manta_Character_BP_Aberrant_C"],
  ["Aberrant Megalania", "Megalania_Character_BP_Aberrant_C"],
  ["Aberrant Megalosaurus", "Megalosaurus_Character_BP_Aberrant_C"],
  ["Aberrant Meganeura", "Dragonfly_Character_BP_Aberrant_C"],
  ["Aberrant Moschops", "Moschops_Character_BP_Aberrant_C"],
  ["Aberrant Otter", "Otter_Character_BP_Aberrant_C"],
  ["Aberrant Oviraptor", "Oviraptor_Character_BP_Aberrant_C"],
  ["Aberrant Ovis", "Sheep_Character_BP_Aberrant_C"],
  ["Aberrant Paraceratherium", "Paracer_Character_BP_Aberrant_C"],
  ["Aberrant Parasaur", "Para_Character_BP_Aberrant_C"],
  ["Aberrant Piranha", "Piranha_Character_BP_Aberrant_C"],
  ["Aberrant Pulmonoscorpius", "Scorpion_Character_BP_Aberrant_C"],
  ["Aberrant Purlovia", "Purlovia_Character_BP_Aberrant_C"],
  ["Aberrant Raptor", "Raptor_Character_BP_Aberrant_C"],
  ["Aberrant Salmon", "Salmon_Character_Aberrant_C"],
  ["Aberrant Sarco", "Sarco_Character_BP_Aberrant_C"],
  ["Aberrant Spino", "Spino_Character_BP_Aberrant_C"],
  ["Aberrant Stegosaurus", "Stego_Character_BP_Aberrant_C"],
  ["Aberrant Titanoboa", "BoaFrill_Character_BP_Aberrant_C"],
  ["Aberrant Triceratops", "Trike_Character_BP_Aberrant_C"],
  ["Aberrant Trilobite", "Trilobite_Character_Aberrant_C"],
  ["Abyssal Ankylosaurus", "Ankylo_Character_BP_Abyssal_C"],
  ["Abyssal Ankylosaurus (Rift)", "Ankylo_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Moschops", "Moschops_Character_BP_Abyssal_C"],
  ["Abyssal Moschops (Rift)", "Moschops_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Procoptodon", "Procoptodon_Character_BP_Abyssal_C"],
  ["Abyssal Procoptodon (Rift)", "Procoptodon_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Reaper King", "Reaper_Character_BP_Male_Abyssal_C"],
  ["Abyssal Reaper Offspring", "Reaper_Character_BP_Offspring_Abyssal_C"],
  ["Abyssal Reaper Queen", "Reaper_Character_BP_Female_Abyssal_C"],
  ["Abyssal Rex", "Rex_Character_BP_Abyssal_C"],
  ["Abyssal Rex (Rift)", "Rex_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Stegosaurus", "Stego_Character_BP_Abyssal_C"],
  ["Abyssal Stegosaurus (Rift)", "Stego_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Therizinosaur", "Therizino_Character_BP_Abyssal_C"],
  ["Abyssal Therizinosaur (Rift)", "Therizino_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Thylacoleo", "Thylacoleo_Character_BP_Abyssal_C"],
  ["Abyssal Thylacoleo (Rift)", "Thylacoleo_Character_BP_Abyssal_Rift_C"],
  ["Abyssal Yutyrannus", "Yutyrannus_Character_BP_Abyssal_C"],
  ["Abyssal Yutyrannus (Rift)", "Yutyrannus_Character_BP_Abyssal_Rift_C"],
  ["Achatina", "Achatina_Character_BP_C"],
  ["Allosaurus", "Allo_Character_BP_C"],
  ["Alpha Abyssal Rex", "MegaRex_Character_BP_Abyssal_C"],
  ["Alpha Abyssal Rex (Rift)", "MegaRex_Character_BP_Abyssal_Rift_C"],
  ["Alpha Araneo Boss Minion", "SpiderS_Character_BP_Aggressive_Hard_C"],
  ["Alpha Attack Drone", "EndDrone_Character_BP_Hard_C"],
  ["Alpha Basilisk", "MegaBasilisk_Character_BP_C"],
  ["Alpha Blood Crystal Wyvern", "CrystalWyvern_Character_BP_Mega_C"],
  ["Alpha Broodmother Lysrix", "SpiderL_Character_BP_Hard_C"],
  ["Alpha Broodmother Lysrix (The Center)", "SpiderL_Character_BP_TheCenterHard_C"],
  ["Alpha Carno", "MegaCarno_Character_BP_C"],
  ["Alpha Chrysaora", "MegaChrysaora_Character_BP_C"],
  ["Alpha Crystal Wyvern Queen", "CrystalWyvern_Character_BP_Boss_Hard_C"],
  ["Alpha Dakosaurus", "Dakosaurus_Character_BP_Alpha_C"],
  ["Alpha Dakosaurus (Rift)", "MegaDakosaurus_Character_BP_Rift_C"],
  ["Alpha Deathworm", "MegaDeathworm_Character_BP_C"],
  ["Alpha Defense Unit", "EndTank_Character_BP_Hard_C"],
  ["Alpha Dimorphodon Boss Minion", "Dimorph_Character_BP_Aggressive_DragonBoss_Hard_C"],
  ["Alpha Dragon", "Dragon_Character_BP_Boss_Hard_C"],
  ["Alpha Dragon (Ragnarok)", "Dragon_Character_BP_Boss_Hard_Ragnarok_C"],
  ["Alpha Fire Wyvern", "MegaWyvern_Character_BP_Fire_C"],
  ["Alpha Gigantopithecus Boss Minion", "Bigfoot_Character_BP_Aggressive_Hard_C"],
  ["Alpha Karkinos", "MegaCrab_Character_BP_C"],
  ["Alpha King Titan", "KingKaiju_Character_BP_Alpha_C"],
  ["Alpha Leedsichthys", "Alpha_Leedsichthys_Character_BP_C"],
  ["Alpha Malleocephalus", "MegaMalleocephalus_Character_BP_C"],
  ["Alpha Manticore", "Manticore_Character_BP_Hard_C"],
  ["Alpha Manticore (Ragnarok)", "Manticore_Character_BP_Hard_Ragnarok_C"],
  ["Alpha Megalodon", "MegaMegalodon_Character_BP_C"],
  ["Alpha Megalodon (Rift)", "MEgaMegalodon_Character_BP_Rift_C"],
  ["Alpha Megapithecus", "Gorilla_Character_BP_Hard_C"],
  ["Alpha Megapithecus (The Center)", "Gorilla_Character_BP_TheCenter_Hard_C"],
  ["Alpha Mesopithecus Boss Minion", "Monkey_Character_BP_Aggressive_Hard_C"],
  ["Alpha Mosasaur (Rift)", "Mosa_Character_BP_Mega_Rift_C"],
  ["Alpha Mosasaurus", "Mosa_Character_BP_Mega_C"],
  ["Alpha Pteranodon Boss Minion", "Ptero_Minion_Character_Hard_C"],
  ["Alpha Raptor", "MegaRaptor_Character_BP_C"],
  ["Alpha Rex", "MegaRex_Character_BP_C"],
  ["Alpha Surface Reaper King", "MegaXenomorph_Character_BP_Male_Surface_C"],
  ["Alpha Tridacna (Blue)", "AlphaCorruptTridacna_Character_BP_Blue_C"],
  ["Alpha Tridacna (Green)", "AlphaCorruptTridacna_Character_BP_Green_C"],
  ["Alpha Tridacna (Red)", "AlphaCorruptTridacna_Character_BP_Red_C"],
  ["Alpha Tusoteuthis", "Mega_Tusoteuthis_Character_BP_C"],
  ["Alpha Tusoteuthis (Rift)", "Mega_Tusoteuthis_Character_BP_Rift_C"],
  ["Alpha Water Wyvern", "MegaWyvern_Character_BP_Water_C"],
  ["Alpha Water Wyvern (Rift)", "MegaWyvern_Character_BP_Water_Rift_C"],
  ["Alpha X-Triceratops", "Volcano_Trike_Character_BP_Retrieve_Alpha_C"],
  ["Amargasaurus", "Amargasaurus_Character_BP_C"],
  ["Amargasaurus Minion", "Amargasaurus_Character_BP_Minion_C"],
  ["Ammonite", "Ammonite_Character_C"],
  ["Andrewsarchus", "Andrewsarchus_Character_BP_C"],
  ["Anglerfish", "Angler_Character_BP_C"],
  ["Anglerfish (Escort)", "Angler_Character_BP_Escort_C"],
  ["Anglerfish (Rift)", "Angler_Character_BP_Rift_C"],
  ["Ankylosaurus", "Ankylo_Character_BP_C"],
  ["Any Insect", "Insect_Character_Base_C"],
  ["Any Titanomyrma", "Ant_Character_Base_C"],
  ["Araneo", "SpiderS_Character_BP_C"],
  ["Araneo (Gauntlet)", "SpiderS_Character_BP_Gauntlet_C"],
  ["Araneo (Retrieve)", "SpiderS_Character_BP_Retrieve_C"],
  ["Archaeopteryx", "Archa_Character_BP_C"],
  ["Archelon", "Archelon_Character_BP_ASA_C"],
  ["Argentavis", "Argent_Character_BP_C"],
  ["Argentavis (Mashup)", "Argent_Character_BP_ExpG_Pod_C"],
  ["Argentavis (Retrieve)", "Argent_Character_BP_Retrieve_C"],
  ["Armadoggo", "Doggo_Character_BP_C"],
  ["Arthropluera", "Arthro_Character_BP_C"],
  ["Arthropluera (Gauntlet)", "Arthro_Character_BP_Gauntlet_C"],
  ["Arthropluera (Mashup)", "Arthro_Character_BP_ExpG_C"],
  ["Arthropluera (Retrieve)", "Arthro_Character_BP_Retrieve_C"],
  ["Astrocetus", "SpaceWhale_Character_BP_C"],
  ["Astrocetus (Whale Rescue)", "SpaceWhale_Character_BP_WhaleRescue_C"],
  ["Astrodelphis", "SpaceDolphin_Character_BP_C"],
  ["Astrodelphis (Race)", "SpaceDolphin_Character_BP_Race_C"],
  ["Astrodelphis (Whale Rescue Bot)", "SpaceDolphin_Character_BP_WhaleRescue_Bot_C"],
  ["Astrodelphis (Whale Rescue)", "SpaceDolphin_Character_BP_WhaleRescue_C"],
  ["Attack Drone (Gauntlet)", "EndDrone_Character_BP_Gauntlet_C"],
  ["Attack Drone (Whale Rescue No Follow)", "EndDrone_Character_BP_WhaleRescue_NoFollow_C"],
  ["Attack Drone (Whale Rescue Passive Spline Formation)", "EndDrone_Character_BP_WhaleRescue_PassiveSplineFormation_C"],
  ["Attack Drone (Whale Rescue Slow Aggressive)", "EndDrone_Character_BP_WhaleRescue_SlowAggressive_C"],
  ["Attack Drone (Whale Rescue)", "EndDrone_Character_BP_WhaleRescue_C"],
  ["Baryonyx", "Baryonyx_Character_BP_C"],
  ["Baryonyx (Escort)", "Baryonyx_Character_BP_Escort_C"],
  ["Baryonyx (Gauntlet)", "Baryonyx_Character_BP_Gauntlet_C"],
  ["Baryonyx (Hunt)", "Baryonyx_Character_BP_Hunt_C"],
  ["Baryonyx (Rift)", "Baryonyx_Character_BP_Rift_C"],
  ["Basilisk", "Basilisk_Character_BP_C"],
  ["Basilisk (Hunt)", "Basilisk_Character_BP_Hunt_C"],
  ["Basilisk (Retrieve)", "Basilisk_Character_BP_Retrieve_C"],
  ["Basilisk Ghost", "Ghost_Basilisk_Character_BP_C"],
  ["Basilosaurus", "Basilosaurus_Character_BP_C"],
  ["Basilosaurus (Rift)", "Basilosaurus_Character_BP_Rift_C"],
  ["Beelzebufo", "Toad_Character_BP_C"],
  ["Beelzebufo (Escort)", "Toad_Character_BP_Escort_C"],
  ["Beelzebufo (Gauntlet)", "Toad_Character_BP_Gauntlet_C"],
  ["Beta Araneo Boss Minion", "SpiderS_Character_BP_Aggressive_Med_C"],
  ["Beta Attack Drone", "EndDrone_Character_BP_Med_C"],
  ["Beta Broodmother Lysrix", "SpiderL_Character_BP_Medium_C"],
  ["Beta Broodmother Lysrix (The Center)", "SpiderL_Character_BP_TheCenterMedium_C"],
  ["Beta Crystal Wyvern Queen", "CrystalWyvern_Character_BP_Boss_Medium_C"],
  ["Beta Defense Unit", "EndTank_Character_BP_Med_C"],
  ["Beta Dimorphodon Boss Minion", "Dimorph_Character_BP_Aggressive_DragonBoss_Med_C"],
  ["Beta Dragon", "Dragon_Character_BP_Boss_Medium_C"],
  ["Beta Dragon (Ragnarok)", "Dragon_Character_BP_Boss_Medium_Ragnarok_C"],
  ["Beta Gigantopithecus Boss Minion", "Bigfoot_Character_BP_Aggressive_Med_C"],
  ["Beta King Titan", "KingKaiju_Character_BP_Beta_C"],
  ["Beta Manticore", "Manticore_Character_BP_Medium_C"],
  ["Beta Manticore (Ragnarok)", "Manticore_Character_BP_Medium_Ragnarok_C"],
  ["Beta Megapithecus", "Gorilla_Character_BP_Medium_C"],
  ["Beta Megapithecus (The Center)", "Gorilla_Character_BP_TheCenter_Medium_C"],
  ["Beta Mesopithecus Boss Minion", "Monkey_Character_BP_Aggressive_Med_C"],
  ["Beta Pteranodon Boss Minion", "Ptero_Minion_Character_Med_C"],
  ["Beyla", "Beyla_Character_BP_C"],
  ["Beyla Minion", "BeylaMinion_Character_BP_C"],
  ["Bloodstalker", "BogSpider_Character_BP_C"],
  ["Bloodstalker (Gauntlet)", "BogSpider_Character_BP_Gauntlet_C"],
  ["Bloodstalker (Race)", "BogSpider_Character_BP_Race_C"],
  ["Bone Fire Wyvern", "Bone_MegaWyvern_Character_BP_Fire_C"],
  ["Brontosaurus", "Sauropod_Character_BP_C"],
  ["Broodmother Guardian", "EndBossSpiderL_Character_BP_C"],
  ["Broodmother Lysrix", "SpiderL_Character_BP_C"],
  ["Broodmother Lysrix (Gauntlet)", "SpiderL_Character_BP_Gauntlet_C"],
  ["Broodmother Lysrix (Valguero)", "SpiderL_VAL_Character_BP_C"],
  ["Broodmother Lysrix Alpha", "EndBossSpiderL_Character_BP_Hard_C"],
  ["Broodmother Lysrix Alpha (Fjordur)", "SpiderL_Character_BP_Hard_FJ_C"],
  ["Broodmother Lysrix Beta", "EndBossSpiderL_Character_BP_Medium_C"],
  ["Broodmother Lysrix Beta (Fjordur)", "SpiderL_Character_BP_Medium_FJ_C"],
  ["Broodmother Lysrix Gamma", "EndBossSpiderL_Character_BP_Easy_C"],
  ["Broodmother Lysrix Gamma (Fjordur)", "SpiderL_Character_BP_Easy_FJ_C"],
  ["Brute Araneo", "SpiderS_Character_BP_Hunt_C"],
  ["Brute Astrocetus", "SpaceWhale_Character_BP_Brute_C"],
  ["Brute Basilosaurus", "Basilosaurus_Character_BP_Hunt_C"],
  ["Brute Bloodstalker", "BogSpider_Character_BP_Hunt_C"],
  ["Brute Ferox", "Shapeshifter_Large_Character_BP_Hunt_C"],
  ["Brute Ferox (Gen2)", "Shapeshifter_Large_Character_BP_Hunt_Gen2_C"],
  ["Brute Fire Wyvern", "Wyvern_Character_BP_Fire_GauntletBoss_C"],
  ["Brute Leedsichthys", "Leedsichthys_Character_BP_Hunt_C"],
  ["Brute Magmasaur", "Cherufe_Character_BP_Hunt_C"],
  ["Brute Malfunctioned Tek Giganotosaurus", "BionicGigant_Character_BP_Malfunctioned_Hunt_C"],
  ["Brute Malfunctioned Tek Rex", "BionicRex_Character_BP_Malfunctioned_Hunt_C"],
  ["Brute Mammoth", "Mammoth_Character_BP_Hunt_C"],
  ["Brute Megaloceros", "Stag_Character_BP_Hunt_C"],
  ["Brute Megaloceros (Mega)", "Stag_Character_BP_Hunt_Mega_C"],
  ["Brute Plesiosaur", "Plesiosaur_Character_BP_Hunt_C"],
  ["Brute Reaper King", "Xenomorph_Character_BP_Male_InitialBuryOnly_Hunt_C"],
  ["Brute Sarco", "Sarco_Character_BP_Hunt_C"],
  ["Brute Seeker", "Pteroteuthis_Char_BP_HuntFollower_C"],
  ["Brute Tusoteuthis", "Tusoteuthis_Character_BP_Hunt_C"],
  ["Brute X-Allosaurus", "Volcano_Allo_Character_BP_Hunt_C"],
  ["Brute X-Megalodon", "Ocean_Megalodon_Character_BP_Hunt_C"],
  ["Brute X-Mosasaurus", "Ocean_Mosa_Character_BP_Hunt_C"],
  ["Brute X-Raptor", "Bog_Raptor_Character_BP_Hunt_C"],
  ["Brute X-Raptor (Hunt)", "Bog_Raptor_Character_BP_C"],
  ["Brute X-Rex", "Volcano_Rex_Character_BP_Hunt_C"],
  ["Brute X-Rock Elemental", "Volcano_Golem_Character_BP_Hunt_C"],
  ["Brute X-Spino", "Bog_Spino_Character_BP_Hunt_C"],
  ["Brute X-Yutyrannus", "Snow_Yutyrannus_Character_BP_Hunt_C"],
  ["Bulbdog", "LanternPug_Character_BP_C"],
  ["Bulbdog (Escort)", "LanternPug_Character_BP_Escort_C"],
  ["Bulbdog (Gauntlet)", "LanternPug_Character_BP_Gauntlet_C"],
  ["Bulbdog (Hunt)", "LanternPug_Character_BP_Hunt_C"],
  ["Bulbdog (Sport)", "LanternPug_Character_BP_Basketball_C"],
  ["Bulbdog Ghost", "Ghost_LanternPug_Character_BP_C"],
  ["Bunny Oviraptor", "BunnyOviraptor_Character_BP_C"],
  ["BunnyDodo", "Dodo_Character_BP_Bunny_C"],
  ["Canoe", "Canoe_BP_C"],
  ["Canoe (Alpha)", "Canoe_BP_Race_Alpha_C"],
  ["Canoe (Alpha) (Team Race)", "Canoe_BP_TeamRace_Alpha_C"],
  ["Canoe (Beta)", "Canoe_BP_Race_Beta_C"],
  ["Canoe (Beta) (Team Race)", "Canoe_BP_TeamRace_Beta_C"],
  ["Canoe (Gamma)", "Canoe_BP_Race_Gamma_C"],
  ["Canoe (Gamma) (Team Race)", "Canoe_BP_TeamRace_Gamma_C"],
  ["Canoe (Race)", "Canoe_BP_Race_C"],
  ["Canoe (Team Race)", "Canoe_BP_TeamRace_C"],
  ["Carbonemys", "Turtle_Character_BP_C"],
  ["Carbonemys (Escort)", "Turtle_Character_BP_Escort_C"],
  ["Carbonemys (Rift)", "Turtle_Character_BP_Rift_C"],
  ["Carcharodontosaurus", "Carcha_Character_BP_C"],
  ["Carnotaurus", "Carno_Character_BP_C"],
  ["Carnotaurus (Escort)", "Carno_Character_BP_Escort_C"],
  ["Carnotaurus (Gauntlet)", "Carno_Character_BP_Gauntlet_C"],
  ["Carnotaurus (Hunt)", "Carno_Character_BP_Hunt_C"],
  ["Carnotaurus (Hunt) (Minion)", "Carno_Character_BP_HuntFollower_C"],
  ["Carnotaurus (Retrieve)", "Carno_Character_BP_Retrieve_C"],
  ["Castoroides", "Beaver_Character_BP_C"],
  ["Castoroides (Gauntlet)", "Beaver_Character_BP_Gauntlet_C"],
  ["Castoroides (Rift)", "Beaver_Character_BP_Rift_C"],
  ["Cat", "CAT_Character_BP_C"],
  ["Cave Alpha Mosasaur", "Mosa_Character_BP_Mega_Cave_C"],
  ["Cave Mosasaurus", "Mosa_Character_BP_Cave_C"],
  ["Cave Tusoteuthis", "Tusoteuthis_Character_BP_Caves_C"],
  ["Ceratosaurus", "Ceratosaurus_Character_BP_ASA_C"],
  ["Chalicotherium", "Chalico_Character_BP_C"],
  ["Chalicotherium (Gauntlet)", "Chalico_Character_BP_Gauntlet_C"],
  ["Chalicotherium (Mashup)", "Chalico_Character_BP_ExpG_Pod_C"],
  ["Chalk Golem", "ChalkGolem_Character_BP_C"],
  ["Chrysaora", "Chrysaora_Character_BP_C"],
  ["Chrysaora (Rift)", "Chrysaora_Character_BP_Rift_C"],
  ["Chupacabra Minion", "ChupaCabra_Character_BP_Minion_C"],
  ["Cnidaria", "Cnidaria_Character_BP_C"],
  ["Cnidaria (Retrieve)", "Cnidaria_Character_BP_Retrieve_C"],
  ["Cnidaria (Rift)", "Cnidaria_Character_BP_Rift_C"],
  ["Coelacanth", "Coel_Character_BP_C"],
  ["Coelacanth (Ice Fishing Mission)", "Coel_Character_BP_IceFishMission_C"],
  ["Compy", "Compy_Character_BP_C"],
  ["Corrupt Arthropluera Boss Minion", "Corrupt_Arthro_Character_BP_C"],
  ["Corrupt Tumor", "CorruptTumor_Character_BP_C"],
  ["Corrupted Arthropluera", "Arthro_Character_BP_Corrupt_C"],
  ["Corrupted Avatar", "Bot_Character_BP_C"],
  ["Corrupted Avatar, With Bow", "Bot_WithBow_BP_C"],
  ["Corrupted Avatar, With Spear", "Bot_WithSpear_BP_C"],
  ["Corrupted Avatar, With Tek Grenades", "Bot_WithTekGrenades_BP_C"],
  ["Corrupted Avatar, With Tek Rifle", "Bot_WithTekRifle_BP_C"],
  ["Corrupted Carnotaurus", "Carno_Character_BP_Corrupt_C"],
  ["Corrupted Chalicotherium", "Chalico_Character_BP_Corrupt_C"],
  ["Corrupted Deathworm", "Deathworm_Character_BP_Corrupt_C"],
  ["Corrupted Dilophosaur", "Dilo_Character_BP_Corrupt_C"],
  ["Corrupted Dimorphodon", "Dimorph_Character_BP_Corrupt_C"],
  ["Corrupted Giganotosaurus", "Gigant_Character_BP_Corrupt_C"],
  ["Corrupted Master Controller (Alpha)", "VRMainBoss_Character_Hard_C"],
  ["Corrupted Master Controller (Beta)", "VRMainBoss_Character_Medium_C"],
  ["Corrupted Master Controller (Gamma)", "VRMainBoss_Character_Easy_C"],
  ["Corrupted Master Controller (Whale Rescue Alpha)", "VRMainBoss_Character_WhaleRescue_Alpha_C"],
  ["Corrupted Master Controller (Whale Rescue Beta)", "VRMainBoss_Character_WhaleRescue_Beta_C"],
  ["Corrupted Master Controller (Whale Rescue Gamma)", "VRMainBoss_Character_WhaleRescue_Gamma_C"],
  ["Corrupted Paraceratherium", "Paracer_Character_BP_Corrupt_C"],
  ["Corrupted Pteranodon", "Ptero_Character_BP_Corrupt_C"],
  ["Corrupted Raptor", "Raptor_Character_BP_Corrupt_C"],
  ["Corrupted Reaper King", "Xenomorph_Character_BP_Male_Tamed_Corrupt_C"],
  ["Corrupted Rex", "Rex_Character_BP_Corrupt_C"],
  ["Corrupted Rock Drake", "RockDrake_Character_BP_Corrupt_C"],
  ["Corrupted Spino", "Spino_Character_BP_Corrupt_C"],
  ["Corrupted Stegosaurus", "Stego_Character_BP_Corrupt_C"],
  ["Corrupted Survivor", "RockwellSpawn_Character_BP_C"],
  ["Corrupted Survivor (Alpha)", "RockwellSpawn_Character_BP_Alpha_C"],
  ["Corrupted Survivor (Alt, Alpha)", "RockwellSpawn_Character_BP_AltAnim_Alpha_C"],
  ["Corrupted Survivor (Alt, Beta)", "RockwellSpawn_Character_BP_AltAnim_Beta_C"],
  ["Corrupted Survivor (Alt, Gamma)", "RockwellSpawn_Character_BP_AltAnim_Gamma_C"],
  ["Corrupted Survivor (Beta)", "RockwellSpawn_Character_BP_Beta_C"],
  ["Corrupted Survivor (Gamma)", "RockwellSpawn_Character_BP_Gamma_C"],
  ["Corrupted Survivor (Variant)", "CorruptHuman_Character_BP_BASE_C"],
  ["Corrupted Survivor (Whale Rescue)", "CorruptHuman_WithTekRifle_Character_BP_WhaleRescue_C"],
  ["Corrupted Survivor, Alt", "RockwellSpawn_Character_BP_AltAnim_C"],
  ["Corrupted Survivor, With Tek Rifle", "CorruptHuman_WithTekRifle_Character_BP_C"],
  ["Corrupted Triceratops", "Trike_Character_BP_Corrupt_C"],
  ["Corrupted Wyvern", "Wyvern_Character_BP_Fire_Corrupt_C"],
  ["Cosmo", "JumpingSpider_Character_BP_C"],
  ["Cruise Missile", "TekCruiseMissile_Character_BP_C"],
  ["Crystal Wyvern", "CrystalWyvern_Character_BP_Base_C"],
  ["Crystal Wyvern (Blood)", "CrystalWyvern_Character_BP_Blood_C"],
  ["Crystal Wyvern (Ember)", "CrystalWyvern_Character_BP_Ember_C"],
  ["Crystal Wyvern (Tropical)", "CrystalWyvern_Character_BP_WS_C"],
  ["Crystal Wyvern Minion", "CrystalWyvern_Character_BP_Minion_C"],
  ["Crystal Wyvern Minion (Blood)", "CrystalWyvern_Character_BP_Minion_Blood_C"],
  ["Crystal Wyvern Minion (Ember)", "CrystalWyvern_Character_BP_Minion_Ember_C"],
  ["Crystal Wyvern Minion (Tropical)", "CrystalWyvern_Character_BP_Minion_WS_C"],
  ["Crystal Wyvern Queen", "CrystalWyvern_Character_BP_Boss_C"],
  ["Cymathoa", "Cymathoa_Character_BP_Medium_C"],
  ["Cymathoa (Alpha)", "Cymathoa_Character_BP_Hard_C"],
  ["Cymathoa (Gamma)", "Cymathoa_Character_BP_Easy_C"],
  ["Daeodon", "Daeodon_Character_BP_C"],
  ["Daeodon (Escort)", "Daeodon_Character_BP_Escort_C"],
  ["Daeodon (Gauntlet)", "Daeodon_Character_BP_Gauntlet_C"],
  ["Daeodon (Retrieve)", "Daeodon_Character_BP_Retrieve_C"],
  ["Dakosaurus", "Dakosaurus_Character_BP_C"],
  ["Dakosaurus (Rift)", "Dakosaurus_Character_BP_Rift_C"],
  ["Deathworm", "Deathworm_Character_BP_C"],
  ["Deathworm (Gauntlet)", "Deathworm_Character_BP_Gauntlet_C"],
  ["Deathworm Boss Minion", "Deathworm_Character_Minion_BP_C"],
  ["Deep Sea Coelacanth", "Coel_Character_BP_Ocean_C"],
  ["Deep Sea Valentine's Coelacanth", "Coel_Character_BP_VDay_Ocean_C"],
  ["Defense Unit", "Defender_Character_BP_C"],
  ["Defense Unit (Gauntlet)", "EndTank_Character_BP_Gauntlet_C"],
  ["Defense Unit (Mashup)", "EndTank_Character_BP_ExpG_C"],
  ["Deinonychus", "Deinonychus_Character_BP_C"],
  ["Deinosuchus", "DeinosuchusASA_Character_BP_C"],
  ["Deinotherium", "DeinotheriumASA_Character_BP_C"],
  ["Desert Titan", "DesertKaiju_Character_BP_C"],
  ["Desert Titan Flock", "DesertKaiju_FirstFlockChar_BP_C"],
  ["Desmodus", "Desmodus_Character_BP_C"],
  ["Dilophosaur", "Dilo_Character_BP_C"],
  ["Dilophosaur (Gauntlet)", "Dilo_Character_BP_Gauntlet_C"],
  ["Dilophosaur (Hunt)", "Dilo_Character_BP_Hunt_C"],
  ["Dilophosaur (Retrieve)", "Dilo_Character_BP_Retrieve_C"],
  ["Dimetrodon", "Dimetro_Character_BP_C"],
  ["Dimetrodon (Hunt)", "Dimetro_Character_BP_Hunt_C"],
  ["Dimorphodon", "Dimorph_Character_BP_C"],
  ["Dimorphodon (Retrieve)", "Dimorph_Character_BP_Aggressive_Retrieve_C"],
  ["Dinopithecus", "Dinopithecus_Character_BP_C"],
  ["Dinopithecus (Minion)", "Dinopithecus_Character_BP_Minion_C"],
  ["Dinopithecus King (Alpha)", "BossDinopithecus_Character_BP_Hard_C"],
  ["Dinopithecus King (Beta)", "BossDinopithecus_Character_BP_Medium_C"],
  ["Dinopithecus King (Gamma)", "BossDinopithecus_Character_BP_Easy_C"],
  ["Diplocaulus", "Diplocaulus_Character_BP_C"],
  ["Diplodocus", "Diplodocus_Character_BP_C"],
  ["Direbear", "Direbear_Character_BP_C"],
  ["Direwolf", "Direwolf_Character_BP_C"],
  ["Direwolf (Escort)", "Direwolf_Character_BP_Escort_C"],
  ["Direwolf (Gauntlet)", "Direwolf_Character_BP_Gauntlet_C"],
  ["Direwolf (Hunt)", "Direwolf_Character_BP_Hunt_C"],
  ["Direwolf (Retrieve)", "Direwolf_Character_BP_Retrieve_C"],
  ["Direwolf Ghost", "Ghost_Direwolf_Character_BP_C"],
  ["Diseased Leech", "Leech_Character_Diseased_C"],
  ["Dodo", "Dodo_Character_BP_C"],
  ["Dodo (Gauntlet Large)", "Dodo_Character_BP_Aggressive_Large_C"],
  ["Dodo (Gauntlet)", "Dodo_Character_BP_Aggressive_C"],
  ["Dodo (Sport)", "Dodo_Character_BP_Basketball_C"],
  ["Dodo Wyvern", "DodoWyvern_Character_BP_C"],
  ["DodoRex", "DodoRex_Character_BP_C"],
  ["DodoRex (Alt)", "DodoRex_Character_BP_FearEvolved_C"],
  ["DodoRex (Turkey Trials)", "DodoRex_Character_BP_TurkeyTrials_C"],
  ["Doedicurus", "Doed_Character_BP_C"],
  ["Doedicurus (Race)", "Doed_Character_BP_Race_C"],
  ["Dragon", "Dragon_Character_BP_C"],
  ["Dragon Alpha", "EndBossDragon_Character_BP_Hard_C"],
  ["Dragon Alpha (Fjordur)", "Dragon_Character_BP_Boss_Hard_FJ_C"],
  ["Dragon Beta", "EndBossDragon_Character_BP_Medium_C"],
  ["Dragon Beta (Fjordur)", "Dragon_Character_BP_Boss_Medium_FJ_C"],
  ["Dragon Gamma", "EndBossDragon_Character_BP_Easy_C"],
  ["Dragon Gamma (Fjordur)", "Dragon_Character_BP_Boss_Easy_FJ_C"],
  ["Dragon Guardian", "EndBossDragon_Character_BP_C"],
  ["Dreadmare", "DarkPegasus_Character_BP_C"],
  ["Dreadnoughtus", "Dreadnoughtus_Character_BP_C"],
  ["Drone", "EndDrone_Lunar_Character_BP_C"],
  ["Drone Tank", "EndTank_Lunar_Character_BP_C"],
  ["Dung Beetle", "DungBeetle_Character_BP_C"],
  ["Dunkleosteus", "Dunkle_Character_BP_C"],
  ["Dunkleosteus (Rift)", "Dunkle_Character_BP_Rift_C"],
  ["Eden Daeodon", "Daeodon_Character_BP_Eden_C"],
  ["Eden Direwolf", "Direwolf_Character_BP_Eden_C"],
  ["Eden Equus", "Equus_Character_BP_Eden_C"],
  ["Eden Gasbag", "GasBags_Character_BP_Eden_C"],
  ["Eden Megatherium", "Megatherium_Character_BP_Eden_C"],
  ["Eden Owl", "Owl_Character_BP_Eden_C"],
  ["Eden Parasaur", "Para_Character_BP_Eden_C"],
  ["Eden Procoptodon", "Procoptodon_Character_BP_Eden_C"],
  ["Eden Thylacoleo", "Thylacoleo_Character_BP_Eden_C"],
  ["Eel Minion", "EelMinion_Character_BP_C"],
  ["Eel Minion Alpha", "EelMinion_Character_BP_Hard_C"],
  ["Eel Minion Beta", "EelMinion_Character_BP_Medium_C"],
  ["Eel Minion Gamma", "EelMinion_Character_BP_Easy_C"],
  ["Electrophorus", "Eel_Character_BP_C"],
  ["Electrophorus (Escort)", "Eel_Character_BP_Escort_C"],
  ["Electrophorus (Hunt)", "Eel_Character_BP_Hunt_C"],
  ["Electrophorus (Retrieve)", "Eel_Character_BP_Retrieve_C"],
  ["Electrophorus (Rift)", "Eel_Character_BP_Rift_C"],
  ["Elemental Reaper King", "Xenomorph_Character_BP_Male_Minion_C"],
  ["Enforcer", "Enforcer_Character_BP_C"],
  ["Enforcer (Race)", "Enforcer_Character_BP_Race_C"],
  ["Enraged Corrupted Rex", "MegaRex_Character_BP_Corrupt_C"],
  ["Enraged Triceratops", "MegaTrike_Character_BP_Corrupt_C"],
  ["Equus", "Equus_Character_BP_C"],
  ["Eurypterid", "Euryp_Character_C"],
  ["Exo-Mek", "Exosuit_Character_BP_C"],
  ["Exo-Mek (Final Fight)", "Exosuit_Character_BP_FinalFight_C"],
  ["Exo-Mek (RTS)", "Exosuit_RTS_Character_BP_C"],
  ["Experimental Giganotosaurus (Mashup)", "Gigant_Character_BP_ExpG_C"],
  ["Fasolasuchus", "Fasola_Character_BP_C"],
  ["Featherlight", "LanternBird_Character_BP_C"],
  ["Fenrir", "Fenrir_Character_BP_C"],
  ["Fenrir Mini Boss", "Fenrir_Character_BP_MiniBoss_C"],
  ["Fenrir Minion", "Fenrir_Character_BP_Minion_C"],
  ["Fenrisúlfr", "Fenrir_Character_BP_Boss_C"],
  ["Fenrisulfr Alpha", "Fenrir_Character_BP_Boss_Hard_C"],
  ["Fenrisulfr Beta", "Fenrir_Character_BP_Boss_Medium_C"],
  ["Fenrisulfr Gamma", "Fenrir_Character_BP_Boss_Easy_C"],
  ["Ferox (Gauntlet)", "Shapeshifter_Large_Character_BP_Gauntlet_C"],
  ["Ferox (Large)", "Shapeshifter_Large_Character_BP_C"],
  ["Ferox (Small)", "Shapeshifter_Small_Character_BP_C"],
  ["Fire Wyvern", "Wyvern_Character_BP_Fire_C"],
  ["Fire Wyvern (Gauntlet)", "Wyvern_Character_BP_Fire_Gauntlet_C"],
  ["Fire Wyvern (Ragnarok)", "Ragnarok_Wyvern_Override_C"],
  ["Fjordhawk", "Fjordhawk_Character_BP_C"],
  ["Flying Titanomyrma", "FlyingAnt_Character_BP_C"],
  ["Forest Titan", "ForestKaiju_Character_BP_C"],
  ["Forest Wyvern", "Wyvern_Character_BP_Fire_Minion_C"],
  ["Fractalis", "Fractalis_Character_BP_Medium_C"],
  ["Fractalis (Alpha)", "Fractalis_Character_BP_Hard_C"],
  ["Fractalis (Gamma)", "Fractalis_Character_BP_Easy_C"],
  ["Gacha", "Gacha_Character_BP_C"],
  ["Gacha Claus", "Gacha_Claus_Character_BP_C"],
  ["Gallimimus", "Galli_Character_BP_C"],
  ["Gallimimus (Race)", "Galli_Character_BP_Race_C"],
  ["Gamma Araneo Boss Minion (Gauntlet)", "SpiderS_Character_BP_Aggressive_C"],
  ["Gamma Attack Drone", "EndDrone_Character_BP_C"],
  ["Gamma Broodmother Lysrix", "SpiderL_Character_BP_Easy_C"],
  ["Gamma Broodmother Lysrix (The Center)", "SpiderL_Character_BP_TheCenter_C"],
  ["Gamma Crystal Wyvern Queen", "CrystalWyvern_Character_BP_Boss_Easy_C"],
  ["Gamma Defense Unit", "EndTank_Character_BP_C"],
  ["Gamma Dimorphodon Boss Minion", "Dimorph_Character_BP_Aggressive_DragonBoss_C"],
  ["Gamma Dragon", "Dragon_Character_BP_Boss_Easy_C"],
  ["Gamma Dragon (Ragnarok)", "Dragon_Character_BP_Boss_Easy_Ragnarok_C"],
  ["Gamma Gigantopithecus Boss Minion (Gauntlet)", "Bigfoot_Character_BP_Aggressive_C"],
  ["Gamma King Titan", "KingKaiju_Character_BP_C"],
  ["Gamma Manticore", "Manticore_Character_BP_Easy_C"],
  ["Gamma Manticore (Ragnarok)", "Manticore_Character_BP_Easy_Ragnarok_C"],
  ["Gamma Megapithecus", "Gorilla_Character_BP_Easy_C"],
  ["Gamma Megapithecus (The Center)", "Gorilla_Character_BP_TheCenter_C"],
  ["Gamma Mesopithecus Boss Minion (Gauntlet)", "Monkey_Character_BP_Aggressive_C"],
  ["Gamma Pteranodon Boss Minion", "Ptero_Minion_Character_BP_C"],
  ["Gasbags", "GasBags_Character_BP_C"],
  ["Giant Bee", "Bee_Character_BP_C"],
  ["Giant Queen Bee", "Bee_Queen_Character_BP_C"],
  ["Giant Queen Bee (Gauntlet)", "Bee_Queen_Character_BP_Gauntlet_C"],
  ["Giant Worker Bee", "HoneyBee_Character_BP_C"],
  ["Giganotosaurus", "Gigant_Character_BP_C"],
  ["Gigantopithecus", "Bigfoot_Character_BP_C"],
  ["Gigantopithecus (Hunt)", "Bigfoot_Character_BP_Hunt_C"],
  ["Gigantopithecus (Mashup)", "Bigfoot_Character_BP_ExpG_Pod_C"],
  ["Gigantoraptor", "Gigantoraptor_Character_BP_C"],
  ["Glowbug", "Lightbug_Character_BaseBP_C"],
  ["Glowtail", "LanternLizard_Character_BP_C"],
  ["Golden Striped Brute Megalodon", "Ocean_Megalodon_Character_BP_Retrieve_Brute_C"],
  ["Golden Striped Megalodon (Retrieve)", "Ocean_Megalodon_Character_BP_Retrieve_C"],
  ["Griffin", "Griffin_Character_BP_C"],
  ["Griffin Boss Minion", "Griffin_Character_Minion_BP_C"],
  ["Hati", "Fenrir_Character_BP_MiniBoss_Hati_C"],
  ["Hesperornis", "Hesperornis_Character_BP_C"],
  ["Homarus", "Homarus_Character_BP_C"],
  ["Hover Skiff", "TekHoverSkiff_Character_BP_C"],
  ["Hover Skiff (Race)", "TekHoverSkiff_Character_BP_Race_C"],
  ["Hover Skiff (Whale Rescue)", "TekHoverSkiff_Character_BP_WhaleRescue_C"],
  ["Human (Female)", "PlayerPawnTest_Female_C"],
  ["Human (Male)", "PlayerPawnTest_Male_C"],
  ["Hyaenodon", "Hyaenodon_Character_BP_C"],
  ["Ice Golem (Valguero)", "IceGolem_Character_BP_C"],
  ["Ice Titan", "IceKaiju_Character_BP_C"],
  ["Ice Wyvern", "Ragnarok_Wyvern_Override_Ice_C"],
  ["Iceworm Male", "Iceworm_Character_Minion_BP_smaller_C"],
  ["Iceworm Queen", "Iceworm_Queen_Character_BP_C"],
  ["Ichthyornis", "Ichthyornis_Character_BP_C"],
  ["Ichthyosaurus", "Dolphin_Character_BP_C"],
  ["Ichthyosaurus (Race)", "RaceDolphin_Character_BP_C"],
  ["Iguanodon", "Iguanodon_Character_BP_C"],
  ["Iguanodon (Gauntlet)", "Iguanodon_Character_BP_Gauntlet_C"],
  ["Injured Brute Reaper King (Retrieve)", "Xenomorph_Character_BP_Male_InitialBuryOnly_Brute_Retrieve_C"],
  ["Insect Swarm", "InsectSwarmChar_BP_C"],
  ["Istiophorus", "Istiophorus_Character_BP_C"],
  ["Jerboa", "Jerboa_Character_BP_C"],
  ["Jug Bug", "Jugbug_Character_BaseBP_C"],
  ["Kairuku", "Kairuku_Character_BP_C"],
  ["Kaprosuchus", "Kaprosuchus_Character_BP_C"],
  ["Kaprosuchus (Gauntlet)", "Kaprosuchus_Character_BP_Gauntlet_C"],
  ["Kaprosuchus (Mashup)", "Kaprosuchus_Character_BP_ExpG_Pod_C"],
  ["Kaprosuchus (Race)", "Kapro_Character_BP_Race_C"],
  ["Kaprosuchus (Retrieve)", "Kaprosuchus_Character_BP_Retrieve_C"],
  ["Kaprosuchus (Rift)", "Kaprosuchus_Character_BP_Rift_C"],
  ["Karkinos", "Crab_Character_BP_C"],
  ["Kathreptis", "Kathreptis_Character_BP_C"],
  ["Kentrosaurus", "Kentro_Character_BP_C"],
  ["Kentrosaurus (Gauntlet)", "Kentro_Character_BP_Gauntlet_C"],
  ["Kentrosaurus (Retrieve)", "Kentro_Character_BP_Retrieve_C"],
  ["King Titan", "KingKaiju_Character_BP_WorldBoss_C"],
  ["Lamprey", "Lamprey_Character_C"],
  ["Large Fractalis Crystal", "FractalisCrystal_Large_Fire_C"],
  ["Large Fractalis Crystal (Stun)", "FractalisCrystal_Large_Stun_C"],
  ["Lava Elemental", "LavaGolem_Character_BP_C"],
  ["Leech", "Leech_Character_C"],
  ["Leech (Rift)", "Leech_Character_Rift_C"],
  ["Leedsichthys", "Leedsichthys_Character_BP_C"],
  ["Leedsichthys (Retrieve)", "Leedsichthys_Character_BP_Retrieve_C"],
  ["Lightning Wyvern", "Wyvern_Character_BP_Lightning_C"],
  ["Lightning Wyvern (Gauntlet)", "Wyvern_Character_BP_Lightning_Gauntlet_C"],
  ["Liopleurodon", "Liopleurodon_Character_BP_C"],
  ["Liopleurodon (Escort)", "Liopleurodon_Character_BP_Escort_C"],
  ["Liopleurodon (Hunt)", "Liopleurodon_Character_BP_Hunt_C"],
  ["Liopleurodon (Retrieve)", "Liopleurodon_Character_BP_Retrieve_C"],
  ["Liopleurodon (Rift)", "Liopleurodon_Character_BP_Rift_C"],
  ["Lunar Reaper King", "Xenomorph_Character_BP_Male_Lunar_C"],
  ["Lymantria", "Moth_Character_BP_C"],
  ["Lymantria (Gauntlet)", "Moth_Character_BP_Gauntlet_C"],
  ["Lystrosaurus", "Lystro_Character_BP_C"],
  ["Macro-Summoner", "Summoner_Character_BP_CorruptedMaze_C"],
  ["Macrophage", "Macrophage_Swarm_Character_C"],
  ["Maeguana", "Maelizard_Character_BP_C"],
  ["Maewing", "MilkGlider_character_BP_C"],
  ["Maewing (Hunt)", "MilkGlider_Character_BP_TorporHunt_C"],
  ["Maewing (Race)", "MilkGlider_Character_BP_Race_C"],
  ["Magmasaur", "Cherufe_Character_BP_C"],
  ["Magmasaur (Gauntlet)", "Cherufe_Character_BP_Gauntlet_C"],
  ["Magmasaur (Retrieve)", "Cherufe_Character_BP_Retrieve_C"],
  ["Malfunctioned Attack Drone", "EndDrone_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Attack Drone (Malfunctioned)", "EndDrone_Character_BP_Malfunctioned_LifeSupport_C"],
  ["Malfunctioned Defense Unit", "EndTank_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Defense Unit (Malfunctioned)", "EndTank_Character_BP_LifeSupport_C"],
  ["Malfunctioned Enforcer", "Enforcer_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Enforcer (Malfunctioned)", "Enforcer_Character_BP_Malfunctioned_LifeSupport_C"],
  ["Malfunctioned Mek Knight (Malfunctioned)", "Mek_Character_BP_LifeSupport_C"],
  ["Malfunctioned Tek Giganotosaurus", "BionicGigant_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Giganotosaurus (Gauntlet)", "BionicGigant_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Parasaur", "BionicPara_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Parasaur (Gauntlet)", "BionicPara_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Parasaur (Retrieve)", "BionicPara_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malfunctioned Tek Quetzal", "BionicQuetz_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Quetzal (Gauntlet)", "BionicQuetz_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Quetzal (Retrieve)", "BionicQuetz_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malfunctioned Tek Raptor", "BionicRaptor_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Raptor (Gauntlet)", "BionicRaptor_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Raptor (Malfunctioned)", "BionicRaptor_Character_BP_Malfunctioned_LifeSupport_C"],
  ["Malfunctioned Tek Raptor (Retrieve)", "BionicRaptor_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malfunctioned Tek Rex", "BionicRex_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Rex (Gauntlet)", "BionicRex_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Rex (Hunt)", "BionicRex_Character_BP_Malfunctioned_Adolescent_Hunt_C"],
  ["Malfunctioned Tek Rex (Retrieve)", "BionicRex_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malfunctioned Tek Stegosaurus", "BionicStego_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Stegosaurus (Gauntlet)", "BionicStego_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Stegosaurus (Malfunctioned)", "BionicStego_Character_BP_Malfunctioned_LifeSupport_C"],
  ["Malfunctioned Tek Stegosaurus (Retrieve)", "BionicStego_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malfunctioned Tek Stryder (Malfunctioned)", "TekStrider_Character_BP_LifeSupport_C"],
  ["Malfunctioned Tek Triceratops", "BionicTrike_Character_BP_Malfunctioned_C"],
  ["Malfunctioned Tek Triceratops (Gauntlet)", "BionicTrike_Character_BP_Malfunctioned_Gauntlet_C"],
  ["Malfunctioned Tek Triceratops (Malfunctioned)", "BionicTrike_Character_BP_Malfunctioned_LifeSupport_C"],
  ["Malfunctioned Tek Triceratops (Retrieve)", "BionicTrike_Character_BP_Malfunctioned_Retrieve_C"],
  ["Malleocephalus", "Malleocephalus_Character_BP_C"],
  ["Malleocephalus (Rift)", "Malleocephalus_Character_BP_Rift_C"],
  ["Mammoth", "Mammoth_Character_BP_C"],
  ["Mammoth (Gauntlet)", "Mammoth_Character_BP_Gauntlet_C"],
  ["Mammoth (Hunt)", "Mammoth_Character_BP_HuntFollower_C"],
  ["Managarmr", "IceJumper_Character_BP_C"],
  ["Managarmr (Gauntlet)", "IceJumper_Character_BP_Gauntlet_C"],
  ["Manta", "Manta_Character_BP_C"],
  ["Manta (Escort)", "Manta_Character_BP_Escort_C"],
  ["Manta (Race)", "Manta_Character_BP_Race_C"],
  ["Manta (Retrieve)", "Manta_Character_BP_Retrieve_C"],
  ["Manta (Rift)", "Manta_Character_BP_Rift_C"],
  ["Manticore", "Manticore_Character_BP_C"],
  ["Mantis", "Mantis_Character_BP_C"],
  ["Mantis (Gauntlet)", "Mantis_Character_BP_Gauntlet_C"],
  ["Mantis Ghost", "Ghost_Mantis_Character_BP_C"],
  ["Mantis Shrimp", "MantisShrimp_Character_BP_C"],
  ["Mantis Shrimp (Rift)", "MantisShrimp_Character_BP_Rift_C"],
  ["Mega Mek", "MegaMek_Character_BP_C"],
  ["Megachelon", "GiantTurtle_Character_BP_C"],
  ["Megachelon (Escort)", "GiantTurtle_Character_BP_Escort_C"],
  ["Megalania", "Megalania_Character_BP_C"],
  ["Megalania (Gauntlet)", "Megalania_Character_BP_Gauntlet_C"],
  ["Megaloceros", "Stag_Character_BP_C"],
  ["Megaloceros (Lifes Labyrinth)", "Stag_LL_Character_BP_C"],
  ["Megalodon", "Megalodon_Character_BP_C"],
  ["Megalodon (Rift)", "Megalodon_Character_BP_Rift_C"],
  ["Megalosaurus", "Megalosaurus_Character_BP_C"],
  ["Megalosaurus (Gauntlet)", "Megalosaurus_Character_BP_Gauntlet_C"],
  ["Megalosaurus (Hunt)", "Megalosaurus_Character_BP_Hunt_Enemy_C"],
  ["Meganeura", "Dragonfly_Character_BP_C"],
  ["Megapithecus", "Gorilla_Character_BP_C"],
  ["Megapithecus (Gauntlet)", "Gorilla_Character_BP_Gauntlet_C"],
  ["Megapithecus Alpha", "EndBossGorilla_Character_BP_Hard_C"],
  ["Megapithecus Alpha (Fjordur)", "Gorilla_Character_BP_Hard_FJ_C"],
  ["Megapithecus Beta", "EndBossGorilla_Character_BP_Medium_C"],
  ["Megapithecus Beta (Fjordur)", "Gorilla_Character_BP_Medium_FJ_C"],
  ["Megapithecus Gamma", "EndBossGorilla_Character_BP_Easy_C"],
  ["Megapithecus Gamma (Fjordur)", "Gorilla_Character_BP_Easy_FJ_C"],
  ["Megapithecus Guardian", "EndBossGorilla_Character_BP_C"],
  ["Megatherium", "Megatherium_Character_BP_C"],
  ["Megatherium (Gauntlet)", "Megatherium_Character_BP_Gauntlet_C"],
  ["Mek", "Mek_Character_BP_C"],
  ["Mesopithecus", "Monkey_Character_BP_C"],
  ["Microbe Swarm", "MicrobeSwarmChar_BP_C"],
  ["Microraptor", "Microraptor_Character_BP_C"],
  ["Microraptor (Retrieve)", "Microraptor_Character_BP_Retrieve_C"],
  ["Moeder", "EelBoss_Character_BP_C"],
  ["Moeder Alpha", "EelBoss_Character_BP_Hard_C"],
  ["Moeder Beta", "EelBoss_Character_BP_Medium_C"],
  ["Moeder Gamma", "EelBoss_Character_BP_Easy_C"],
  ["Monodon", "Monodon_Character_BP_C"],
  ["Monodon (Rift)", "Monodon_Character_BP_Rift_C"],
  ["Morellatops", "camelsaurus_Character_BP_C"],
  ["Mosasaurus", "Mosa_Character_BP_C"],
  ["Mosasaurus (Rift)", "Mosa_Character_BP_Rift_C"],
  ["Moschops", "Moschops_Character_BP_C"],
  ["Motorboat", "MotorRaft_BP_C"],
  ["Mudpuppy", "Mudpuppy_Character_BP_C"],
  ["Mudpuppy (Rift)", "Mudpuppy_Character_BP_Rift_C"],
  ["Nameless", "ChupaCabra_Character_BP_C"],
  ["Nameless Queen", "Xenomorph_Character_BP_C"],
  ["Net Breaking Piranha", "Piranha_Character_BP_BreakNet_C"],
  ["Noglin", "BrainSlug_Character_BP_C"],
  ["Oasisaur", "Oasisaur_Character_BP_C"],
  ["Oasisaur (Vulture)", "Vulture_Character_BP_OasisaurTaming_C"],
  ["Ocepechelon", "Ocepechelon_Character_BP_C"],
  ["Ocepechelon (Rift)", "Ocepechelon_Character_BP_Rift_C"],
  ["Oil Jug Bug", "Jugbug_Oil_Character_BP_C"],
  ["Onchopristis", "Onchopristis_Character_BP_C"],
  ["Onchopristis (Rift)", "Onchopristis_Character_BP_Rift_C"],
  ["Onyc (Gauntlet)", "Bat_Character_BP_Gauntlet_C"],
  ["Onyc (Retrieve)", "Bat_Character_BP_Retrieve_C"],
  ["Onychonycteris", "Bat_Character_BP_C"],
  ["Otter", "Otter_Character_BP_C"],
  ["Overseer", "EndBoss_Character_C"],
  ["Overseer Alpha", "EndBoss_Character_Hard_C"],
  ["Overseer Beta", "EndBoss_Character_Medium_C"],
  ["Overseer Gamma", "EndBoss_Character_Easy_C"],
  ["Oviraptor", "Oviraptor_Character_BP_C"],
  ["Ovis", "Sheep_Character_BP_C"],
  ["Pachy", "Pachy_Character_BP_C"],
  ["Pachyrhinosaurus", "Pachyrhino_Character_BP_C"],
  ["Pachyrhinosaurus (Gauntlet)", "Pachyrhino_Character_BP_Gauntlet_C"],
  ["Pachyrhinosaurus (Mashup)", "Pachyrhino_Character_BP_ExpG_Pod_C"],
  ["Paraceratherium", "Paracer_Character_BP_C"],
  ["Paraceratherium (Hunt)", "Paracer_Character_BP_TorporHunt_C"],
  ["Paraceratherium (Mashup)", "Paracer_Character_BP_ExpG_Pod_C"],
  ["Parakeet Fish School (Escort)", "MicrobeSwarmChar_BP_Escort_C"],
  ["Parasaur (Escort)", "Para_Character_BP_Escort_C"],
  ["Parasaurolophus", "Para_Character_BP_C"],
  ["Party Dodo", "Dodo_Character_BP_Birthday_C"],
  ["Pegomastax", "Pegomastax_Character_BP_C"],
  ["Pelagornis", "Pela_Character_BP_C"],
  ["Phiomia", "Phiomia_Character_BP_C"],
  ["Phoenix", "Phoenix_Character_BP_C"],
  ["Phoenix (Gauntlet)", "Phoenix_Character_BP_Gauntlet_C"],
  ["Piranha", "Piranha_Character_BP_C"],
  ["Piranha (Ice Fishing Mission)", "Piranha_Character_BP_IceFishMission_C"],
  ["Piranha (Rift)", "Piranha_Character_BP_Rift_C"],
  ["Plesiosaur", "Plesiosaur_Character_BP_C"],
  ["Plesiosaur (Escort)", "Plesiosaur_Character_BP_Escort_C"],
  ["Plesiosaur (Retrieve)", "Plesiosaur_Character_BP_Retrieve_C"],
  ["Plesiosaur (Rift)", "Plesiosaur_Character_BP_Rift_C"],
  ["Poison Wyvern", "Wyvern_Character_BP_Poison_C"],
  ["Poison Wyvern (Gauntlet)", "Wyvern_Character_BP_Poison_Gauntlet_C"],
  ["Polar Bear", "Direbear_Character_Polar_C"],
  ["Polar Bear (Escort)", "Direbear_Character_Polar_Escort_C"],
  ["Polar Bear (Gauntlet)", "Direbear_Character_Polar_Gauntlet_C"],
  ["Polar Bear (Hunt)", "Direbear_Character_Hunt_C"],
  ["Polar Bear (Ragnarok)", "Polar_Bear_C"],
  ["Polar Bear (Retrieve)", "Direbear_Character_Polar_Retrieve_C"],
  ["Polar Purlovia", "Purlovia_Character_BP_Polar_C"],
  ["Polar Purlovia (Retrieve)", "Purlovia_Character_BP_Polar_Retrieve_C"],
  ["Procoptodon", "Procoptodon_Character_BP_C"],
  ["Procoptodon (Escort)", "Procoptodon_Character_BP_Escort_C"],
  ["Pteranodon", "Ptero_Character_BP_C"],
  ["Pteranodon (Escort)", "Ptero_Character_BP_Escort_C"],
  ["Pteranodon (Malfunctioned)", "Ptero_Character_BP_LifeSupport_C"],
  ["Pulmonoscorpius", "Scorpion_Character_BP_C"],
  ["Pulmonoscorpius (Escort)", "Scorpion_Character_BP_Escort_C"],
  ["Pulmonoscorpius (Gauntlet)", "Scorpion_Character_BP_Gauntlet_C"],
  ["Pulmonoscorpius (Hunt)", "Scorpion_Character_BP_Hunt_C"],
  ["Pulmonoscorpius (Retrieve)", "Scorpion_Character_BP_Retrieve_C"],
  ["Purlovia", "Purlovia_Character_BP_C"],
  ["Purlovia (Gauntlet)", "Purlovia_Character_BP_Gauntlet_C"],
  ["Purlovia (Retrieve)", "Purlovia_Character_BP_Retrieve_C"],
  ["Pygocentrus", "Pygocentrus_Character_BP_Medium_C"],
  ["Pygocentrus (Alpha)", "Pygocentrus_Character_BP_Hard_C"],
  ["Pygocentrus (Gamma)", "Pygocentrus_Character_BP_Easy_C"],
  ["Pygocentrus Minion", "PygocentrusMinion_Character_BP_C"],
  ["Pyromane", "FireLion_Character_BP_C"],
  ["Qarmoutus", "Qarmoutus_Character_BP_C"],
  ["Quetzalcoatlus", "Quetz_Character_BP_C"],
  ["R-Allosaurus (Mashup)", "Allo_Character_BP_ExpG_Pod_C"],
  ["R-Direbear", "Direbear_Character_BP_Rockwell_C"],
  ["R-Direwolf (Hunt)", "Direwolf_Character_BP_Eden_Hunt_Enemy_C"],
  ["R-Megatherium (Mashup)", "Megatherium_Character_BP_ExpG_Pod_C"],
  ["R-Parasaur (Mashup)", "Para_Character_BP_ExpG_Pod_C"],
  ["R-Thylacoleo (Hunt)", "Thylacoleo_Character_BP_Eden_Hunt_Enemy_C"],
  ["R-Velonasaur (Hunt Alpha)", "Spindles_Character_BP_Rockwell_Hunt_Alpha_C"],
  ["R-Velonasaur (Hunt)", "Spindles_Character_BP_Rockwell_Hunt_C"],
  ["Raft", "Raft_BP_C"],
  ["Raptor", "Raptor_Character_BP_C"],
  ["Raptor (Escort)", "Raptor_Character_BP_Escort_C"],
  ["Raptor (Hunt)", "Raptor_Character_BP_Hunt_Volcanic_C"],
  ["Raptor (Mashup)", "Raptor_Character_BP_ExpG_Pod_C"],
  ["Raptor (Retrieve)", "Raptor_Character_BP_Retrieve_C"],
  ["Rare Sabertooth Salmon", "Salmon_Character_Rare_BP_C"],
  ["Rare X-Sabertooth Salmon", "Rare_Lunar_Salmon_Character_BP_C"],
  ["Ravager", "CaveWolf_Character_BP_C"],
  ["Ravager (Gauntlet)", "CaveWolf_Character_BP_Gauntlet_C"],
  ["Reaper King", "Xenomorph_Character_BP_Male_C"],
  ["Reaper King (Tamed)", "Xenomorph_Character_BP_Male_Tamed_C"],
  ["Reaper Prince", "Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent_C"],
  ["Reaper Prince (Escort)", "Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent_Escort_C"],
  ["Reaper Prince (Gauntlet)", "Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent_Gauntlet_C"],
  ["Reaper Prince (Retrieve)", "Xenomorph_Character_BP_Male_InitialBuryOnly_Adolescent_Retrieve_C"],
  ["Reaper Queen", "Xenomorph_Character_BP_Female_C"],
  ["Rex", "Rex_Character_BP_C"],
  ["Rex (Hunt)", "Rex_Character_BP_Hunt_Enemy_C"],
  ["Rex (Mashup)", "Rex_Character_BP_ExpG_Pod_C"],
  ["Rex Ghost", "Ghost_Rex_Character_BP_C"],
  ["Rhyniognatha", "Rhynio_Character_BP_C"],
  ["Riftcrawler", "RiftCrawler_Character_BP_C"],
  ["Rock Drake", "RockDrake_Character_BP_C"],
  ["Rock Drake (Gauntlet)", "RockDrake_Character_BP_Gauntlet_C"],
  ["Rock Elemental", "RockGolem_Character_BP_C"],
  ["Rock Elemental (Gauntlet)", "IceGolem_Character_BP_Gauntlet_C"],
  ["Rock Elemental (Retrieve)", "IceGolem_Character_BP_Retrieve_C"],
  ["Rock Golem Boss Minion", "RockGolem_Character_Minion_BP_C"],
  ["Rockwell", "Rockwell_Character_BP_C"],
  ["Rockwell (Alpha)", "Rockwell_Character_BP_Hard_C"],
  ["Rockwell (Beta)", "Rockwell_Character_BP_Medium_C"],
  ["Rockwell (Gamma)", "Rockwell_Character_BP_Easy_C"],
  ["Rockwell Allosaurus", "Allo_Character_BP_Rockwell_C"],
  ["Rockwell Bronto", "Sauropod_Character_BP_Rockwell_C"],
  ["Rockwell Carno", "Carno_Character_BP_Rockwell_C"],
  ["Rockwell Dilo", "Dilo_Character_BP_Rockwell_C"],
  ["Rockwell Giga", "Gigant_Character_BP_Rockwell_C"],
  ["Rockwell Node (Final Fight)", "RockwellNode_Character_BP_FinalFight_C"],
  ["Rockwell Node Alpha", "RockwellNode_Character_BP_FinalFight_Alpha_C"],
  ["Rockwell Node Beta", "RockwellNode_Character_BP_FinalFight_Beta_C"],
  ["Rockwell Node Gamma", "RockwellNode_Character_BP_FinalFight_Gamma_C"],
  ["Rockwell Prime", "RockwellNode_Character_BP_Boss_C"],
  ["Rockwell Prime Alpha", "RockwellNode_Character_BP_Boss_Alpha_C"],
  ["Rockwell Prime Beta", "RockwellNode_Character_BP_Boss_Beta_C"],
  ["Rockwell Prime Gamma", "RockwellNode_Character_BP_Boss_Gamma_C"],
  ["Rockwell Quetzal", "Quetz_Character_BP_Rockwell_C"],
  ["Rockwell Reaper Female", "Xenomorph_Character_BP_Female_Gen2_C"],
  ["Rockwell Reaper Male", "Xenomorph_Character_BP_Male_Gen2_C"],
  ["Rockwell Tentacle", "RockwellTentacle_Character_BP_C"],
  ["Rockwell Tentacle (Alpha)", "RockwellTentacle_Character_BP_Alpha_C"],
  ["Rockwell Tentacle (Beta)", "RockwellTentacle_Character_BP_Beta_C"],
  ["Rockwell Tentacle (Gamma)", "RockwellTentacle_Character_BP_Gamma_C"],
  ["Rockwell Turtle", "Turtle_Character_BP_Rockwell_C"],
  ["Rockwell Velonasaur", "Spindles_Character_BP_Rockwell_C"],
  ["RockwellPrime", "RockwellNode_Character_BP_C"],
  ["Roll Rat", "MoleRat_Character_BP_C"],
  ["Rubble Bear", "Direbear_Character_BP_SteinbjornMinion_C"],
  ["Rubble Golem", "RubbleGolem_Character_BP_C"],
  ["Sabertooth", "Saber_Character_BP_C"],
  ["Sabertooth Salmon", "Salmon_Character_BP_C"],
  ["Sabertooth Salmon (Escort)", "Salmon_Character_BP_Escort_C"],
  ["Sabertooth Salmon (Ice Fishing Mission)", "Salmon_Character_BP_IceFishMission_C"],
  ["Sarco", "Sarco_Character_BP_C"],
  ["Sarco (Gauntlet)", "Sarco_Character_BP_Gauntlet_C"],
  ["Sarco (Hunt)", "Sarco_Character_BP_Hunt_Secondary_C"],
  ["Sarco (Retrieve)", "Sarco_Character_BP_Retrieve_C"],
  ["Sarco (Rift)", "Sarco_Character_BP_Rift_C"],
  ["Scout", "Scout_Character_BP_C"],
  ["Scout (Camera)", "RemoteCamera_Character_BP_C"],
  ["Seahorse", "Seahorse_Character_BP_C"],
  ["Seahorse (Rift)", "Seahorse_Character_BP_Rift_C"],
  ["Seeker", "Pteroteuthis_Char_BP_C"],
  ["Seeker (Escort)", "Pteroteuthis_Char_BP_Escort_C"],
  ["Seeker (Gauntlet)", "Pteroteuthis_Char_BP_Gauntlet_C"],
  ["Seeker (Retrieve)", "Pteroteuthis_Char_BP_Retrieve_C"],
  ["Shadowmane", "LionFishLion_Character_BP_C"],
  ["Shadowmane (Hunt Alpha)", "LionfishLion_Character_BP_Hunt_Alpha_C"],
  ["Shadowmane (Hunt)", "LionfishLion_Character_BP_Hunt_C"],
  ["Shadowmane Female", "LionfishLion_Character_BP_Female_C"],
  ["Shastasaurus", "Shastasaurus_Character_BP_C"],
  ["Shinehorn", "LanternGoat_Character_BP_C"],
  ["Shinehorn (Escort)", "LanternGoat_Character_BP_Escort_C"],
  ["Sinomacrops", "Sinomacrops_Character_BP_C"],
  ["Sinomacrops Minion", "Sinomacrops_Character_BP_Minion_C"],
  ["SIR-5rM8", "HelperBot_Character_BP_C"],
  ["Skeletal Bronto", "Bone_Sauropod_Character_BP_C"],
  ["Skeletal Carnotaurus", "Bone_MegaCarno_Character_BP_C"],
  ["Skeletal Giganotosaurus", "Bone_Gigant_Character_BP_C"],
  ["Skeletal Jerboa", "Bone_Jerboa_Character_BP_C"],
  ["Skeletal Quetzal", "Bone_Quetz_Character_BP_C"],
  ["Skeletal Raptor", "Bone_MegaRaptor_Character_BP_C"],
  ["Skeletal Rex", "Bone_MegaRex_Character_BP_C"],
  ["Skeletal Stego", "Bone_Stego_Character_BP_C"],
  ["Skeletal Trike", "Bone_Trike_Character_BP_C"],
  ["Skoll", "Fenrir_Character_BP_MiniBoss_Skoll_C"],
  ["Snow Owl", "Owl_Character_BP_C"],
  ["Snow Owl (Gauntlet)", "Owl_Character_BP_Gauntlet_C"],
  ["Snow Owl Ghost", "Ghost_Owl_Character_BP_C"],
  ["Spino", "Spino_Character_BP_C"],
  ["Spino (Mashup)", "Spino_Character_BP_ExpG_Pod_C"],
  ["Spino (Rift)", "Spino_Character_BP_Rift_C"],
  ["Spirit Direbear", "Direbear_LL_Character_BP_C"],
  ["Spirit Direwolf", "Direwolf_LL_Character_BP_C"],
  ["Static HoverSkiff (Whale Rescue)", "TekHoverSkiff_Character_BP_WhaleRescue_StaticCharging_C"],
  ["Stegosaurus", "Stego_Character_BP_C"],
  ["Steinbjorn", "Steinbjorn_Character_BP_C"],
  ["Stereolepis", "Stereolepis_Character_BP_C"],
  ["Stryder", "TekStrider_Character_BP_C"],
  ["Subterranean Reaper King", "Xenomorph_Character_BP_Male_Chupa_C"],
  ["Summoned Aberrant Arthropluera", "Arthro_Character_BP_Aberrant_Summoned_C"],
  ["Summoned Araneo", "SpiderS_Character_BP_Summoned_C"],
  ["Summoned Argentavis", "Argent_Character_BP_Summoned_C"],
  ["Summoned Baryonyx", "Baryonyx_Character_BP_Summoned_C"],
  ["Summoned Basilisk", "Basilisk_Character_BP_Summoned_C"],
  ["Summoned Bloodstalker", "BogSpider_Character_BP_Summoned_C"],
  ["Summoned Direbear", "Direbear_Character_BP_Summoned_C"],
  ["Summoned Ferox", "Shapeshifter_Large_Character_BP_Summoned_C"],
  ["Summoned Kaprosuchus", "Kaprosuchus_Character_BP_Summoned_C"],
  ["Summoned Karkinos", "Crab_Character_BP_Summoned_C"],
  ["Summoned Magmasaur", "Cherufe_Character_BP_Summoned_C"],
  ["Summoned Managarmr", "IceJumper_Character_BP_Summoned_C"],
  ["Summoned Mantis", "Mantis_Character_BP_Summoned_C"],
  ["Summoned Microraptor", "Microraptor_Character_BP_Summoned_C"],
  ["Summoned Onyc", "Bat_Character_BP_Summoned_C"],
  ["Summoned Paraceratherium", "Paracer_Character_BP_Summoned_C"],
  ["Summoned Pteranodon", "Ptero_Character_BP_Summoned_C"],
  ["Summoned Purlovia", "Purlovia_Character_BP_Summoned_C"],
  ["Summoned R-Allosaurus", "Allo_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Brontosaurus", "Sauropod_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Carnotaurus", "Carno_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Daeodon", "Daeodon_Character_BP_Eden_Summoned_C"],
  ["Summoned R-Dilophosaur", "Dilo_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Direbear", "Direbear_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Direwolf", "Direwolf_Character_BP_Eden_Summoned_C"],
  ["Summoned R-Megatherium", "Megatherium_Character_BP_Eden_Summoned_C"],
  ["Summoned R-Quetzal", "Quetz_Character_BP_Rockwell_Summoned_C"],
  ["Summoned R-Reaper King", "Xenomorph_Character_BP_Male_Gen2_Summoned_C"],
  ["Summoned R-Snow Owl", "Owl_Character_BP_Eden_Summoned_C"],
  ["Summoned R-Thylacoleo", "Thylacoleo_Character_BP_Eden_Summoned_C"],
  ["Summoned R-Velonasaur", "Spindles_Character_BP_Rockwell_Summoned_C"],
  ["Summoned Ravager", "CaveWolf_Character_BP_Summoned_C"],
  ["Summoned Rex", "Rex_Character_BP_Summoned_C"],
  ["Summoned Rock Drake", "RockDrake_Character_BP_Summoned_C"],
  ["Summoned Rock Elemental", "RockGolem_Character_BP_Summoned_C"],
  ["Summoned Sabertooth", "Saber_Character_BP_Summoned_C"],
  ["Summoned Sarco", "Sarco_Character_BP_Summoned_C"],
  ["Summoned Shadowmane", "LionfishLion_Character_BP_Summoned_C"],
  ["Summoned Spino", "Spino_Character_BP_Summoned_C"],
  ["Summoned Stegosaurus", "Stego_Character_BP_Summoned_C"],
  ["Summoned Terror Bird", "TerrorBird_Character_BP_Summoned_C"],
  ["Summoned Therizinosaur", "Therizino_Character_BP_Summoned_C"],
  ["Summoned Thorny Dragon", "SpineyLizard_Character_BP_Summoned_C"],
  ["Summoned Titanoboa", "BoaFrill_Character_BP_Summoned_C"],
  ["Summoned Triceratops", "Trike_Character_BP_Summoned_C"],
  ["Summoned Yutyrannus", "Yutyrannus_Character_BP_Summoned_C"],
  ["Summoner", "Summoner_Character_BP_C"],
  ["Summoner (Corrupted Maze Minion)", "Summoner_Character_BP_CorruptedMazeMinion_C"],
  ["Summoner (Final Fight)", "Summoner_Character_BP_FinalFight_C"],
  ["Summoner Alpha", "Summoner_Character_BP_FinalFight_Alpha_C"],
  ["Summoner Beta", "Summoner_Character_BP_FinalFight_Beta_C"],
  ["Summoner Gamma", "Summoner_Character_BP_FinalFight_Gamma_C"],
  ["Super Turkey", "Turkey_Character_BP_C"],
  ["Surface Chupacabra", "ChupaCabra_Character_BP_Surface_C"],
  ["Surface Reaper King", "Xenomorph_Character_BP_Male_Surface_C"],
  ["Surface Reaper King Ghost", "Ghost_Xenomorph_Character_BP_Male_Surface_C"],
  ["Surface Seeker", "Pteroteuthis_Char_BP_Surface_C"],
  ["Takifugu", "Takifugu_Character_BP_C"],
  ["Takifugu (Rift)", "Takifugu_Character_BP_Rift_C"],
  ["Tamed R-Reaper King", "Xenomorph_Character_BP_Male_Tamed_Gen2_C"],
  ["Tapejara", "Tapejara_Character_BP_C"],
  ["Tapejara (Mashup)", "Tapejara_Character_BP_ExpG_Pod_C"],
  ["Tek ATV", "VH_Buggy_C"],
  ["Tek Cave Giganotosaurus", "Gigant_Character_BP_TekCave_C"],
  ["Tek Cave Megalosaurus", "Megalosaurus_Character_BP_TekCave_C"],
  ["Tek Giganotosaurus", "BionicGigant_Character_BP_C"],
  ["Tek Hoversail", "TekHoverSail_Character_BP_C"],
  ["Tek Hoversail (Race)", "TekHoverSail_Character_BP_Race_C"],
  ["Tek Parasaur", "BionicPara_Character_BP_C"],
  ["Tek Quetzal", "BionicQuetz_Character_BP_C"],
  ["Tek Raptor", "BionicRaptor_Character_BP_C"],
  ["Tek Rex", "BionicRex_Character_BP_C"],
  ["Tek Stego", "BionicStego_Character_BP_C"],
  ["Tek Triceratops", "BionicTrike_Character_BP_C"],
  ["Tek Wyvern", "TekWyvern_Character_BP_C"],
  ["Terror Bird", "TerrorBird_Character_BP_C"],
  ["Terror Bird (Escort)", "TerrorBird_Character_BP_Escort_C"],
  ["Terror Bird (Gauntlet)", "TerrorBird_Character_BP_Gauntlet_C"],
  ["Terror Bird (Mashup)", "TerrorBird_Character_BP_ExpG_Pod_C"],
  ["Therizinosaur", "Therizino_Character_BP_C"],
  ["Therizinosaur (Gauntlet)", "Therizino_Character_BP_Gauntlet_C"],
  ["Therizinosaur (Mashup)", "Therizino_Character_BP_ExpG_Pod_C"],
  ["Thorny Dragon", "SpineyLizard_Character_BP_C"],
  ["Thorny Dragon (Gauntlet)", "SpineyLizard_Character_BP_Gauntlet_C"],
  ["Thorny Dragon (Hunt)", "SpineyLizard_Character_BP_Hunt_C"],
  ["Thorny Dragon (Retrieve)", "SpineyLizard_Character_BP_Retrieve_C"],
  ["Thunnus", "Thunnus_Character_BP_C"],
  ["Thylacoleo", "Thylacoleo_Character_BP_C"],
  ["Tiktaalik", "Tiktaalik_Character_BP_C"],
  ["Tiktaalik (Rift)", "Tiktaalik_Character_BP_Rift_C"],
  ["Titanoboa", "BoaFrill_Character_BP_C"],
  ["Titanoboa (Escort)", "BoaFrill_Character_BP_Escort_C"],
  ["Titanoboa (Gauntlet)", "BoaFrill_Character_BP_Gauntlet_C"],
  ["Titanoboa (Retrieve)", "BoaFrill_Character_BP_Retrieve_C"],
  ["Titanoboa (Rift)", "BoaFrill_Character_BP_Rift_C"],
  ["Titanomyrma", "Ant_Character_BP_C"],
  ["Titanosaur", "Titanosaur_Character_BP_C"],
  ["Triceratops", "Trike_Character_BP_C"],
  ["Tridacna", "Tridacna_Character_BP_C"],
  ["Trilobite", "Trilobite_Character_C"],
  ["Troodon", "Troodon_Character_BP_C"],
  ["Tropeognathus", "Tropeognathus_Character_BP_C"],
  ["Turkey", "TurkeyBase_Character_BP_C"],
  ["Tusoteuthis", "Tusoteuthis_Character_BP_C"],
  ["Tusoteuthis (Retrieve)", "Tusoteuthis_Character_BP_Retrieve_C"],
  ["Tusoteuthis (Rift)", "Tusoteuthis_Character_BP_Rift_C"],
  ["Unicorn", "Equus_Character_BP_Unicorn_C"],
  ["Valentine's Aberrant Coelacanth", "Coel_Character_BP_VDay_Aberrant_C"],
  ["Valentine's Coelacanth", "Coel_Character_BP_VDay_C"],
  ["Velonasaur", "Spindles_Character_BP_C"],
  ["Virtual Daeodon", "VRDaeodon_Character_BP_C"],
  ["Virtual Drone", "VREndDrone_Character_BP_C"],
  ["Virtual Giganotosaurus", "VRGigant_Character_BP_C"],
  ["Virtual Raptor", "VRRaptor_Character_BP_C"],
  ["Virtual Reaper King", "VRXenomorph_Character_BP_Male_Minion_C"],
  ["Virtual Rex", "VRRex_Character_BP_C"],
  ["Virtual Triceratops", "VRTrike_Character_BP_C"],
  ["Virtual Yutyrannus", "VRYutyrannus_Character_BP_C"],
  ["VR Allosaurus", "Allo_Character_BP_TameSTA_C"],
  ["VR Araneo (Mashup)", "SpiderS_Character_BP_ExpG_C"],
  ["VR Araneo (Maze)", "SpiderS_Character_BP_CorrMaze_C"],
  ["VR Argentavis (Malfunctioned)", "Argent_Character_BP_LifeSupport_C"],
  ["VR Argentavis (Mashup)", "Argent_Character_BP_ExpG_C"],
  ["VR Astrodelphis", "SpaceDolphin_Character_BP_TameSTA_C"],
  ["VR Bloodstalker", "BogSpider_Character_TameSTA_C"],
  ["VR Carnotaurus (Mashup)", "Carno_Character_BP_ExpG_C"],
  ["VR Carnotaurus (Maze)", "Carno_Character_BP_CorrMaze_C"],
  ["VR Chalicotherium (Mashup)", "Chalico_Character_BP_ExpG_C"],
  ["VR Dilophosaur (Maze)", "Dilo_Character_BP_CorrMaze_C"],
  ["VR Dimorphodon", "Dimorph_Character_BP_TameSTA_C"],
  ["VR Enforcer", "Enforcer_Character_BP_TameSTA_C"],
  ["VR Ferox", "Shapeshifter_Large_Character_BP_TameSTA_C"],
  ["VR Kaprosuchus", "Kaprosuchus_Character_BP_TameSTA_C"],
  ["VR Kaprosuchus (Mashup)", "Kaprosuchus_Character_BP_ExpG_C"],
  ["VR Kaprosuchus (Maze)", "Kaprosuchus_Character_BP_CorrMaze_C"],
  ["VR Karkinos", "Crab_Character_BP_TameSTA_C"],
  ["VR Lymantria", "Moth_Character_BP_TameSTA_C"],
  ["VR Lymantria (Mashup)", "Moth_Character_BP_ExpG_C"],
  ["VR Lymantria (Maze)", "Moth_Character_BP_CorrMaze_C"],
  ["VR Mantis", "Mantis_Character_BP_TameSTA_C"],
  ["VR Mantis (Maze)", "Mantis_Character_BP_CorrMaze_C"],
  ["VR Megalania (Maze)", "Megalania_Character_BP_CorrMaze_C"],
  ["VR Megatherium (Mashup)", "Megatherium_Character_BP_ExpG_C"],
  ["VR Onyc (Malfunctioned)", "Bat_Character_BP_LifeSupport_C"],
  ["VR Onyc (Mashup)", "Bat_Character_BP_ExpG_C"],
  ["VR Onyc (Maze)", "Bat_Character_BP_CorrMaze_C"],
  ["VR Pachy (Mashup)", "Pachy_Character_BP_ExpG_C"],
  ["VR Parasaur (Malfunctioned)", "Para_Character_BP_LifeSupport_C"],
  ["VR Parasaur (Mashup)", "Para_Character_BP_ExpG_C"],
  ["VR Pulmonoscorpius (Mashup)", "Scorpion_Character_BP_ExpG_C"],
  ["VR Pulmonoscorpius (Maze)", "Scorpion_Character_BP_CorrMaze_C"],
  ["VR Raptor", "Raptor_Character_BP_TameSTA_C"],
  ["VR Raptor (Mashup)", "Raptor_Character_BP_ExpG_C"],
  ["VR Raptor (Maze)", "Raptor_Character_BP_CorrMaze_C"],
  ["VR Ravager", "CaveWolf_Character_BP_TameSTA_C"],
  ["VR Rex (Malfunctioned)", "Rex_Character_BP_LifeSupport_C"],
  ["VR Rex (Mashup)", "Rex_Character_BP_ExpG_C"],
  ["VR Shadowmane", "LionfishLion_Character_BP_TameSTA_C"],
  ["VR Stegosaurus", "Stego_Character_BP_TameSTA_C"],
  ["VR Tapejara (Mashup)", "Tapejara_Character_BP_ExpG_C"],
  ["VR Tapejara (Maze)", "Tapejara_Character_BP_CorrMaze_C"],
  ["VR Terror Bird (Mashup)", "TerrorBird_Character_BP_ExpG_C"],
  ["VR Titanoboa (Maze)", "BoaFrill_Character_BP_CorrMaze_C"],
  ["VR Triceratops", "Trike_Character_BP_TameSTA_C"],
  ["VR Velonasaur", "Spindles_Character_BP_TameSTA_C"],
  ["Vulcanite", "Vulcanite_Character_BP_C"],
  ["Vulcanite (Boss Add)", "Vulcanite_Character_BP_BossAdd_C"],
  ["Vulcanithys", "Vulcanithys_Character_BP_Medium_C"],
  ["Vulcanithys (Alpha)", "Vulcanithys_Character_BP_Hard_C"],
  ["Vulcanithys (Gamma)", "Vulcanithys_Character_BP_Easy_C"],
  ["Vulture", "Vulture_Character_BP_C"],
  ["Water Jug Bug", "Jugbug_Water_Character_BP_C"],
  ["Water Wyvern", "Wyvern_Character_BP_Water_C"],
  ["Water Wyvern (Rift)", "Wyvern_Character_BP_Water_Rift_C"],
  ["Woolly Rhino", "Rhino_Character_BP_C"],
  ["Wyvern", "Wyvern_Character_BP_Base_C"],
  ["X-Allosaurus", "Volcano_Allo_Character_BP_C"],
  ["X-Allosaurus (Escort)", "Volcano_Allo_Character_BP_Escort_C"],
  ["X-Allosaurus (Gauntlet)", "Volcano_Allo_Character_BP_Gauntlet_C"],
  ["X-Allosaurus (Retrieve)", "Volcano_Allo_Character_BP_Retrieve_C"],
  ["X-Ankylosaurus", "Volcano_Ankylo_Character_BP_C"],
  ["X-Ankylosaurus (Gauntlet)", "Volcano_Ankylo_Character_BP_Gauntlet_C"],
  ["X-Argentavis", "Snow_Argent_Character_BP_C"],
  ["X-Argentavis (Gauntlet)", "Snow_Argent_Character_BP_Gauntlet_C"],
  ["X-Argentavis (Retrieve)", "Snow_Argent_Character_BP_Retrieve_C"],
  ["X-Basilosaurus", "Ocean_Basilosaurus_Character_BP_C"],
  ["X-Dragon", "Volcanic_Dragon_Character_BP_C"],
  ["X-Dunkleosteus", "Ocean_Dunkle_Character_BP_C"],
  ["X-Dunkleosteus (Escort)", "Ocean_Dunkle_Character_BP_Escort_C"],
  ["X-Ichthyosaurus", "Ocean_Dolphin_Character_BP_C"],
  ["X-Ichthyosaurus (Escort)", "Ocean_Dolphin_Character_BP_Escort_C"],
  ["X-Megalodon", "Ocean_Megalodon_Character_BP_C"],
  ["X-Megalodon (Escort)", "Ocean_Megalodon_Character_BP_Escort_C"],
  ["X-Megalodon (Retrieve)", "Ocean_Megalodon_Character_BP_RetrieveNonTarget_C"],
  ["X-Mosasaurus", "Ocean_Mosa_Character_BP_C"],
  ["X-Mosasaurus (Retrieve)", "Ocean_Mosa_Character_BP_Retrieve_C"],
  ["X-Otter", "Snow_Otter_Character_BP_C"],
  ["X-Paraceratherium", "Bog_Paracer_Character_BP_C"],
  ["X-Paraceratherium (Gauntlet)", "Bog_Paracer_Character_BP_Gauntlet_C"],
  ["X-Parasaur", "Bog_Para_Character_BP_C"],
  ["X-Raptor", "Raptor_Character_BP_Hunt_Enemy_C"],
  ["X-Raptor (Escort)", "Bog_Raptor_Character_BP_Escort_C"],
  ["X-Raptor (Gauntlet)", "Bog_Raptor_Character_BP_Gauntlet_C"],
  ["X-Raptor (Hunt)", "Bog_Raptor_Character_BP_Hunt_Secondary_C"],
  ["X-Raptor (Retrieve)", "Bog_Raptor_Character_BP_Retrieve_C"],
  ["X-Rex", "Volcano_Rex_Character_BP_C"],
  ["X-Rex (Escort)", "Volcano_Rex_Character_BP_Escort_C"],
  ["X-Rex (Gauntlet)", "Volcano_Rex_Character_BP_Gauntlet_C"],
  ["X-Rex (Retrieve)", "Volcano_Rex_Character_BP_Retrieve_C"],
  ["X-Rock Elemental", "Volcano_Golem_Character_BP_C"],
  ["X-Rock Elemental (Gauntlet)", "Volcano_Golem_Character_BP_Gauntlet_C"],
  ["X-Sabertooth", "Snow_Saber_Character_BP_C"],
  ["X-Sabertooth (Escort)", "Snow_Saber_Character_BP_Escort_C"],
  ["X-Sabertooth (Gauntlet)", "Snow_Saber_Character_BP_Gauntlet_C"],
  ["X-Sabertooth (Hunt)", "Snow_Saber_Character_BP_Hunt_C"],
  ["X-Sabertooth (Race)", "RaceSnow_Saber_Character_BP_C"],
  ["X-Sabertooth (Retrieve)", "Snow_Saber_Character_BP_Retrieve_C"],
  ["X-Sabertooth Salmon", "Lunar_Salmon_Character_BP_C"],
  ["X-Spino", "Bog_Spino_Character_BP_C"],
  ["X-Spino (Gauntlet)", "Bog_Spino_Character_BP_Gauntlet_C"],
  ["X-Spino (Retrieve)", "Bog_Spino_Character_BP_Retrieve_C"],
  ["X-Tapejara", "Bog_Tapejara_Character_BP_C"],
  ["X-Tapejara (Gauntlet)", "Bog_Tapejara_Character_BP_Gauntlet_C"],
  ["X-Triceratops", "Volcano_Trike_Character_BP_C"],
  ["X-Triceratops (Gauntlet)", "Volcano_Trike_Character_BP_Gauntlet_C"],
  ["X-Triceratops (Retrieve)", "Volcano_Trike_Character_BP_Retrieve_C"],
  ["X-Woolly Rhino", "Snow_Rhino_Character_BP_C"],
  ["X-Woolly Rhino (Gauntlet)", "Snow_Rhino_Character_BP_Gauntlet_C"],
  ["X-Woolly Rhino (Race)", "Snow_Rhino_Character_BP_Race_C"],
  ["X-Yutyrannus", "Snow_Yutyrannus_Character_BP_C"],
  ["X-Yutyrannus (Gauntlet)", "Snow_Yutyrannus_Character_BP_Gauntlet_C"],
  ["X-Yutyrannus (Hunt)", "Snow_Yutyrannus_Character_BP_HuntFollower_C"],
  ["X-Yutyrannus (Retrieve)", "Snow_Yutyrannus_Character_BP_Retrieve_C"],
  ["Xiphactinus", "Xiphactinus_Character_BP_ASA_C"],
  ["Yeti", "Yeti_Character_BP_C"],
  ["Yeti (Gauntlet)", "Bigfoot_Character_BP_Gauntlet_C"],
  ["Yi Ling", "YiLing_Character_BP_C"],
  ["Young Malfunctioned Tek Rex", "BionicRex_Character_BP_Malfunctioned_Adolescent_C"],
  ["Yutyrannus", "Yutyrannus_Character_BP_C"],
  ["Yutyrannus (Mashup)", "Yutyrannus_Character_BP_ExpG_Pod_C"],
  ["Zombie Fire Wyvern", "Wyvern_Character_BP_ZombieFire_C"],
  ["Zombie Lightning Wyvern", "Wyvern_Character_BP_ZombieLightning_C"],
  ["Zombie Poison Wyvern", "Wyvern_Character_BP_ZombiePoison_C"],
  ["Zomdodo", "ZombieDodo_Character_BP_C"]
];

export const ARK_GM_CREATURE_OPTIONS: ArkGmCreatureOption[] = ARK_GM_CREATURE_TUPLES.map(([name, classId]) => ({
  value: classId,
  label: `${name} / Official / ${classId}`,
  name,
  category: "Official"
}));

type ArkGmCreatureSearchEntry = {
  option: ArkGmCreatureOption;
  text: string;
  name: string;
  localizedName: string;
  localizedCategory: string;
  value: string;
  order: number;
};

let creatureSearchIndex: ArkGmCreatureSearchEntry[] | undefined;

function buildArkGmCreatureSearchIndex(): ArkGmCreatureSearchEntry[] {
  return ARK_GM_CREATURE_OPTIONS.map((option, order) => {
    const aliases = arkCatalogSearchAliases(option);
    const [localizedName = "", ...localizedCategory] = aliases.split(" ");
    return {
      option,
      text: normalizeArkGmCreatureSearchText([option.name, option.category, option.value, aliases].join(" ")),
      name: normalizeArkGmCreatureSearchText(option.name),
      localizedName: normalizeArkGmCreatureSearchText(localizedName),
      localizedCategory: normalizeArkGmCreatureSearchText(localizedCategory.join(" ")),
      value: normalizeArkGmCreatureSearchText(option.value),
      order
    };
  });
}

export function searchArkGmCreatureOptions(query: string, limit = 80): ArkGmCreatureOption[] {
  const normalized = normalizeArkGmCreatureSearchText(query);
  if (!normalized) {
    return ARK_GM_CREATURE_OPTIONS.slice(0, limit);
  }
  creatureSearchIndex ??= buildArkGmCreatureSearchIndex();
  return creatureSearchIndex
    .map((entry) => ({ entry, score: scoreArkGmCreatureMatch(entry, normalized) }))
    .filter((match) => Number.isFinite(match.score))
    .sort((left, right) => left.score - right.score || left.entry.order - right.entry.order)
    .slice(0, limit)
    .map((match) => match.entry.option);
}

function scoreArkGmCreatureMatch(entry: ArkGmCreatureSearchEntry, query: string): number {
  if (entry.name === query) return 0;
  if (entry.localizedName === query) return 0;
  if (entry.value === query) return 1;
  if (startsWithArkGmCreatureSearchTerm(entry.name, query)) return 2;
  if (startsWithArkGmCreatureSearchTerm(entry.localizedName, query)) return 2;
  if (containsArkGmCreatureSearchTerm(entry.name, query)) return 3;
  if (containsArkGmCreatureSearchTerm(entry.localizedName, query)) return 3;
  if (startsWithArkGmCreatureSearchTerm(entry.value, query)) return 4;
  if (entry.localizedCategory === query) return 5;
  if (entry.text.includes(query)) return 10;
  return Number.POSITIVE_INFINITY;
}

function startsWithArkGmCreatureSearchTerm(value: string, query: string): boolean {
  return value === query || value.startsWith(`${query} `) || value.startsWith(`${query}-`) || value.startsWith(`${query}_`);
}

function containsArkGmCreatureSearchTerm(value: string, query: string): boolean {
  return startsWithArkGmCreatureSearchTerm(value, query)
    || value.includes(` ${query}`)
    || value.includes(`-${query}`)
    || value.includes(`_${query}`)
    || value.includes(`/${query}`);
}

function normalizeArkGmCreatureSearchText(value: string): string {
  return value.trim().toLowerCase().replace(/[^\p{L}\p{N}_#'/. -]+/gu, " ").replace(/\s+/g, " ");
}
